/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2018. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Federated Identity Management
    Subsystem   :   Federal Criminal Police Office Frontend Customizations

    File        :   ConsoleBundle.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    ConsoleBundle.


    Revisions    Date        Editor      Comment
    ------------+-----------+-----------+-----------------------------------
    1.0.0.0     2018-02-23  DSteding    First release version
*/

package bka.iam.identity.resource;

import oracle.hst.foundation.resource.ListResourceBundle;

////////////////////////////////////////////////////////////////////////////////
// class ConsoleBundle
// ~~~~~ ~~~~~~~~~~~~~
/**
 ** This declares the translated objects by resource keys for message output.
 ** <br>
 ** Used for translation resources to
 ** <ul>
 **   <li>language code common
 **   <li>region   code common
 ** </ul>
 **
 ** @author  dieter.steding@oracle.com
 ** @version 1.0.0.0
 ** @since   1.0.0.0
 */
public class ConsoleBundle extends ListResourceBundle {

  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  private static final String[][] CONTENT = {
    /** Constant used to demarcate catalog entity related messages. */
    {Console.USR_ANONYMIZED_LABEL,   "Anonymized Login"}
  , {Console.USR_ANONYMIZED_HINT,    "The Login Name used by this identity to obfuscated the real identity in outbound communications."}
  , {Console.USR_UNIFIED_LABEL,      "Unified Login"}
  , {Console.USR_UNIFIED_HINT,       "The Login Name used by this identity to be identified in P20 applications and services."}
  , {Console.USR_PARTICIPANT_TITLE,  "Participant"}
  , {Console.USR_PARTICIPANT_LABEL,  "Participant"}
  , {Console.USR_PARTICIPANT_HINT,   "Participant"}
  , {Console.USR_ORGANIZATION_LABEL, "Organizational Unit"}
  , {Console.USR_ORGANIZATION_HINT,  "Organizational Unit"}
  , {Console.USR_DIVISION_LABEL,     "Division"}
  , {Console.USR_DIVISION_HINT,      "Division"}
  , {Console.USR_DEPARTMENT_LABEL,   "Department"}
  , {Console.USR_DEPARTMENT_HINT,    "Department"}
  , {Console.USR_GENERATED_LABEL,    "Generated Identifier"}
  , {Console.USR_GENERATED_HINT,     "Identifier generated by the data source from which the identity was obtained."}
  , {Console.USR_GENERATION_LABEL,   "Principal Name"}
  , {Console.USR_GENERATION_HINT,    "This name is used later to identify the user for authentication purposes.\nA user principal name is not the same as an email address.\nSometimes a user principal name can match a user's email address, but that's not a general rule."}
  , {Console.USR_JOBROLE_LABEL,      "Job Role"}
  , {Console.USR_JOBROLE_HINT,       "The role/rank that the identity has in the organizational structure."}
  , {Console.USR_QUALIFIED_LABEL,    "Qualified Identifier"}
  , {Console.USR_QUALIFIED_HINT,     "Qualified Identifier"}

    /** Constant used to demarcate authorization entity related messages. */
  , {Console.ACC_BADGE_TITLE,        "Authorization" }
  , {Console.ACC_BADGE_HINT,         "See whom has been granted user accounts and entitlements." }
  , {Console.ACC_APPLICATION_MENU,   "Applications" }
  , {Console.ACC_ENTITLEMENT_MENU,   "Entitlements" }

    /** Constant used to demarcate catalog entity related messages. */
  , {Console.CAT_BADGE_TITLE,        "Catalog" }
  , {Console.CAT_BADGE_HINT,         "Manage Catalog Items" }

    /** Constant used to demarcate eFBS entity related messages. */
  , {Console.FBS_TITLE,              "Request eFBS" }
  , {Console.FBS_ACTION_LABEL,       "Request eFBS" }
  , {Console.FBS_ACTION_HINT,        "Requesting special accounts for the application system eFBS." }

    /** Constant used to demarcate access policy evaluation related messages. */
  , {Console.EVAL_ACTION_LABEL,       "Evaluate" }
  , {Console.EVAL_ACTION_HINT,        "Evaluating access policies immediately for the user." }
  };

  //////////////////////////////////////////////////////////////////////////////
  // Methods of abstract base classes
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   getContents (ListResourceBundle)
  /**
   ** Returns an array, where each item in the array is a pair of objects.
   ** <br>
   ** The first element of each pair is the key, which must be a
   ** <code>String</code>, and the second element is the value associated with
   ** that key.
   **
   ** @return                    an array, where each item in the array is a
   **                            pair of objects.
   */
  public Object[][] getContents() {
    return CONTENT;
  }
}