#!/bin/sh
#
# Program.....: sh
#
# Requirements:
#     The database and the listener are up and running.
#     The administration server is up and running.
#     The managed server is up and running
#     iam.env, utility.env is present
#
# Purpose.....:
#     This script onboards lookups from target systems in an Oracle
#     Identity Manager instance.
#
# -----------------------------------------------------------------------
# IMPORTANT
# Please note that script are NOT supported by Oracle Support and are
# available for reference only. You may need to modify the script
# according to your system and startup requirements. Oracle will not
# support the use of these, and you may be required to abandon the use of
# these scripts, if a problem arises.
# -----------------------------------------------------------------------
#
# Author......: Dieter Steding, Oracle Consulting Berlin
#
# Revision   Date        Editor      Comment
# ----------+-----------+-----------+------------------------------------
# 1.0.0.0    2013-05-30  DSteding    First release version
# 1.1.0.0    2015-02-12  UFischer    Added exitOnError functionality & comments
# 1.2.0.0    2015-02-25  DSteding    Add the subcommand publish which
#                                    executes the entity publication
#                                    after all required data are loaded
#

#################### FUNCTIONS start ####################################
# -----------------------------------------------------------------------
# onboard() function
# -----------------------------------------------------------------------
# short-hand function which incorporates the error checking
#   takes any number of arguments and passes them to the onboard script
# -----------------------------------------------------------------------
onboard() {
  cmd="./onboard $*"
  echo $cmd
  $cmd
  exitOnError $cmd
}

# -----------------------------------------------------------------------
# exitOnError() function
# -----------------------------------------------------------------------
# checks the previous command's exit code and depending on the
#  $ABORT_ON_ERROR variable exits the onboarding procedure
# -----------------------------------------------------------------------
exitOnError() {
  errorCode=$?
  if $ABORT_ON_ERROR ; then
    if [ $errorCode -ne 0 ]; then
      echo ABORTED: \'$*\' FAILED
      echo exit code: $errorCode
      exit $errorCode
    fi
  fi
}
#################### FUNCTIONS end ######################################

#################### ON-BOARDING PROCEDURE #############################
#### Intermediate Synchronization of Catalog
onboard lookup 991
#### Account Discovery IDS
onboard account 003
#### Account Discovery CTS
onboard account 004
#### Account Discovery eFBS
onboard account 005
#### Account Discovery PSC
onboard account 006
#### Account Discovery PCF
onboard account 007
#### Account Discovery PIAV
onboard account 008
#### Account Discovery PAP/SZ4
onboard account 009
#### Account Discovery AJS
onboard account 010
#### Account Discovery GAE
onboard account 011