/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Administration Management

    File        :   JobAMClient.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    JobAMClient.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysadmin.module.client;

import java.util.Map;

import oracle.jbo.client.remote.ApplicationModuleImpl;

import oracle.iam.identity.sysadmin.module.common.JobAM;

import oracle.iam.identity.sysadmin.schema.JobAdapter;

////////////////////////////////////////////////////////////////////////////////
// class JobAMClient
// ~~~~~ ~~~~~~~~~~~
/**
 ** The remote {@link ApplicationModuleImpl} to coordinate certain task
 ** belonging to jobs.
 ** <p>
 ** ---------------------------------------------------------------------
 ** ---    File generated by Oracle ADF Business Components Design Time.
 ** ---    Mon Mar 06 19:50:30 CET 2017
 ** ---    Custom code may be added to this class.
 ** ---    Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public class JobAMClient extends    ApplicationModuleImpl
                         implements JobAM {

  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  // the official serial version ID which says cryptically which version we're
  // compatible with
  @SuppressWarnings("compatibility:-250339786379846594")
  private static final long serialVersionUID = -1199150061865928889L;

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>JobAMClient</code> application module that allows use
   ** as a JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public JobAMClient() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methods of implemented interfaces
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchByIdentifier (JobAM)
  /**
   ** Finds a certain <code>Schedule Job</code> by executing a query against the
   ** persistence layer which leverage the primary key of the entity object.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Schedule Job</code> to fetch from the
   **                            persistence layer.
   **                            <br>
   **                            Allowed object is {@link String}.
   */
  @Override
  public void fetchByIdentifier(final String identifier) {
    riInvokeExportedMethod(this, "fetchByIdentifier", new String[]{"java.lang.String"}, new Object[] {identifier});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchByName (JobAM)
  /**
   ** Finds a certain <code>Schedule Job</code> by executing a query against the
   ** persistence layer which leverage the unique name of the entity object.
   **
   ** @param  name               the unique name  of the
   **                            <code>Schedule Job</code> to fetch from the
   **                            persistence layer.
   **                            <br>
   **                            Allowed object is {@link String}.
   */
  @Override
  public void fetchByName(final String name) {
    riInvokeExportedMethod(this, "fetchByName", new String[]{"java.lang.String"}, new Object[] {name});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchDetail (JobAM)
  /**
   ** Initialize the model to maintain an existing <code>Schedule Job</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Schedule Job</code> to fetch from the
   **                            persistence layer.
   **                            <br>
   **                            Allowed object is {@link String}.
   */
  @Override
  public void fetchDetail(final String identifier) {
    this.riInvokeExportedMethod(this, "fetchDetail", new String [] {"java.lang.String"}, new Object[] {identifier});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   createDetail (JobAM)
  /**
   ** Initialize the model to create a new <code>Schedule Job</code>.
   */
  @Override
  public void createDetail() {
    this.riInvokeExportedMethod(this, "createDetail", null, null);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   refreshAttribute (JobAM)
  /**
   ** Refresh the attributes belonging to a certain <code>Schedule Job</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Schedule Job</code> to refresh from the
   **                            persistence layer.
   **                            <br>
   **                            Allowed object is {@link String}.
   */
  @Override
  public void refreshAttribute(final String identifier) {
    riInvokeExportedMethod(this, "refreshAttribute", new String [] {"java.lang.String"}, new Object[] {identifier});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   refreshParameter (JobAM)
  /**
   ** Refresh the <code>Job Parameter</code>s belonging to a certain
   ** <code>Schedule Job</code>.
   **
   ** @param  jobName            the system identifier of the
   **                            <code>Schedule Job</code> to query.
   **                            <br>
   **                            Allowed object is {@link String}.
   ** @param  taskName           the system identifier of the
   **                            <code>Schedule Task</code> to query.
   **                            <br>
   **                            Allowed object is {@link String}.
   ** @param  pending            the collection of pending changes belonging to
   **                            modified values.
   **                            <br>
   **                            Allowed object is {@link Map}.
   */
  @Override
  public void refreshParameter(final String jobName, final String taskName, final Map<String, Map<String, Object>> pending) {
    this.riInvokeExportedMethod(this, "refreshParameter", new String [] {"java.lang.String", "java.lang.String", "java.util.Map<java.lang.String, java.util.Map>"}, new Object[] {jobName, taskName, pending});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   refreshHistory (JobAM)
  /**
   ** Refresh the history belonging to a certain <code>Schedule Job</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Schedule Job</code> to refresh from the
   **                            persistence layer.
   **                            <br>
   **                            Allowed object is {@link String}.
   */
  @Override
  public void refreshHistory(final String identifier) {
    riInvokeExportedMethod(this, "refreshHistory", new String [] {"java.lang.String"}, new Object[] {identifier});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   commitDetail  (JobAM)
  /**
   ** Committing changes to a <code>Schedule Job</code>.
   **
   ** @param  mode               the mode of transction to perfom.
   **                            <br>
   **                            Allowed object is {@link String}.
   ** @param  bean               the {@link JobAdapter} providing access to the
   **                            changes to apply.
   **                            <br>
   **                            Allowed object is {@link JobAdapter}.
   **
   ** @return                    <code>true</code> id the transaction is
   **                            completed successful.
   **                            <br>
   **                            Possible object is {@link Boolean}.
   */
  @Override
  public Boolean commitDetail(final String mode, final JobAdapter bean) {
    riInvokeExportedMethod(this, "commitDetail", new String [] {"java.lang.String", "java.lang.String"}, new Object[] {mode, bean});
    return Boolean.TRUE;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   start (JobAM)
  /**
   ** Starts the execution of an existing <code>Schedule Job</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Schedule Job</code> to start.
   **                            <br>
   **                            Allowed object is {@link String}.
   */
  @Override
  public void start(final String identifier) {
    riInvokeExportedMethod(this, "start", new String [] {"java.lang.String"}, new Object[] {identifier});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   stop (JobAM)
  /**
   ** Stops the execution of an existing <code>Schedule Job</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Schedule Job</code> to stop.
   **                            <br>
   **                            Allowed object is {@link String}.
   */
  @Override
  public void stop(final String identifier) {
    riInvokeExportedMethod(this, "stop", new String [] {"java.lang.String"}, new Object[] {identifier});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   enable (JobAM)
  /**
   ** Enables an deactivated <code>Schedule Job</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Schedule Job</code> to enable.
   **                            <br>
   **                            Allowed object is {@link String}.
   */
  @Override
  public void enable(final String identifier) {
    riInvokeExportedMethod(this, "enable", new String [] {"java.lang.String"}, new Object[] {identifier});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   disable (JobAM)
  /**
   ** Disables an activated <code>Schedule Job</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Schedule Job</code> to disable.
   **                            <br>
   **                            Allowed object is {@link String}.
   */
  @Override
  public void disable(final String identifier) {
    riInvokeExportedMethod(this, "disable", new String [] {"java.lang.String"}, new Object[] {identifier});
  }
}