/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Administration Management

    File        :   TaskAMClient.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    TaskAMClient.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysadmin.module.client;

import java.util.Map;

import oracle.jbo.client.remote.ApplicationModuleImpl;

import oracle.iam.identity.sysadmin.module.common.TaskAM;

////////////////////////////////////////////////////////////////////////////////
// class TaskAMClient
// ~~~~~ ~~~~~~~~~~~~
/**
 ** The remote {@link ApplicationModuleImpl} to coordinate certain task
 ** belonging to jobs.
 ** <p>
 ** ---------------------------------------------------------------------
 ** ---    File generated by Oracle ADF Business Components Design Time.
 ** ---    Mon Mar 06 19:50:30 CET 2017
 ** ---    Custom code may be added to this class.
 ** ---    Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public class TaskAMClient extends    ApplicationModuleImpl
                          implements TaskAM {

  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  // the official serial version ID which says cryptically which version we're
  // compatible with
  @SuppressWarnings("compatibility:2134466411613207219")
  private static final long serialVersionUID = 3659615172007921690L;

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>TaskAMClient</code> application module that allows use
   ** as a JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public TaskAMClient() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methods of implemented interfaces
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchByIdentifier (TaskAM)
  /**
   ** Finds a certain <code>Scheduler Task</code> by executing a query against
   ** the persistence layer which leverage the primary key of the entity object.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Scheduler Task</code> to fetch from the
   **                            persistence layer.
   **                            <br>
   **                            Allowed object is {@link String}.
   */
  @Override
  public void fetchByIdentifier(final String identifier) {
    riInvokeExportedMethod(this, "fetchByIdentifier", new String[]{"java.lang.String"}, new Object[] {identifier});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchByName (TaskAM)
  /**
   ** Finds a certain <code>Scheduler Task</code> by executing a query against
   ** the persistence layer which leverage the unique name of the entity object.
   **
   ** @param  name               the unique name of the
   **                            <code>Scheduler Task</code> to fetch from the
   **                            persistence layer.
   **                            <br>
   **                            Allowed object is {@link String}.
   */
  @Override
  public void fetchByName(final String name) {
    riInvokeExportedMethod(this, "fetchByName", new String[]{"java.lang.String"}, new Object[] {name});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   createDetail (JobAM)
  /**
   ** Initialize the model to create a new <code>Schedule Task</code>.
   */
  @Override
  public void createDetail() {
    this.riInvokeExportedMethod(this, "createDetail", null, null);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchDetail (TaskAM)
  /**
   ** Initialize the model to maintain an existing <code>Scheduler Task</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Scheduler Task</code> to fetch from the
   **                            persistence layer.
   **                            <br>
   **                            Allowed object is {@link String}.
   */
  @Override
  public void fetchDetail(final String identifier) {
    this.riInvokeExportedMethod(this, "fetchDetail", new String [] {"java.lang.String"}, new Object[] {identifier});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   refreshAttribute (TaskAM)
  /**
   ** Refresh the attributes belonging to a certain
   ** <code>Scheduler Task</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Scheduler Task</code> to
   **                            initialize.
   **                            <br>
   **                            Allowed object is {@link String}.
   */
  @Override
  public void refreshAttribute(final String identifier) {
    riInvokeExportedMethod(this, "refreshAttribute", new String [] {"java.lang.String"}, new Object[] {identifier});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   refreshParameter (TaskAM)
  /**
   ** Refresh the <code>Task Parameter</code>s belonging to a certain
   ** <code>Schedule Task</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Schedule Task</code> to query.
   **                            <br>
   **                            Allowed object is {@link String}.
   ** @param  pending            the collection of pending changes belonging to
   **                            added, deleted and modified values.
   **                            <br>
   **                            Allowed object is {@link Map}.
   */
  @Override
  public void refreshParameter(final String identifier, final Map<String, Map<String, Object>> pending) {
    riInvokeExportedMethod(this, "refreshParameter", new String [] {"java.lang.String", "java.util.Map<String, java.util.Map>"}, new Object[] {identifier, pending});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   refreshJob (TaskAM)
  /**
   ** Refresh the jobs belonging to a certain <code>Schedule Task</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Schedule Job</code> to refresh from the
   **                            persistence layer.
   **                            <br>
   **                            Allowed object is {@link String}.
   */
  @Override
  public void refreshJob(final String identifier) {
    riInvokeExportedMethod(this, "refreshJob", new String [] {"java.lang.String"}, new Object[] {identifier});
  }
}