/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Provisioning Management

    File        :   AccountVORowImpl.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    AccountVORowImpl.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysprov.model.view;

import java.util.Date;

import oracle.jbo.server.ViewRowImpl;

import oracle.iam.identity.sysprov.model.entity.AccountEOImpl;

////////////////////////////////////////////////////////////////////////////////
// class AccountVORowImpl
// ~~~~~ ~~~~~~~~~~~~~~~~
/**
 ** ---------------------------------------------------------------------
 ** --- File generated by Oracle ADF Business Components Design Time.
 ** --- Tue Mar 07 07:51:54 CET 2017
 ** --- Custom code may be added to this class.
 ** --- Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public class AccountVORowImpl extends ViewRowImpl {

  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  public static final int ACCOUNTKEY                      = AttributesEnum.accountKey.ordinal();
  public static final int ACCOUNTTYPE                     = AttributesEnum.accountType.ordinal();
  public static final int ACCOUNTMECHANISM                = AttributesEnum.accountMechanism.ordinal();
  public static final int ACCOUNTRISKMECHANISM            = AttributesEnum.accountRiskMechanism.ordinal();
  public static final int ACCOUNTRISKITEM                 = AttributesEnum.accountRiskItem.ordinal();
  public static final int ACCOUNTRISKSUMMARY              = AttributesEnum.accountRiskSummary.ordinal();
  public static final int ACCOUNTRISKUPDATE               = AttributesEnum.accountRiskUpdate.ordinal();
  public static final int ACCOUNTLASTCERIFICATIONMRISK    = AttributesEnum.accountLastCerificationRisk.ordinal();
  public static final int ACCOUNTLASTCERIFICATIONDECISION = AttributesEnum.accountLastCerificationDecision.ordinal();
  public static final int ACCOUNTOPENSODVIOLATION         = AttributesEnum.accountOpenSodViolation.ordinal();
  public static final int ACCOUNTPROVISIONINGSTART        = AttributesEnum.accountProvisioningStart.ordinal();
  public static final int ACCOUNTPROVISIONINGEND          = AttributesEnum.accountProvisioningEnd.ordinal();
  public static final int REQUESTKEY                      = AttributesEnum.requestKey.ordinal();
  public static final int POLICYKEY                       = AttributesEnum.policyKey.ordinal();
  public static final int APPINSTANCEKEY                  = AttributesEnum.appInstanceKey.ordinal();
  public static final int OBJECTINSTANCEKEY               = AttributesEnum.objectInstanceKey.ordinal();
  public static final int OBJECTINSTANCESTATUS            = AttributesEnum.objectInstanceStatus.ordinal();
  public static final int RESOURCEKEY                     = AttributesEnum.resourceKey.ordinal();
  public static final int RESOURCENAME                    = AttributesEnum.resourceName.ordinal();
  public static final int RESOURCETYPE                    = AttributesEnum.resourceType.ordinal();
  public static final int PROCESSINSTANCEKEY              = AttributesEnum.processInstanceKey.ordinal();
  public static final int PROCESSINSTANCESTATUS           = AttributesEnum.processInstanceStatus.ordinal();
  public static final int PROCESSINSTANCENAME             = AttributesEnum.processInstanceName.ordinal();
  public static final int PROCESSINSTANCEARCHIVED         = AttributesEnum.processInstanceArchived.ordinal();
  public static final int PROCESSINSTANCECREATEDATE       = AttributesEnum.processInstanceCreateDate.ordinal();
  public static final int PROCESSINSTANCEUPDATEDATE       = AttributesEnum.processInstanceUpdateDate.ordinal();
  public static final int BENEFICIARYKEY                  = AttributesEnum.beneficiaryKey.ordinal();
  public static final int BENEFICIARYLOGIN                = AttributesEnum.beneficiaryLogin.ordinal();
  public static final int BENEFICIARYFIRSTNAME            = AttributesEnum.beneficiaryFirstName.ordinal();
  public static final int BENEFICIARYLASTNAME             = AttributesEnum.beneficiaryLastName.ordinal();
  public static final int ORGANIZATIONKEY                 = AttributesEnum.organizationKey.ordinal();
  public static final int ORGANIZATIONNAME                = AttributesEnum.organizationName.ordinal();

  //////////////////////////////////////////////////////////////////////////////
  // Member classes
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // class AttributesEnum
  /**
   ** AttributesEnum: generated enum for identifying attributes and accessors.
   ** Do not modify.
   */
  @SuppressWarnings({ "oracle.jbo.attribute-enumeration-classes-rule", "oracle.jbo.attribute-order-rule" })
  private static enum AttributesEnum {
    accountKey
    , accountType
    , accountMechanism
    , accountRiskMechanism
    , accountRiskItem
    , accountRiskSummary
    , accountRiskUpdate
    , accountLastCerificationRisk
    , accountLastCerificationDecision
    , accountOpenSodViolation
    , accountProvisioningStart
    , accountProvisioningEnd
    , requestKey
    , policyKey
    , appInstanceKey
    , objectInstanceKey
    , objectInstanceStatus
    , resourceKey
    , resourceName
    , resourceType
    , processInstanceKey
    , processInstanceStatus
    , processInstanceName
    , processInstanceArchived
    , processInstanceCreateDate
    , processInstanceUpdateDate
    , beneficiaryKey
    , beneficiaryLogin
    , beneficiaryFirstName
    , beneficiaryLastName
    , organizationKey
    , organizationName
    ;
  };

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>AccountVORowImpl</code> view object that
   ** allows use as a JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public AccountVORowImpl() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Accessor and Mutator methods
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getAccountEO
  /**
   ** Returns the Account entity object.
   **
   ** @return                    the AccountEO
   */
  public AccountEOImpl getAccountEO() {
    return (AccountEOImpl)getEntity(0);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setAccountKey
  /**
   ** Sets the attribute value for <code>ACCOUNTKEY</code> using the alias name
   ** <code>accountKey</code>.
   **
   ** @param  value              the attribute value for <code>ACCOUNTKEY</code>
   **                            using the alias name <code>accountKey</code>.
   **                            Allowed object is {@link Long}.
   */
  public void setAccountKey(final Long value) {
    setAttributeInternal(ACCOUNTKEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getAccountKey
  /**
   ** Returns the attribute value for <code>ACCOUNTKEY</code> using the alias
   ** name <code>accountKey</code>.
   **
   ** @return                    the attribute value for <code>ACCOUNTKEY</code>
   **                            using the alias name <code>accountKey</code>.
   **                            Possible object is {@link Long}.
   */
  public Long getAccountKey() {
    return (Long)getAttributeInternal(ACCOUNTKEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setAccountType
  /**
   ** Sets the attribute value for <code>ACCOUNTTYPE</code> using the alias name
   ** <code>accountType</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>ACCOUNTTYPE</code> using the alias name
   **                            <code>accountType</code>.
   **                            Allowed object is {@link String}.
   */
  public void setAccountType(final String value) {
    setAttributeInternal(ACCOUNTTYPE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getAccountType
  /**
   ** Returns the attribute value for <code>ACCOUNTTYPE</code> using the alias
   ** name <code>accountType</code>.
   **
   ** @return                    the attribute value for
   **                            <code>ACCOUNTTYPE</code> using the alias name
   **                            <code>accountType</code>.
   **                            Possible object is {@link String}.
   */
  public String getAccountType() {
    return (String)getAttributeInternal(ACCOUNTTYPE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setAccountMechanism
  /**
   ** Sets the attribute value for <code>ACCOUNTMECHANISM</code> using the alias
   ** name <code>accountMechanism</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>ACCOUNTMECHANISM</code> using the alias
   **                            name <code>accountMechanism</code>.
   **                            Allowed object is {@link String}.
   */
  public void setAccountMechanism(final String value) {
    setAttributeInternal(ACCOUNTMECHANISM, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getAccountMechanism
  /**
   ** Returns the attribute value for <code>ACCOUNTMECHANISM</code> using the
   ** alias name <code>accountMechanism</code>.
   **
   ** @return                    the attribute value for
   **                            <code>ACCOUNTMECHANISM</code> using the alias
   **                            name <code>accountMechanism</code>.
   **                            Possible object is {@link String}.
   */
  public String getAccountMechanism() {
    return (String)getAttributeInternal(ACCOUNTMECHANISM);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setAccountRiskMechanism
  /**
   ** Sets the attribute value for <code>ACCOUNTRISKMECHANISM</code> using the
   ** alias name <code>accountRiskMechanism</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>ACCOUNTRISKMECHANISM</code> using the
   **                            alias name <code>accountRiskMechanism</code>.
   **                            Allowed object is {@link Integer}.
   */
  public void setAccountRiskMechanism(final Integer value) {
    setAttributeInternal(ACCOUNTRISKMECHANISM, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getAccountRiskMechanism
  /**
   ** Returns the attribute value for <code>ACCOUNTRISKMECHANISM</code> using
   ** the alias name <code>accountRiskMechanism</code>.
   **
   ** @return                    the attribute value for
   **                            <code>ACCOUNTRISKMECHANISM</code> using the
   **                            alias name <code>accountRiskMechanism</code>.
   **                            Possible object is {@link Integer}.
   */
  public Integer getAccountRiskMechanism() {
    return (Integer)getAttributeInternal(ACCOUNTRISKMECHANISM);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setAccountRiskItem
  /**
   ** Sets the attribute value for <code>ACCOUNTRISKITEM</code> using the alias
   ** name <code>accountRiskItem</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>ACCOUNTRISKITEM</code> using the alias
   **                            name <code>accountRiskItem</code>.
   **                            Allowed object is {@link Integer}.
   */
  public void setAccountRiskItem(final Integer value) {
    setAttributeInternal(ACCOUNTRISKITEM, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getAccountRiskItem
  /**
   ** Returns the attribute value for <code>ACCOUNTRISKITEM</code> using the
   ** alias name <code>accountRiskItem</code>.
   **
   ** @return                    the attribute value for
   **                            <code>ACCOUNTRISKITEM</code> using the alias
   **                            name <code>accountRiskItem</code>.
   **                            Possible object is {@link Integer}.
   */
  public Integer getAccountRiskItem() {
    return (Integer)getAttributeInternal(ACCOUNTRISKITEM);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setAccountRiskSummary
  /**
   ** Sets the attribute value for <code>ACCOUNTRISKSUMMARY</code> using the
   ** alias name <code>accountRiskSummary</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>ACCOUNTRISKSUMMARY</code> using the alias
   **                            name <code>accountRiskSummary</code>.
   **                            Allowed object is {@link Integer}.
   */
  public void setAccountRiskSummary(final Integer value) {
    setAttributeInternal(ACCOUNTRISKSUMMARY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getAccountRiskSummary
  /**
   ** Returns the attribute value for <code>ACCOUNTRISKSUMMARY</code> using the
   ** alias name <code>accountRiskSummary</code>.
   **
   ** @return                    the attribute value for
   **                            <code>ACCOUNTRISKSUMMARY</code> using the alias
   **                            name <code>accountRiskSummary</code>.
   **                            Possible object is {@link Integer}.
   */
  public Integer getAccountRiskSummary() {
    return (Integer)getAttributeInternal(ACCOUNTRISKSUMMARY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setAccountRiskUpdate
  /**
   ** Sets the attribute value for <code>ACCOUNTRISKUPDATE</code> using the
   ** alias name <code>accountRiskUpdate</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>ACCOUNTRISKUPDATE</code> using the alias
   **                            name <code>accountRiskUpdate</code>.
   **                            Allowed object is {@link Date}.
   */
  public void setAccountRiskUpdate(final Date value) {
    setAttributeInternal(ACCOUNTRISKUPDATE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getAccountRiskUpdate
  /**
   ** Returns the attribute value for <code>ACCOUNTRISKUPDATE</code> using the
   ** alias name <code>accountRiskUpdate</code>.
   **
   ** @return                    the attribute value for
   **                            <code>ACCOUNTRISKUPDATE</code> using the alias
   **                            name <code>accountRiskUpdate</code>.
   **                            Possible object is {@link Date}.
   */
  public Date getAccountRiskUpdate() {
    return (Date)getAttributeInternal(ACCOUNTRISKUPDATE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setAccountLastCerificationRisk
  /**
   ** Sets the attribute value for <code>ACCOUNTLASTCERIFICATIONMRISK</code>
   ** using the alias name <code>accountLastCerificationRisk</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>ACCOUNTLASTCERIFICATIONMRISK</code>
   **                            using the alias name
   **                            <code>accountLastCerificationRisk</code>.
   **                            Allowed object is {@link Integer}.
   */
  public void setAccountLastCerificationRisk(final Integer value) {
    setAttributeInternal(ACCOUNTLASTCERIFICATIONMRISK, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getAccountLastCerificationRisk
  /**
   ** Returns the attribute value for
   ** <code>ACCOUNTLASTCERIFICATIONMRISK</code> using the alias name
   ** <code>accountLastCerificationRisk</code>.
   **
   ** @return                    the attribute value for
   **                            <code>ACCOUNTLASTCERIFICATIONMRISK</code>
   **                            using the alias name
   **                            <code>accountLastCerificationRisk</code>.
   **                            Possible object is {@link Integer}.
   */
  public Integer getAccountLastCerificationRisk() {
    return (Integer)getAttributeInternal(ACCOUNTLASTCERIFICATIONMRISK);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setAccountLastCerificationDecision
  /**
   ** Sets the attribute value for <code>ACCOUNTLASTCERIFICATIONDECISION</code>
   ** using the alias name <code>accountLastCerificationDecision</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>ACCOUNTLASTCERIFICATIONDECISION</code>
   **                            using the alias name
   **                            <code>accountLastCerificationDecision</code>.
   **                            Allowed object is {@link Integer}.
   */
  public void setAccountLastCerificationDecision(final Integer value) {
    setAttributeInternal(ACCOUNTLASTCERIFICATIONDECISION, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getAccountLastCerificationDecision
  /**
   ** Returns the attribute value for
   ** <code>ACCOUNTLASTCERIFICATIONDECISION</code> using the alias name
   ** <code>accountLastCerificationDecision</code>.
   **
   ** @return                    the attribute value for
   **                            <code>ACCOUNTLASTCERIFICATIONDECISION</code>
   **                            using the alias name
   **                            <code>accountLastCerificationDecision</code>.
   **                            Possible object is {@link Integer}.
   */
  public Integer getAccountLastCerificationDecision() {
    return (Integer)getAttributeInternal(ACCOUNTLASTCERIFICATIONDECISION);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setAccountOpenSodViolation
  /**
   ** Sets the attribute value for <code>ACCOUNTOPENSODVIOLATION</code> using
   ** the alias name <code>accountOpenSodViolation</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>ACCOUNTOPENSODVIOLATION</code> using the
   **                            alias name
   **                            <code>accountOpenSodViolation</code>.
   **                            Allowed object is {@link Boolean}.
   */
  public void setAccountOpenSodViolation(final Boolean value) {
    setAttributeInternal(ACCOUNTOPENSODVIOLATION, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getAccountOpenSodViolation
  /**
   ** Returns the attribute value for <code>ACCOUNTOPENSODVIOLATION</code> using
   ** the alias name <code>accountOpenSodViolation</code>.
   **
   ** @return                    the attribute value for
   **                            <code>ACCOUNTOPENSODVIOLATION</code> using the
   **                            alias name
   **                            <code>accountOpenSodViolation</code>.
   **                            Possible object is {@link Boolean}.
   */
  public Boolean getAccountOpenSodViolation() {
    return (Boolean)getAttributeInternal(ACCOUNTOPENSODVIOLATION);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setAccountProvisioningStart
  /**
   ** Sets the attribute value for <code>ACCOUNTPROVISIONINGSTART</code> using
   ** the alias name <code>accountProvisioningStart</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>ACCOUNTPROVISIONINGSTART</code> using the
   **                            alias name
   **                            <code>accountProvisioningStart</code>.
   **                            Allowed object is {@link Date}.
   */
  public void setAccountProvisioningStart(final Date value) {
    setAttributeInternal(ACCOUNTPROVISIONINGSTART, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getAccountProvisioningStart
  /**
   ** Returns the attribute value for <code>ACCOUNTPROVISIONINGSTART</code>
   ** using the alias name <code>accountProvisioningStart</code>.
   **
   ** @return                    the attribute value for
   **                            <code>ACCOUNTPROVISIONINGSTART</code> using the
   **                            alias name
   **                            <code>accountProvisioningStart</code>.
   **                            Possible object is {@link Date}.
   */
  public Date getAccountProvisioningStart() {
    return (Date)getAttributeInternal(ACCOUNTPROVISIONINGSTART);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setAccountProvisioningEnd
  /**
   ** Sets the attribute value for <code>ACCOUNTPROVISIONINGEND</code> using the
   ** alias name <code>accountProvisioningEnd</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>ACCOUNTPROVISIONINGEND</code> using the
   **                            alias name <code>accountProvisioningEnd</code>.
   **                            Allowed object is {@link Date}.
   */
  public void setAccountProvisioningEnd(final Date value) {
    setAttributeInternal(ACCOUNTPROVISIONINGEND, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getAccountProvisioningEnd
  /**
   ** Returns the attribute value for <code>ACCOUNTPROVISIONINGEND</code> using
   ** the alias name <code>accountProvisioningEnd</code>.
   **
   ** @return                    the attribute value for
   **                            <code>ACCOUNTPROVISIONINGEND</code> using the
   **                            alias name <code>accountProvisioningEnd</code>.
   **                            Possible object is {@link Date}.
   */
  public Date getAccountProvisioningEnd() {
    return (Date)getAttributeInternal(ACCOUNTPROVISIONINGEND);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setRequestKey
  /**
   ** Sets the attribute value for <code>REQUESTKEY</code> using the alias name
   ** <code>requestKey</code>.
   **
   ** @param  value              the attribute value for <code>REQUESTKEY</code>
   **                            using the alias name <code>requestKey</code>.
   **                            Allowed object is {@link Long}.
   */
  public void setRequestKey(final Long value) {
    setAttributeInternal(REQUESTKEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getRequestKey
  /**
   ** Returns the attribute value for <code>REQUESTKEY</code> using the alias
   ** name <code>requestKey</code>.
   **
   ** @return                    the attribute value for <code>REQUESTKEY</code>
   **                            using the alias name <code>requestKey</code>.
   **                            Possible object is {@link Long}.
   */
  public Long getRequestKey() {
    return (Long)getAttributeInternal(REQUESTKEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setPolicyKey
  /**
   ** Sets the attribute value for <code>POLICYKEY</code> using the alias name
   ** <code>policyKey</code>.
   **
   ** @param  value              the attribute value for <code>POLICYKEY</code>
   **                            using the alias name <code>policyKey</code>.
   **                            Allowed object is {@link Long}.
   */
  public void setPolicyKey(final Long value) {
    setAttributeInternal(POLICYKEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getPolicyKey
  /**
   ** Returns the attribute value for <code>POLICYKEY</code> using the alias
   ** name <code>policyKey</code>.
   **
   ** @return                    the attribute value for <code>POLICYKEY</code>
   **                            using the alias name <code>policyKey</code>.
   **                            Possible object is {@link Long}.
   */
  public Long getPolicyKey() {
    return (Long)getAttributeInternal(POLICYKEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setAppInstanceKey
  /**
   ** Sets the attribute value for <code>APPINSTANCEKEY</code> using the alias
   ** name <code>appInstanceKey</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>APPINSTANCEKEY</code> using the alias
   **                            name <code>appInstanceKey</code>.
   **                            Allowed object is {@link Long}.
   */
  public void setAppInstanceKey(final Long value) {
    setAttributeInternal(APPINSTANCEKEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getAppInstanceKey
  /**
   ** Returns the attribute value for <code>APPINSTANCEKEY</code> using the
   ** alias name <code>appInstanceKey</code>.
   **
   ** @return                    the attribute value for
   **                            <code>APPINSTANCEKEY</code> using the alias
   **                            name <code>appInstanceKey</code>.
   **                            Possible object is {@link Long}.
   */
  public Long getAppInstanceKey() {
    return (Long)getAttributeInternal(APPINSTANCEKEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setObjectInstanceKey
  /**
   ** Sets the attribute value for <code>OBJECTINSTANCEKEY</code> using the
   ** alias name <code>objectInstanceKey</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>OBJECTINSTANCEKEY</code> using the alias
   **                            name <code>objectInstanceKey</code>.
   **                            Allowed object is {@link Long}.
   */
  public void setObjectInstanceKey(final Long value) {
    setAttributeInternal(OBJECTINSTANCEKEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getObjectInstanceKey
  /**
   ** Returns the attribute value for <code>OBJECTINSTANCEKEY</code> using the
   ** alias name <code>objectInstanceKey</code>.
   **
   ** @return                    the attribute value for
   **                            <code>OBJECTINSTANCEKEY</code> using the alias
   **                            name <code>objectInstanceKey</code>.
   **                            Possible object is {@link Long}.
   */
  public Long getObjectInstanceKey() {
    return (Long)getAttributeInternal(OBJECTINSTANCEKEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setObjectInstanceStatus
  /**
   ** Sets the attribute value for <code>OBJECTINSTANCESTATUS</code> using the
   ** alias name <code>objectInstanceStatus</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>OBJECTINSTANCESTATUS</code> using the
   **                            alias name <code>objectInstanceStatus</code>.
   **                            Allowed object is {@link String}.
   */
  public void setObjectInstanceStatus(final String value) {
    setAttributeInternal(OBJECTINSTANCESTATUS, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getObjectInstanceStatus
  /**
   ** Returns the attribute value for <code>OBJECTINSTANCESTATUS</code> using
   ** the alias name <code>objectInstanceStatus</code>.
   **
   ** @return                    the attribute value for
   **                            <code>OBJECTINSTANCESTATUS</code> using the
   **                            alias name <code>objectInstanceStatus</code>.
   **                            Possible object is {@link String}.
   */
  public String getObjectInstanceStatus() {
    return (String)getAttributeInternal(OBJECTINSTANCESTATUS);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setResourceKey
  /**
   ** Sets the attribute value for <code>RESOURCEKEY</code> using the alias name
   ** <code>resourceKey</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>RESOURCEKEY</code> using the alias name
   **                            <code>resourceKey</code>.
   **                            Allowed object is {@link Long}.
   */
  public void setResourceKey(final Long value) {
    setAttributeInternal(RESOURCEKEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getResourceKey
  /**
   ** Returns the attribute value for <code>RESOURCEKEY</code> using the alias
   ** name <code>resourceKey</code>.
   **
   ** @return                    the attribute value for
   **                            <code>RESOURCEKEY</code> using the alias name
   **                            <code>resourceKey</code>.
   **                            Possible object is {@link Long}.
   */
  public Long getResourceKey() {
    return (Long)getAttributeInternal(RESOURCEKEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setResourceName
  /**
   ** Sets the attribute value for <code>RESOURCENAME</code> using the alias
   ** name <code>resourceName</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>RESOURCENAME</code> using the alias name
   **                            <code>resourceName</code>.
   **                            Allowed object is {@link String}.
   */
  public void setResourceName(final String value) {
    setAttributeInternal(RESOURCENAME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getResourceName
  /**
   ** Returns the attribute value for <code>RESOURCENAME</code> using the alias
   ** name <code>resourceName</code>.
   **
   ** @return                    the attribute value for
   **                            <code>RESOURCENAME</code> using the alias name
   **                            <code>resourceName</code>.
   **                            Possible object is {@link String}.
   */
  public String getResourceName() {
    return (String)getAttributeInternal(RESOURCENAME);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setResourceType
  /**
   ** Sets the attribute value for <code>RESOURCETYPE</code> using the alias
   ** name <code>resourceType</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>RESOURCETYPE</code> using the alias name
   **                            <code>resourceType</code>.
   **                            Allowed object is {@link String}.
   */
  public void setResourceType(final String value) {
    setAttributeInternal(RESOURCETYPE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getResourceType
  /**
   ** Returns the attribute value for <code>RESOURCETYPE</code> using the alias
   ** name <code>resourceType</code>.
   **
   ** @return                    the attribute value for
   **                            <code>RESOURCETYPE</code> using the alias name
   **                            <code>resourceType</code>.
   **                            Possible object is {@link String}.
   */
  public String getResourceType() {
    return (String)getAttributeInternal(RESOURCETYPE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setProcessInstanceKey
  /**
   ** Sets the attribute value for <code>PROCESSINSTANCEKEY</code> using the
   ** alias name <code>processInstanceKey</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>PROCESSINSTANCEKEY</code> using the
   **                            alias name <code>processInstanceKey</code>.
   **                            Allowed display is {@link Long}.
   */
  public void setProcessInstanceKey(final Long value) {
    setAttributeInternal(PROCESSINSTANCEKEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getProcessInstanceKey
  /**
   ** Returns the attribute value for <code>PROCESSINSTANCEKEY</code> using
   ** the alias name <code>processInstanceKey</code>.
   **
   ** @return                    the attribute value for
   **                            <code>PROCESSINSTANCEKEY</code> using the
   **                            alias name <code>processInstanceKey</code>.
   **                            Possible display is {@link Long}.
   */
  public Long getProcessInstanceKey() {
    return (Long)getAttributeInternal(PROCESSINSTANCEKEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setProcessInstanceStatus
  /**
   ** Sets the attribute value for <code>PROCESSINSTANCESTATUS</code> using the
   ** alias name <code>processInstanceStatus</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>PROCESSINSTANCESTATUS</code> using the
   **                            alias name <code>processInstanceStatus</code>.
   **                            Allowed object is {@link String}.
   */
  public void setProcessInstanceStatus(final String value) {
    setAttributeInternal(PROCESSINSTANCESTATUS, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getProcessInstanceStatus
  /**
   ** Returns the attribute value for <code>PROCESSINSTANCESTATUS</code> using the
   ** alias name <code>processInstanceStatus</code>.
   **
   ** @return                    the attribute value for
   **                            <code>PROCESSINSTANCESTATUS</code> using the
   **                            alias name <code>processInstanceStatus</code>.
   **                            Possible object is {@link String}.
   */
  public String getProcessInstanceStatus() {
    return (String)getAttributeInternal(PROCESSINSTANCESTATUS);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setProcessInstanceName
  /**
   ** Sets the attribute value for <code>PROCESSINSTANCENAME</code> using the
   ** alias name <code>processInstanceName</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>PROCESSINSTANCENAME</code> using the
   **                            alias name <code>processInstanceName</code>.
   **                            Allowed object is {@link String}.
   */
  public void setProcessInstanceName(final String value) {
    setAttributeInternal(PROCESSINSTANCENAME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getProcessInstanceName
  /**
   ** Returns the attribute value for <code>PROCESSINSTANCENAME</code> using the
   ** alias name <code>processInstanceName</code>.
   **
   ** @return                    the attribute value for
   **                            <code>PROCESSINSTANCENAME</code> using the
   **                            alias name <code>processInstanceName</code>.
   **                            Possible object is {@link String}.
   */
  public String getProcessInstanceName() {
    return (String)getAttributeInternal(PROCESSINSTANCENAME);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setProcessInstanceArchived
  /**
   ** Sets the attribute value for <code>PROCESSINSTANCEARCHIVED</code> using
   ** the alias name <code>processInstanceArchived</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>PROCESSINSTANCEARCHIVED</code> using
   **                            the alias name
   **                            <code>processInstanceArchived</code>.
   **                            Allowed object is {@link Boolean}.
   */
  public void setProcessInstanceArchived(final Boolean value) {
    setAttributeInternal(PROCESSINSTANCEARCHIVED, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getProcessInstanceArchived
  /**
   ** Returns the attribute value for <code>PROCESSINSTANCEARCHIVED</code>
   ** using the alias name <code>processInstanceArchived</code>.
   **
   ** @return                    the attribute value for
   **                            <code>PROCESSINSTANCEARCHIVED</code> using
   **                            the alias name
   **                            <code>processInstanceArchived</code>.
   **                            Possible object is {@link Boolean}.
   */
  public Boolean getProcessInstanceArchived() {
    return (Boolean)getAttributeInternal(PROCESSINSTANCEARCHIVED);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setProcessInstanceCreateDate
  /**
   ** Sets the attribute value for <code>PROCESSINSTANCECREATEDATE</code> using
   ** the alias name <code>processInstanceCreateDate</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>PROCESSINSTANCECREATEDATE</code> using
   **                            the alias name
   **                            <code>processInstanceCreateDate</code>.
   **                            Allowed object is {@link Date}.
   */
  public void setProcessInstanceCreateDate(final Date value) {
    setAttributeInternal(PROCESSINSTANCECREATEDATE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getProcessInstanceCreateDate
  /**
   ** Returns the attribute value for <code>PROCESSINSTANCECREATEDATE</code>
   ** using the alias name <code>processInstanceCreateDate</code>.
   **
   ** @return                    the attribute value for
   **                            <code>PROCESSINSTANCECREATEDATE</code> using
   **                            the alias name
   **                            <code>processInstanceCreateDate</code>.
   **                            Possible object is {@link Date}.
   */
  public Date getProcessInstanceCreateDate() {
    return (Date)getAttributeInternal(PROCESSINSTANCECREATEDATE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setProcessInstanceUpdateDate
  /**
   ** Sets the attribute value for <code>PROCESSINSTANCEUPDATEDATE</code> using
   ** the alias name <code>processInstanceUpdateDate</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>PROCESSINSTANCEUPDATEDATE</code> using
   **                            the alias name
   **                            <code>processInstanceUpdateDate</code>.
   **                            Allowed object is {@link Date}.
   */
  public void setProcessInstanceUpdateDate(final Date value) {
    setAttributeInternal(PROCESSINSTANCEUPDATEDATE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getProcessInstanceUpdateDate
  /**
   ** Returns the attribute value for <code>PROCESSINSTANCEUPDATEDATE</code>
   ** using the alias name <code>processInstanceUpdateDate</code>.
   **
   ** @return                    the attribute value for
   **                            <code>PROCESSINSTANCEUPDATEDATE</code> using
   **                            the alias name
   **                            <code>processInstanceUpdateDate</code>.
   **                            Possible object is {@link Date}.
   */
  public Date getProcessInstanceUpdateDate() {
    return (Date)getAttributeInternal(PROCESSINSTANCEUPDATEDATE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setBeneficiaryKey
  /**
   ** Sets the attribute value for <code>BENEFICIARYKEY</code> using the alias
   ** name <code>beneficiaryKey</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>BENEFICIARYKEY</code> using the alias
   **                            name <code>beneficiaryKey</code>.
   **                            Allowed object is {@link Long}.
   */
  public void setBeneficiaryKey(final Long value) {
    setAttributeInternal(BENEFICIARYKEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getBeneficiaryKey
  /**
   ** Returns the attribute value for <code>BENEFICIARYKEY</code> using the
   ** alias name <code>beneficiaryKey</code>.
   **
   ** @return                    the attribute value for
   **                            <code>BENEFICIARYKEY</code> using the alias
   **                            name <code>beneficiaryKey</code>.
   **                            Possible object is {@link Long}.
   */
  public Long getBeneficiaryKey() {
    return (Long)getAttributeInternal(BENEFICIARYKEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setBeneficiaryLogin
  /**
   ** Sets the attribute value for <code>BENEFICIARYLOGIN</code> using the alias
   ** name <code>beneficiaryLogin</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>BENEFICIARYLOGIN</code> using the alias
   **                            name <code>beneficiaryLogin</code>.
   **                            Allowed object is {@link String}.
   */
  public void setBeneficiaryLogin(final String value) {
    setAttributeInternal(BENEFICIARYLOGIN, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getBeneficiaryLogin
  /**
   ** Returns the attribute value for <code>BENEFICIARYLOGIN</code> using the
   ** alias name <code>beneficiaryLogin</code>.
   **
   ** @return                    the attribute value for
   **                            <code>BENEFICIARYLOGIN</code> using the alias
   **                            name <code>beneficiaryLogin</code>.
   **                            Possible object is {@link String}.
   */
  public String getBeneficiaryLogin() {
    return (String)getAttributeInternal(BENEFICIARYLOGIN);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setBeneficiaryFirstName
  /**
   ** Sets the attribute value for <code>BENEFICIARYFIRSTNAME</code> using the
   ** alias name <code>beneficiaryFirstName</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>BENEFICIARYFIRSTNAME</code> using the
   **                            alias name <code>beneficiaryFirstName</code>.
   **                            Allowed object is {@link String}.
   */
  public void setBeneficiaryFirstName(final String value) {
    setAttributeInternal(BENEFICIARYFIRSTNAME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getBeneficiaryFirstName
  /**
   ** Returns the attribute value for <code>BENEFICIARYFIRSTNAME</code> using
   ** the alias name <code>beneficiaryFirstName</code>.
   **
   ** @return                    the attribute value for
   **                            <code>BENEFICIARYFIRSTNAME</code> using the
   **                            alias name <code>beneficiaryFirstName</code>.
   **                            Possible object is {@link String}.
   */
  public String getBeneficiaryFirstName() {
    return (String)getAttributeInternal(BENEFICIARYFIRSTNAME);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setBeneficiaryLastName
  /**
   ** Sets the attribute value for <code>BENEFICIARYLASTNAME</code> using the
   ** alias name <code>beneficiaryLastName</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>BENEFICIARYLASTNAME</code> using the
   **                            alias name <code>beneficiaryLastName</code>.
   **                            Allowed object is {@link String}.
   */
  public void setBeneficiaryLastName(final String value) {
    setAttributeInternal(BENEFICIARYLASTNAME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getBeneficiaryLastName
  /**
   ** Returns the attribute value for <code>BENEFICIARYLASTNAME</code> using the
   ** alias name <code>beneficiaryLastName</code>.
   **
   ** @return                    the attribute value for
   **                            <code>BENEFICIARYLASTNAME</code> using the
   **                            alias name <code>beneficiaryLastName</code>.
   **                            Possible object is {@link String}.
   */
  public String getBeneficiaryLastName() {
    return (String)getAttributeInternal(BENEFICIARYLASTNAME);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setOrganizationKey
  /**
   ** Sets the attribute value for <code>ORGANIZATIONKEY</code> using the alias
   ** name <code>organizationKey</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>ORGANIZATIONKEY</code> using the alias
   **                            name <code>organizationKey</code>.
   **                            Allowed object is {@link Long}.
   */
  public void setOrganizationKey(final Long value) {
    setAttributeInternal(ORGANIZATIONKEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getOrganizationKey
  /**
   ** Returns the attribute value for <code>ORGANIZATIONKEY</code> using the
   ** alias name <code>organizationKey</code>.
   **
   ** @return                    the attribute value for
   **                            <code>ORGANIZATIONKEY</code> using the alias
   **                            name <code>organizationKey</code>.
   **                            Possible object is {@link Long}.
   */
  public Long getOrganizationKey() {
    return (Long)getAttributeInternal(ORGANIZATIONKEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setOrganizationName
  /**
   ** Sets the attribute value for <code>ORGANIZATIONNAME</code> using the alias
   ** name <code>organizationName</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>ORGANIZATIONNAME</code> using the alias
   **                            name <code>organizationName</code>.
   **                            Allowed object is {@link String}.
   */
  public void setOrganizationName(final String value) {
    setAttributeInternal(ORGANIZATIONNAME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getOrganizationName
  /**
   ** Returns the attribute value for <code>ORGANIZATIONNAME</code> using the
   ** alias name <code>organizationName</code>.
   **
   ** @return                    the attribute value for
   **                            <code>ORGANIZATIONNAME</code> using the alias
   **                            name <code>organizationName</code>.
   **                            Possible object is {@link String}.
   */
  public String getOrganizationName() {
    return (String)getAttributeInternal(ORGANIZATIONNAME);
  }
}