/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Provisioning Management

    File        :   EndpointTypeVORowImpl.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    EndpointTypeVORowImpl.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysprov.model.view;

import oracle.jbo.RowIterator;

import oracle.jbo.domain.ClobDomain;

import oracle.jbo.server.ViewRowImpl;

import oracle.iam.identity.sysprov.model.entity.EndpointTypeEOImpl;

////////////////////////////////////////////////////////////////////////////////
// class EndpointTypeVORowImpl
// ~~~~~ ~~~~~~~~~~~~~~~~~~~~~
/**
 ** ---------------------------------------------------------------------
 ** --- File generated by Oracle ADF Business Components Design Time.
 ** --- Tue Mar 07 07:51:54 CET 2017
 ** --- Custom code may be added to this class.
 ** --- Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public class EndpointTypeVORowImpl extends ViewRowImpl {

  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  public static final int KEY       = AttributesEnum.endpointTypeKey.ordinal();
  public static final int NAME      = AttributesEnum.endpointTypeName.ordinal();
  public static final int MULTIPLE  = AttributesEnum.multiple.ordinal();
  public static final int NOTE      = AttributesEnum.note.ordinal();
  public static final int ENDPOINT  = AttributesEnum.endpointVO.ordinal();
  public static final int PARAMETER = AttributesEnum.parameterVO.ordinal();

  //////////////////////////////////////////////////////////////////////////////
  // Member classes
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // class AttributesEnum
  /**
   ** AttributesEnum: generated enum for identifying attributes and accessors.
   ** Do not modify.
   */
  private static enum AttributesEnum {
      endpointTypeKey
    , endpointTypeName
    , multiple
    , note
    , endpointVO
    , parameterVO
    ;
  };

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>EndpointTypeVORowImpl</code> view object that allows
   ** use as a JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public EndpointTypeVORowImpl() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Accessor and Mutator methods
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEndpointTypeEO
  /**
   ** Returns the Endpoint Type entity object.
   **
   ** @return                    the EndpointTypeEO
   */
  public EndpointTypeEOImpl getEndpointTypeEO() {
    return (EndpointTypeEOImpl)getEntity(0);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setEndpointTypeKey
  /**
   ** Sets the attribute value for <code>KEY</code> using the alias name
   ** <code>endpointTypeKey</code>.
   **
   ** @param  value              the attribute value for <code>KEY</code> using
   **                            the alias name <code>endpointTypeKey</code>.
   **                            Allowed object is {@link Long}.
   */
  public void setEndpointTypeKey(final Long value) {
    setAttributeInternal(KEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEndpointTypeKey
  /**
   ** Returns the attribute value for <code>KEY</code> using the alias name
   ** <code>endpointTypeKey</code>.
   **
   ** @return                    the attribute value for <code>KEY</code> using
   **                            the alias name <code>endpointTypeKey</code>.
   **                            Possible object is {@link Long}.
   */
  public Long getEndpointTypeKey() {
    return (Long)getAttributeInternal(KEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setEndpointTypeName
  /**
   ** Sets the attribute value for <code>NAME</code> using the alias name
   ** <code>endpointTypeName</code>.
   **
   ** @param  value              the attribute value for <code>NAME</code> using
   **                            the alias name <code>endpointTypeName</code>.
   **                            Allowed object is {@link String}.
   */
  public void setEndpointTypeName(final String value) {
    setAttributeInternal(NAME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEndpointTypeName
  /**
   ** Returns the attribute value for <code>NAME</code> using the alias name
   ** <code>endpointTypeName</code>.
   **
   ** @return                    the attribute value for <code>NAME</code> using
   **                            the alias name <code>endpointTypeName</code>.
   **                            Possible object is {@link String}.
   */
  public String getEndpointTypeName() {
    return (String)getAttributeInternal(NAME);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setMultiple
  /**
   ** Sets the attribute value for <code>MULTIPLE</code> using the alias name
   ** <code>multiple</code>.
   **
   ** @param  value              the attribute value for <code>MULTIPLE</code>
   **                            using the alias name <code>multiple</code>.
   **                            Allowed object is {@link Boolean}.
   */
  public void setMultiple(final Boolean value) {
    setAttributeInternal(MULTIPLE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getMultiple
  /**
   ** Returns the attribute value for <code>MULTIPLE</code> using the alias name
   ** <code>multiple</code>.
   **
   ** @return                    the attribute value for <code>MULTIPLE</code>
   **                            using the alias name <code>multiple</code>.
   **                            Possible object is {@link Boolean}.
   */
  public Boolean getMultiple() {
    return (Boolean)getAttributeInternal(MULTIPLE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setNote
  /**
   ** Sets the attribute value for <code>NOTE</code> using the alias name
   ** <code>note</code>.
   **
   ** @param  value              the attribute value for <code>NOTE</code> using
   **                            the alias name <code>note</code>.
   **                            Allowed object is {@link ClobDomain}.
   */
  public void setNote(final ClobDomain value) {
    setAttributeInternal(NOTE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getNote
  /**
   ** Returns the attribute value for <code>NOTE</code> using the alias name
   ** <code>note</code>.
   **
   ** @return                    the attribute value for <code>NOTE</code> using
   **                            the alias name <code>note</code>.
   **                            Possible object is {@link ClobDomain}.
   */
  public ClobDomain getNote() {
    return (ClobDomain)getAttributeInternal(NOTE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEndpointVO
  /**
   ** Returns the attribute value for <code>ENDPOINT</code> using the alias name
   ** <code>endpointVO</code>.
   **
   ** @return                    the attribute value for <code>ENDPOINT</code>
   **                            using the alias name <code>endpointVO</code>.
   **                            Possible object is {@link RowIterator}.
   */
  public RowIterator getEndpointVO() {
    return (RowIterator)getAttributeInternal(ENDPOINT);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getParameterVO
  /**
   ** Returns the attribute value for <code>PARAMETER</code> using the alias
   ** name <code>parameterVO</code>.
   **
   ** @return                    the attribute value for <code>PARAMETER</code>
   **                            using the alias name <code>parameterVO</code>.
   **                            Possible object is {@link RowIterator}.
   */
  public RowIterator getParameterVO() {
    return (RowIterator)getAttributeInternal(PARAMETER);
  }
}