/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Provisioning Management

    File        :   EndpointVORowImpl.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    EndpointVORowImpl.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysprov.model.view;

import oracle.jbo.RowIterator;

import oracle.jbo.domain.ClobDomain;

import oracle.jbo.server.ViewRowImpl;

import oracle.iam.identity.sysprov.model.entity.EndpointEOImpl;

////////////////////////////////////////////////////////////////////////////////
// class EndpointVORowImpl
// ~~~~~ ~~~~~~~~~~~~~~~~~
/**
 ** ---------------------------------------------------------------------
 ** --- File generated by Oracle ADF Business Components Design Time.
 ** --- Tue Mar 07 07:51:54 CET 2017
 ** --- Custom code may be added to this class.
 ** --- Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public class EndpointVORowImpl extends ViewRowImpl {

  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  public static final int KEY           = AttributesEnum.endpointKey.ordinal();
  public static final int NAME          = AttributesEnum.endpointName.ordinal();
  public static final int TYPE          = AttributesEnum.endpointType.ordinal();
  public static final int REMOTE        = AttributesEnum.remoteManager.ordinal();
  public static final int NOTE          = AttributesEnum.note.ordinal();
  public static final int PARAMETER     = AttributesEnum.parameterVO.ordinal();
  public static final int ADMINISTRATOR = AttributesEnum.administratorVO.ordinal();

  //////////////////////////////////////////////////////////////////////////////
  // Member classes
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // class AttributesEnum
  /**
   ** AttributesEnum: generated enum for identifying attributes and accessors.
   ** Do not modify.
   */
  private static enum AttributesEnum {
      endpointKey
    , endpointName
    , endpointType
    , remoteManager
    , note
    , parameterVO
    , administratorVO
    ;
  };

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>EndpointVORowImpl</code> view object that allows use as
   ** a JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public EndpointVORowImpl() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Accessor and Mutator methods
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEndpointEO
  /**
   ** Returns the Endpoint entity object.
   **
   ** @return                    the EndpointEO
   */
  public EndpointEOImpl getEndpointEO() {
    return (EndpointEOImpl)getEntity(0);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setEndpointKey
  /**
   ** Sets the attribute value for <code>KEY</code> using the alias name
   ** <code>endpointKey</code>.
   **
   ** @param  value              the attribute value for <code>KEY</code> using
   **                            the alias name <code>endpointKey</code>.
   **                            Allowed object is {@link Long}.
   */
  public void setEndpointKey(final Long value) {
    setAttributeInternal(KEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEndpointKey
  /**
   ** Returns the attribute value for <code>KEY</code> using the alias name
   ** <code>endpointKey</code>.
   **
   ** @return                    the attribute value for <code>KEY</code> using
   **                            the alias name <code>endpointKey</code>.
   **                            Possible object is {@link Long}.
   */
  public Long getEndpointKey() {
    return (Long)getAttributeInternal(KEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setEndpointName
  /**
   ** Sets the attribute value for <code>NAME</code> using the alias name
   ** <code>endpointName</code>.
   **
   ** @param  value              the attribute value for <code>NAME</code> using
   **                            the alias name <code>endpointName</code>.
   **                            Allowed object is {@link String}.
   */
  public void setEndpointName(final String value) {
    setAttributeInternal(NAME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEndpointName
  /**
   ** Returns the attribute value for <code>NAME</code> using the alias name
   ** <code>endpointName</code>.
   **
   ** @return                    the attribute value for <code>NAME</code> using
   **                            the alias name <code>endpointName</code>.
   **                            Possible object is {@link String}.
   */
  public String getEndpointName() {
    return (String)getAttributeInternal(NAME);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setEndpointType
  /**
   ** Sets the attribute value for <code>TYPE</code> using the alias name
   ** <code>endpointType</code>.
   **
   ** @param  value              the attribute value for <code>TYPE</code> using
   **                            the alias name <code>endpointType</code>.
   **                            Allowed object is {@link String}.
   */
  public void setEndpointType(final String value) {
    setAttributeInternal(TYPE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEndpointType
  /**
   ** Returns the attribute value for <code>TYPE</code> using the alias name
   ** <code>endpointType</code>.
   **
   ** @return                    the attribute value for <code>TYPE</code> using
   **                            the alias name <code>endpointType</code>.
   **                            Possible object is {@link String}.
   */
  public String getEndpointTyp() {
    return (String)getAttributeInternal(KEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setRemoteManager
  /**
   ** Sets the attribute value for <code>REMOTE</code> using the alias name
   ** <code>remoteManager</code>.
   **
   ** @param  value              the attribute value for <code>REMOTE</code>
   **                            using the alias name
   **                            <code>remoteManager</code>.
   **                            Allowed object is {@link String}.
   */
  public void setRemoteManager(final String value) {
    setAttributeInternal(REMOTE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getRemoteManagerKey
  /**
   ** Returns the attribute value for <code>REMOTE</code> using the alias name
   ** <code>remoteManager</code>.
   **
   ** @return                    the attribute value for <code>REMOTE</code>
   **                            using the alias name
   **                            <code>remoteManager</code>.
   **                            Possible object is {@link String}.
   */
  public String getRemoteManagerKey() {
    return (String)getAttributeInternal(REMOTE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setNote
  /**
   ** Sets the attribute value for <code>NOTE</code> using the alias name
   ** <code>note</code>.
   **
   ** @param  value              the attribute value for <code>NOTE</code> using
   **                            the alias name <code>note</code>.
   **                            Allowed object is {@link ClobDomain}.
   */
  public void setNote(final ClobDomain value) {
    setAttributeInternal(NOTE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getNote
  /**
   ** Returns the attribute value for <code>NOTE</code> using the alias name
   ** <code>note</code>.
   **
   ** @return                    the attribute value for <code>NOTE</code> using
   **                            the alias name <code>note</code>.
   **                            Possible object is {@link ClobDomain}.
   */
  public ClobDomain getNote() {
    return (ClobDomain)getAttributeInternal(NOTE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getParameterVO
  /**
   ** Returns the attribute value for <code>PARAMETER</code> using the alias
   ** name <code>parameterVO</code>.
   **
   ** @return                    the attribute value for <code>PARAMETER</code>
   **                            using the alias name <code>parameterVO</code>.
   **                            Possible object is {@link RowIterator}.
   */
  public RowIterator getParameterVO() {
    return (RowIterator)getAttributeInternal(PARAMETER);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getAdministratorVO
  /**
   ** Returns the attribute value for <code>ADMINISTRATOR</code> using the alias
   ** name <code>administratorVO</code>.
   **
   ** @return                    the attribute value for
   **                            <code>ADMINISTRATOR</code> using the alias name
   **                            <code>administratorVO</code>.
   **                            Possible object is {@link RowIterator}.
   */
  public RowIterator getAdministratorVO() {
    return (RowIterator)getAttributeInternal(ADMINISTRATOR);
  }
}