/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Provisioning Management

    File        :   EndpointParameterVORowImpl.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    EndpointParameterVORowImpl.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysprov.model.view;

import oracle.jbo.server.ViewRowImpl;

import oracle.iam.identity.sysprov.model.entity.EndpointParameterEOImpl;

////////////////////////////////////////////////////////////////////////////////
// class EndpointParameterVORowImpl
// ~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~
/**
 ** ---------------------------------------------------------------------
 ** --- File generated by Oracle ADF Business Components Design Time.
 ** --- Tue Mar 07 07:51:54 CET 2017
 ** --- Custom code may be added to this class.
 ** --- Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public class EndpointParameterVORowImpl extends ViewRowImpl {

  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  public static final int ENTITY    = 0;
  public static final int KEY       = AttributesEnum.parameterKey.ordinal();
  public static final int ENDPOINT  = AttributesEnum.endpointKey.ordinal();
  public static final int NAME      = AttributesEnum.name.ordinal();
  public static final int VALUE     = AttributesEnum.value.ordinal();
  public static final int ENCRYPTED = AttributesEnum.encrypted.ordinal();
  public static final int ACTION    = AttributesEnum.pendingAction.ordinal();
  public static final int MOD       = AttributesEnum.mod.ordinal();

  //////////////////////////////////////////////////////////////////////////////
  // Member classes
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // class AttributesEnum
  /**
   ** AttributesEnum: generated enum for identifying attributes and accessors.
   ** Do not modify.
   */
  private static enum AttributesEnum {
      parameterKey
    , endpointKey
    , name
    , value
    , encrypted
    , pendingAction
    , mod
    ;
  };

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>EndpointParameterVORowImpl</code> view object that
   ** allows use as a JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public EndpointParameterVORowImpl() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Accessor and Mutator methods
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEndpointParameterEO
  /**
   ** Returns the entity object implementation.
   **
   ** @return                    the implementation of EndpointParameterEO.
   **                            <br>
   **                            Possible object is
   **                            {@link EndpointParameterEOImpl}.
   */
  public EndpointParameterEOImpl getEndpointParameterEO() {
    return (EndpointParameterEOImpl)getEntity(ENTITY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setParameterKey
  /**
   ** Sets the attribute value for <code>KEY</code> using the alias name
   ** <code>parameterKey</code>.
   **
   ** @param  value              the attribute value for <code>KEY</code> using
   **                            the alias name <code>parameterKey</code>.
   **                            <br>
   **                            Allowed object is {@link Long}.
   */
  public void setParameterKey(final Long value) {
    setAttributeInternal(KEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getParameterKey
  /**
   ** Returns the attribute value for <code>KEY</code> using the alias name
   ** <code>parameterKey</code>.
   **
   ** @return                    the attribute value for <code>KEY</code> using
   **                            the alias name <code>parameterKey</code>.
   **                            <br>
   **                            Possible object is {@link Long}.
   */
  public Long getParameterKey() {
    return (Long)getAttributeInternal(KEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setEndpointKey
  /**
   ** Sets the attribute value for <code>ENDPOINT</code> using the alias name
   ** <code>endpointKey</code>.
   **
   ** @param  value              the attribute value for <code>ENDPOINT</code>
   **                            using the alias name <code>endpointKey</code>.
   **                            <br>
   **                            Allowed object is {@link Long}.
   */
  public void setEndpointKey(final Long value) {
    setAttributeInternal(ENDPOINT, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEndpointKey
  /**
   ** Returns the attribute value for <code>ENDPOINT</code> using the alias name
   ** <code>endpointKey</code>.
   **
   ** @return                    the attribute value for <code>ENDPOINT</code>
   **                            using the alias name <code>endpointKey</code>.
   **                            <br>
   **                            Possible object is {@link Long}.
   */
  public Long getEndpointKey() {
    return (Long)getAttributeInternal(ENDPOINT);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setName
  /**
   ** Sets the attribute value for <code>NAME</code> using the alias name
   ** <code>name</code>.
   **
   ** @param  value              the attribute value for <code>NAME</code> using
   **                            the alias name <code>name</code>.
   **                            <br>
   **                            Allowed object is {@link String}.
   */
  public void setName(final String value) {
    setAttributeInternal(NAME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getName
  /**
   ** Returns the attribute value for <code>NAME</code> using the alias name
   ** <code>name</code>.
   **
   ** @return                    the attribute value for <code>NAME</code> using
   **                            the alias name <code>name</code>.
   **                            <br>
   **                            Possible object is {@link String}.
   */
  public String getName() {
    return (String)getAttributeInternal(NAME);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setValue
  /**
   ** Sets the attribute value for <code>VALUE</code> using the alias name
   ** <code>value</code>.
   **
   ** @param  value              the attribute value for <code>VALUE</code>
   **                            using the alias name <code>value</code>.
   **                            <br>
   **                            Allowed object is {@link String}.
   */
  public void setValue(final String value) {
    setAttributeInternal(VALUE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getValue
  /**
   ** Returns the attribute value for <code>VALUE</code> using the alias name
   ** <code>name</code>.
   **
   ** @return                    the attribute value for <code>VALUE</code>
   **                            using the alias name <code>value</code>.
   **                            <br>
   **                            Possible object is {@link String}.
   */
  public String getValue() {
    return (String)getAttributeInternal(VALUE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setEncrypted
  /**
   ** Sets the attribute value for <code>ENCRYPTED</code> using the alias name
   ** <code>encrypted</code>.
   **
   ** @param  value              the attribute value for <code>ENCRYPTED</code>
   **                            using the alias name
   **                            <code>encrypted</code>.
   **                            <br>
   **                            Allowed object is {@link Boolean}.
   */
  public void setEncrypted(final Boolean value) {
    setAttributeInternal(ENCRYPTED, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEncrypted
  /**
   ** Returns the attribute value for <code>ENCRYPTED</code> using the alias name
   ** <code>encrypted</code>.
   **
   ** @return                    the attribute value for <code>ENCRYPTED</code>
   **                            using the alias name
   **                            <code>encrypted</code>.
   **                            <br>
   **                            Possible object is {@link Boolean}.
   */
  public Boolean getEncrypted() {
    return (Boolean)getAttributeInternal(ENCRYPTED);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setPendingAction
  /**
   ** Sets the attribute value for the calculated attribute
   ** <code>ACTION</code> using the alias name <code>pendingAction</code>.
   **
   ** @param  value              the attribute value for the calculated
   **                            attribute <code>ACTION</code> using the alias
   **                            name <code>pendingAction</code>.
   **                            <br>
   **                            Allowed object is {@link String}.
   */
  public void setPendingAction(final String value) {
    setAttributeInternal(ACTION, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getPendingAction
  /**
   ** Returns the attribute value for the calculated attribute
   ** <code>ACTION</code> using the alias name <code>pendingAction</code>.
   **
   ** @return                    the attribute value for the calculated
   **                            attribute <code>ACTION</code> using the alias
   **                            name <code>pendingAction</code>.
   **                            <br>
   **                            Possible object is {@link String}.
   */
  public String getPendingAction() {
    return (String)getAttributeInternal(ACTION);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setMod
  /**
   ** Sets the attribute value for the calculated attribute <code>MOD</code>
   ** using the alias name <code>mod</code>.
   **
   ** @param  value              the attribute value for the calculated
   **                            attribute <code>MOD</code> using the alias name
   **                            <code>mod</code>.
   **                            <br>
   **                            Allowed object is {@link String}.
   */
  public void setMod(final String value) {
    setAttributeInternal(MOD, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getMod
  /**
   ** Returns the attribute value for the calculated attribute <code>MOD</code>
   ** using the alias name <code>mod</code>.
   **
   ** @return                    the attribute value for the calculated
   **                            attribute <code>MOD</code> using the alias name
   **                            <code>mod</code>.
   **                            <br>
   **                            Possible object is {@link String}.
   */
  public String getMod() {
    return (String)getAttributeInternal(MOD);
  }
}