/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Provisioning Management

    File        :   ReconciliationEventVORowImpl.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    ReconciliationEventVORowImpl.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysprov.model.view;

import oracle.jbo.server.ViewRowImpl;

import oracle.iam.identity.sysprov.model.entity.ReconciliationEventEOImpl;

////////////////////////////////////////////////////////////////////////////////
// class ReconciliationEventVORowImpl
// ~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/**
 ** ---------------------------------------------------------------------
 ** --- File generated by Oracle ADF Business Components Design Time.
 ** --- Tue Mar 07 07:51:54 CET 2017
 ** --- Custom code may be added to this class.
 ** --- Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public class ReconciliationEventVORowImpl extends ViewRowImpl {

  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  public static final int EVENT_KEY       = AttributesEnum.eventKey.ordinal();
  public static final int JOB_KEY         = AttributesEnum.jobKey.ordinal();
  public static final int BATCH_KEY       = AttributesEnum.batchKey.ordinal();
  public static final int OBJ_KEY         = AttributesEnum.objectKey.ordinal();
  public static final int OBJ_NAME        = AttributesEnum.objectName.ordinal();
  public static final int USR_KEY         = AttributesEnum.userKey.ordinal();
  public static final int ORG_KEY         = AttributesEnum.organizationKey.ordinal();
  public static final int ACT_KEY         = AttributesEnum.accountKey.ordinal();
  public static final int ENTITY_TYPE     = AttributesEnum.entityType.ordinal();
  public static final int CHANGE_TYPE     = AttributesEnum.changeType.ordinal();
  public static final int STATUS          = AttributesEnum.status.ordinal();
  public static final int LINK_SOURCE     = AttributesEnum.linkSource.ordinal();
  public static final int NOTE            = AttributesEnum.note.ordinal();
  public static final int REASON          = AttributesEnum.reason.ordinal();
  public static final int ACTION_DATE     = AttributesEnum.actionDate.ordinal();
  public static final int KEY_FIELD       = AttributesEnum.keyField.ordinal();
  public static final int STATUS_LOV      = AttributesEnum.statusLV.ordinal();
  public static final int ENTITY_TYPE_LOV = AttributesEnum.entityTypeLV.ordinal();
  public static final int CHANGE_TYPE_LOV = AttributesEnum.changeTypeLV.ordinal();

  //////////////////////////////////////////////////////////////////////////////
  // Member classes
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // class AttributesEnum
  /**
   ** AttributesEnum: generated enum for identifying attributes and accessors.
   ** Do not modify.
   */
  private static enum AttributesEnum {
      eventKey
    , jobKey
    , batchKey
    , objectKey
    , objectName
    , userKey
    , organizationKey
    , accountKey
    , entityType
    , changeType
    , status
    , linkSource
    , note
    , reason
    , actionDate
    , keyField
    , statusLV
    , entityTypeLV
    , changeTypeLV
    ;
  };

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>ReconciliationEventVORowImpl</code> view object that allows use as
   ** a JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public ReconciliationEventVORowImpl() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Accessor and Mutator methods
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getReconciliationEventEO
  /**
   ** Returns the Reconciliation Event entity object.
   **
   ** @return                    the ReconciliationEventEO
   */
  public ReconciliationEventEOImpl getReconciliationEventEO() {
    return (ReconciliationEventEOImpl)getEntity(0);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setEventKey
  /**
   ** Sets the attribute value for <code>EVENT_KEY</code> using the alias name
   ** <code>eventKey</code>.
   **
   ** @param  value              the attribute value for <code>EVENT_KEY</code>
   **                            using the alias name <code>eventKey</code>.
   **                            Allowed object is {@link Long}.
   */
  public void setEventKey(final Long value) {
    setAttributeInternal(EVENT_KEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEventKey
  /**
   ** Returns the attribute value for <code>EVENT_KEY</code> using the alias
   ** name <code>eventKey</code>.
   **
   ** @return                    the attribute value for <code>EVENT_KEY</code>
   **                            using the alias name <code>eventKey</code>.
   **                            Possible object is {@link Long}.
   */
  public Long getEventKey() {
    return (Long)getAttributeInternal(EVENT_KEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setJobKey
  /**
   ** Sets the attribute value for <code>JOB_KEY</code> using the alias name
   ** <code>jobKey</code>.
   **
   ** @param  value              the attribute value for <code>JOB_KEY</code>
   **                            using the alias name <code>jobKey</code>.
   **                            Allowed object is {@link Long}.
   */
  public void setJobKey(final Long value) {
    setAttributeInternal(JOB_KEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getJobKey
  /**
   ** Returns the attribute value for <code>JOB_KEY</code> using the alias name
   ** <code>jobKey</code>.
   **
   ** @return                    the attribute value for <code>JOB_KEY</code>
   **                            using the alias name <code>jobKey</code>.
   **                            Possible object is {@link Long}.
   */
  public Long getJobKey() {
    return (Long)getAttributeInternal(JOB_KEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setBatchKey
  /**
   ** Sets the attribute value for <code>BATCH_KEY</code> using the alias name
   ** <code>batchKey</code>.
   **
   ** @param  value              the attribute value for <code>BATCH_KEY</code>
   **                            using the alias name <code>batchKey</code>.
   **                            Allowed object is {@link Long}.
   */
  public void setBatchKey(final Long value) {
    setAttributeInternal(BATCH_KEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getBatchKey
  /**
   ** Returns the attribute value for <code>BATCH_KEY</code> using the alias name
   ** <code>batchKey</code>.
   **
   ** @return                    the attribute value for <code>BATCH_KEY</code>
   **                            using the alias name <code>batchKey</code>.
   **                            Possible object is {@link Long}.
   */
  public Long getBatchKey() {
    return (Long)getAttributeInternal(BATCH_KEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setObjectKey
  /**
   ** Sets the attribute value for <code>OBJ_KEY</code> using the alias name
   ** <code>objectKey</code>.
   **
   ** @param  value              the attribute value for <code>OBJ_KEY</code>
   **                            using the alias name <code>objectKey</code>.
   **                            Allowed object is {@link Long}.
   */
  public void setObjectKey(final Long value) {
    setAttributeInternal(OBJ_KEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getObjectKey
  /**
   ** Returns the attribute value for <code>OBJ_KEY</code> using the alias name
   ** <code>objectKey</code>.
   **
   ** @return                    the attribute value for <code>OBJ_KEY</code>
   **                            using the alias name <code>objectKey</code>.
   **                            Possible object is {@link Long}.
   */
  public Long getObjectKey() {
    return (Long)getAttributeInternal(OBJ_KEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setObjectName
  /**
   ** Sets the attribute value for <code>OBJ_NAME</code> using the alias name
   ** <code>objectName</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>OBJ_NAME</code> using the alias name
   **                            <code>objectName</code>.
   **                            Allowed account is {@link String}.
   */
  public void setObjectName(final String value) {
    setAttributeInternal(OBJ_NAME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getObjectName
  /**
   ** Returns the attribute value for <code>OBJ_NAME</code> using the alias
   ** name <code>objectName</code>.
   **
   ** @return                    the attribute value for
   **                            <code>OBJ_NAME</code> using the alias name
   **                            <code>objectName</code>.
   **                            Possible account is {@link String}.
   */
  public String getObjectName() {
    return (String)getAttributeInternal(OBJ_NAME);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setUserKey
  /**
   ** Sets the attribute value for <code>USR_KEY</code> using the alias name
   ** <code>userKey</code>.
   **
   ** @param  value              the attribute value for <code>USR_KEY</code>
   **                            using the alias name <code>userKey</code>.
   **                            Allowed user is {@link Long}.
   */
  public void setUserKey(final Long value) {
    setAttributeInternal(USR_KEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getUserKey
  /**
   ** Returns the attribute value for <code>USR_KEY</code> using the alias name
   ** <code>userKey</code>.
   **
   ** @return                    the attribute value for <code>USR_KEY</code>
   **                            using the alias name <code>userKey</code>.
   **                            Possible user is {@link Long}.
   */
  public Long getUserKey() {
    return (Long)getAttributeInternal(USR_KEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setOrganizationKey
  /**
   ** Sets the attribute value for <code>ORG_KEY</code> using the alias name
   ** <code>organizationKey</code>.
   **
   ** @param  value              the attribute value for <code>ORG_KEY</code>
   **                            using the alias name
   **                            <code>organizationKey</code>.
   **                            Allowed organization is {@link Long}.
   */
  public void setOrganizationKey(final Long value) {
    setAttributeInternal(ORG_KEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getOrganizationKey
  /**
   ** Returns the attribute value for <code>ORG_KEY</code> using the alias name
   ** <code>organizationKey</code>.
   **
   ** @return                    the attribute value for <code>ORG_KEY</code>
   **                            using the alias name
   **                            <code>organizationKey</code>.
   **                            Possible organization is {@link Long}.
   */
  public Long getOrganizationKey() {
    return (Long)getAttributeInternal(ORG_KEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setAccountKey
  /**
   ** Sets the attribute value for <code>ACT_KEY</code> using the alias name
   ** <code>accountKey</code>.
   **
   ** @param  value              the attribute value for <code>ACT_KEY</code>
   **                            using the alias name <code>accountKey</code>.
   **                            Allowed account is {@link Long}.
   */
  public void setAccountKey(final Long value) {
    setAttributeInternal(ACT_KEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getAccountKey
  /**
   ** Returns the attribute value for <code>ACT_KEY</code> using the alias name
   ** <code>accountKey</code>.
   **
   ** @return                    the attribute value for <code>ACT_KEY</code>
   **                            using the alias name <code>accountKey</code>.
   **                            Possible account is {@link Long}.
   */
  public Long getAccountKey() {
    return (Long)getAttributeInternal(ACT_KEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setEntityType
  /**
   ** Sets the attribute value for <code>ENTITY_TYPE</code> using the alias name
   ** <code>entityType</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>ENTITY_TYPE</code> using the alias name
   **                            <code>entityType</code>.
   **                            Allowed account is {@link String}.
   */
  public void setEntityType(final String value) {
    setAttributeInternal(ENTITY_TYPE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEntityType
  /**
   ** Returns the attribute value for <code>ENTITY_TYPE</code> using the alias
   ** name <code>entityType</code>.
   **
   ** @return                    the attribute value for
   **                            <code>ENTITY_TYPE</code> using the alias name
   **                            <code>entityType</code>.
   **                            Possible account is {@link String}.
   */
  public String getEntityType() {
    return (String)getAttributeInternal(ENTITY_TYPE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setChangeType
  /**
   ** Sets the attribute value for <code>CHANGE_TYPE</code> using the alias name
   ** <code>changeType</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>CHANGE_TYPE</code> using the alias name
   **                            <code>changeType</code>.
   **                            Allowed account is {@link String}.
   */
  public void setChangeType(final String value) {
    setAttributeInternal(CHANGE_TYPE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getChangeType
  /**
   ** Returns the attribute value for <code>CHANGE_TYPE</code> using the alias
   ** name <code>changeType</code>.
   **
   ** @return                    the attribute value for
   **                            <code>CHANGE_TYPE</code> using the alias name
   **                            <code>changeType</code>.
   **                            Possible account is {@link String}.
   */
  public String getChangeType() {
    return (String)getAttributeInternal(CHANGE_TYPE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setStatus
  /**
   ** Sets the attribute value for <code>STATUS</code> using the alias name
   ** <code>status</code>.
   **
   ** @param  value              the attribute value for <code>STATUS</code>
   **                            using the alias name <code>status</code>.
   **                            Allowed account is {@link String}.
   */
  public void setStatus(final String value) {
    setAttributeInternal(STATUS, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getStatus
  /**
   ** Returns the attribute value for <code>STATUS</code> using the alias name
   ** <code>status</code>.
   **
   ** @return                    the attribute value for <code>STATUS</code>
   **                            using the alias name <code>status</code>.
   **                            Possible account is {@link String}.
   */
  public String getStatus() {
    return (String)getAttributeInternal(STATUS);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setLinkSource
  /**
   ** Sets the attribute value for <code>LINK_SOURCE</code> using the alias name
   ** <code>linkSource</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>LINK_SOURCE</code> using the alias name
   **                            <code>linkSource</code>.
   **                            Allowed account is {@link String}.
   */
  public void setLinkSource(final String value) {
    setAttributeInternal(LINK_SOURCE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getLinkSource
  /**
   ** Returns the attribute value for <code>LINK_SOURCE</code> using the alias
   ** name <code>linkSource</code>.
   **
   ** @return                    the attribute value for
   **                            <code>LINK_SOURCE</code> using the alias name
   **                            <code>linkSource</code>.
   **                            Possible account is {@link String}.
   */
  public String getLinkSource() {
    return (String)getAttributeInternal(LINK_SOURCE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setNote
  /**
   ** Sets the attribute value for <code>NOTE</code> using the alias name
   ** <code>note</code>.
   **
   ** @param  value              the attribute value for <code>NOTE</code> using
   **                            the alias name <code>note</code>.
   **                            Allowed object is {@link String}.
   */
  public void setNote(final String value) {
    setAttributeInternal(NOTE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getNote
  /**
   ** Returns the attribute value for <code>NOTE</code> using the alias name
   ** <code>note</code>.
   **
   ** @return                    the attribute value for <code>NOTE</code> using
   **                            the alias name <code>note</code>.
   **                            Possible object is {@link String}.
   */
  public String getNote() {
    return (String)getAttributeInternal(NOTE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setReason
  /**
   ** Sets the attribute value for <code>REASON</code> using the alias name
   ** <code>reason</code>.
   **
   ** @param  value              the attribute value for <code>REASON</code>
   **                            using the alias name <code>reason</code>.
   **                            Allowed account is {@link String}.
   */
  public void setReason(final String value) {
    setAttributeInternal(REASON, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getReason
  /**
   ** Returns the attribute value for <code>REASON</code> using the alias name
   ** <code>reason</code>.
   **
   ** @return                    the attribute value for <code>REASON</code>
   **                            using the alias name <code>reason</code>.
   **                            Possible account is {@link String}.
   */
  public String getReason() {
    return (String)getAttributeInternal(REASON);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setKeyField
  /**
   ** Sets the attribute value for <code>KEY_FIELD</code> using the alias name
   ** <code>keyField</code>.
   **
   ** @param  value              the attribute value for <code>KEY_FIELD</code>
   **                            using the alias name <code>keyField</code>.
   **                            Allowed account is {@link String}.
   */
  public void setKeyField(final String value) {
    setAttributeInternal(KEY_FIELD, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getKeyField
  /**
   ** Returns the attribute value for <code>KEY_FIELD</code> using the alias
   ** name <code>keyField</code>.
   **
   ** @return                    the attribute value for <code>KEY_FIELD</code>
   **                            using the alias name <code>keyField</code>.
   **                            Possible account is {@link String}.
   */
  public String getKeyField() {
    return (String)getAttributeInternal(KEY_FIELD);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setStatusLV
  /**
   ** Sets the attribute value for <code>STATUS_LOV</code> using the alias name
   ** <code>statusLV</code>.
   **
   ** @param  value              the attribute value for <code>STATUS_LOV</code>
   **                            using the alias name <code>changeTypeLV</code>.
   **                            <br>
   **                            Allowed account is {@link String}.
   */
  public void setStatusLV(final String value) {
    setAttributeInternal(STATUS_LOV, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getStatusLV
  /**
   ** Returns the attribute value for <code>STATUS_LOV</code> using the
   ** alias name <code>changeTypeLV</code>.
   **
   ** @return                    the attribute value for <code>STATUS_LOV</code>
   **                            using the alias name <code>changeTypeLV</code>.
   **                            <br>
   **                            Possible account is {@link String}.
   */
  public String getStatusLV() {
    return (String)getAttributeInternal(STATUS_LOV);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setEntityTypeLV
  /**
   ** Sets the attribute value for <code>ENTITY_TYPE_LOV</code> using the alias
   ** name <code>entityTypeLV</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>ENTITY_TYPE_LOV</code> using the alias
   **                            name <code>entityTypeLV</code>.
   **                            <br>
   **                            Allowed account is {@link String}.
   */
  public void setEntityTypeLV(final String value) {
    setAttributeInternal(ENTITY_TYPE_LOV, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEntityTypeLV
  /**
   ** Returns the attribute value for <code>ENTITY_TYPE_LOV</code> using the
   ** alias name <code>entityTypeLV</code>.
   **
   ** @return                    the attribute value for
   **                            <code>ENTITY_TYPE_LOV</code> using the alias
   **                            name <code>entityTypeLV</code>.
   **                            <br>
   **                            Possible account is {@link String}.
   */
  public String getEntityTypeLV() {
    return (String)getAttributeInternal(ENTITY_TYPE_LOV);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setChangeTypeLV
  /**
   ** Sets the attribute value for <code>CHANGE_TYPE_LOV</code> using the alias
   ** name <code>changeTypeLV</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>CHANGE_TYPE_LOV</code> using the alias
   **                            name <code>changeTypeLV</code>.
   **                            <br>
   **                            Allowed account is {@link String}.
   */
  public void setChangeTypeLV(final String value) {
    setAttributeInternal(CHANGE_TYPE_LOV, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getChangeTypeLV
  /**
   ** Returns the attribute value for <code>CHANGE_TYPE_LOV</code> using the
   ** alias name <code>changeTypeLV</code>.
   **
   ** @return                    the attribute value for
   **                            <code>CHANGE_TYPE_LOV</code> using the alias
   **                            name <code>changeTypeLV</code>.
   **                            <br>
   **                            Possible account is {@link String}.
   */
  public String getChangeTypeLV() {
    return (String)getAttributeInternal(CHANGE_TYPE_LOV);
  }
}