/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Provisioning Management

    File        :   ReconciliationProfileVORowImpl.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    ReconciliationProfileVORowImpl.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysprov.model.view;

import oracle.jbo.server.ViewRowImpl;

import oracle.iam.identity.sysprov.model.entity.ReconciliationProfileEOImpl;

////////////////////////////////////////////////////////////////////////////////
// class ReconciliationProfileVORowImpl
// ~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/**
 ** ---------------------------------------------------------------------
 ** --- File generated by Oracle ADF Business Components Design Time.
 ** --- Tue Mar 07 07:51:54 CET 2017
 ** --- Custom code may be added to this class.
 ** --- Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public class ReconciliationProfileVORowImpl extends ViewRowImpl {

  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  public static final int OBJECT    = AttributesEnum.objectsName.ordinal();
  public static final int ATTRIBUTE = AttributesEnum.attribute.ordinal();
  public static final int TYPE      = AttributesEnum.type.ordinal();
  public static final int PRIMARY   = AttributesEnum.primary.ordinal();
  public static final int REQUIRED  = AttributesEnum.required.ordinal();
  public static final int ENCRYPTED = AttributesEnum.encrypted.ordinal();
  public static final int KEYFIELD  = AttributesEnum.keyField.ordinal();

  //////////////////////////////////////////////////////////////////////////////
  // Member classes
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // class AttributesEnum
  /**
   ** AttributesEnum: generated enum for identifying attributes and accessors.
   ** Do not modify.
   */
  private static enum AttributesEnum {
      objectsName
    , attribute
    , type
    , primary
    , required
    , encrypted
    , keyField
    , dataTypeLV
    ;
  };

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>ReconciliationProfileVORowImpl</code> view object that
   ** allows use as a JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public ReconciliationProfileVORowImpl() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Accessor and Mutator methods
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getReconciliationProfileEO
  /**
   ** Returns the Reconciliation Profile entity object.
   **
   ** @return                    the ReconciliationProfileEO
   */
  public ReconciliationProfileEOImpl getReconciliationProfileEO() {
    return (ReconciliationProfileEOImpl)getEntity(0);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setObjectsName
  /**
   ** Sets the attribute value for <code>OBJECT</code> using the alias name
   ** <code>objectsName</code>.
   **
   ** @param  value              the attribute value for <code>OBJECT</code>
   **                            using the alias name <code>objectsName</code>.
   **                            Allowed object is {@link String}.
   */
  public void setObjectsName(final String value) {
    setAttributeInternal(OBJECT, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getObjectsName
  /**
   ** Returns the attribute value for <code>OBJECT</code> using the alias name
   ** <code>objectsName</code>.
   **
   ** @return                    the attribute value for <code>OBJECT</code>
   **                            using the alias name <code>objectsName</code>.
   **                            Possible object is {@link String}.
   */
  public String getObjectsName() {
    return (String)getAttributeInternal(OBJECT);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setAttribute
  /**
   ** Sets the attribute value for <code>ATTRIBUTE</code> using the alias name
   ** <code>attribute</code>.
   **
   ** @param  value              the attribute value for <code>ATTRIBUTE</code>
   **                            using the alias name <code>attribute</code>.
   **                            Allowed object is {@link String}.
   */
  public void setAttribute(final String value) {
    setAttributeInternal(ATTRIBUTE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getAttribute
  /**
   ** Returns the attribute value for <code>ATTRIBUTE</code> using the alias
   ** name <code>attribute</code>.
   **
   ** @return                    the attribute value for <code>ATTRIBUTE</code>
   **                            using the alias name <code>attribute</code>.
   **                            Possible object is {@link String}.
   */
  public String getAttribute() {
    return (String)getAttributeInternal(ATTRIBUTE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setType
  /**
   ** Sets the attribute value for <code>TYPE</code> using the alias name
   ** <code>type</code>.
   **
   ** @param  value              the attribute value for <code>TYPE</code> using
   **                            the alias name <code>type</code>.
   **                            Allowed object is {@link String}.
   */
  public void setType(final String value) {
    setAttributeInternal(TYPE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getType
  /**
   ** Returns the attribute value for <code>TYPE</code> using the alias name
   ** <code>type</code>.
   **
   ** @return                    the attribute value for <code>TYPE</code> using
   **                            the alias name <code>type</code>.
   **                            Possible object is {@link String}.
   */
  public String getType() {
    return (String)getAttributeInternal(TYPE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setPrimary
  /**
   ** Sets the attribute value for <code>PRIMARY</code> using the alias name
   ** <code>primary</code>.
   **
   ** @param  value              the attribute value for <code>PRIMARY</code>
   **                            using the alias name <code>primary</code>.
   **                            Allowed object is {@link Boolean}.
   */
  public void setPrimary(final Boolean value) {
    setAttributeInternal(PRIMARY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getPrimary
  /**
   ** Returns the attribute value for <code>PRIMARY</code> using the alias name
   ** <code>primary</code>.
   **
   ** @return                    the attribute value for <code>PRIMARY</code>
   **                            using the alias name <code>primary</code>.
   **                            Possible object is {@link Boolean}.
   */
  public Boolean getPrimary() {
    return (Boolean)getAttributeInternal(PRIMARY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setRequired
  /**
   ** Sets the attribute value for <code>REQUIRED</code> using the alias name
   ** <code>required</code>.
   **
   ** @param  value              the attribute value for <code>REQUIRED</code>
   **                            using the alias name <code>required</code>.
   **                            Allowed object is {@link Boolean}.
   */
  public void setRequired(final Boolean value) {
    setAttributeInternal(REQUIRED, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getRequired
  /**
   ** Returns the attribute value for <code>REQUIRED</code> using the alias name
   ** <code>required</code>.
   **
   ** @return                    the attribute value for <code>REQUIRED</code>
   **                            using the alias name <code>required</code>.
   **                            Possible object is {@link Boolean}.
   */
  public Boolean getRequired() {
    return (Boolean)getAttributeInternal(REQUIRED);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setEncrypted
  /**
   ** Sets the attribute value for <code>ENCRYPTED</code> using the alias name
   ** <code>encrypted</code>.
   **
   ** @param  value              the attribute value for <code>ENCRYPTED</code>
   **                            using the alias name <code>encrypted</code>.
   **                            Allowed object is {@link Boolean}.
   */
  public void setEncrypted(final Boolean value) {
    setAttributeInternal(ENCRYPTED, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEncrypted
  /**
   ** Returns the attribute value for <code>ENCRYPTED</code> using the alias
   ** name <code>encrypted</code>.
   **
   ** @return                    the attribute value for <code>ENCRYPTED</code>
   **                            using the alias name <code>encrypted</code>.
   **                            Possible object is {@link Boolean}.
   */
  public Boolean getEncrypted() {
    return (Boolean)getAttributeInternal(ENCRYPTED);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setKeyFiled
  /**
   ** Sets the attribute value for <code>KEYFIELD</code> using the alias name
   ** <code>keyField</code>.
   **
   ** @param  value              the attribute value for <code>KEYFIELD</code>
   **                            using the alias name <code>keyField</code>.
   **                            Allowed object is {@link Boolean}.
   */
  public void setKeyFiled(final Boolean value) {
    setAttributeInternal(KEYFIELD, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getKeyFiled
  /**
   ** Returns the attribute value for <code>KEYFIELD</code> using the alias name
   ** <code>keyField</code>.
   **
   ** @return                    the attribute value for <code>KEYFIELD</code>
   **                            using the alias name <code>keyField</code>.
   **                            Possible object is {@link Boolean}.
   */
  public Boolean getKeyFiled() {
    return (Boolean)getAttributeInternal(KEYFIELD);
  }
}