/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Provisioning Management

    File        :   ReconciliationEventHistoryVORowImpl.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    ReconciliationEventHistoryVORowImpl.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysprov.model.view;

import oracle.jbo.server.ViewRowImpl;

import oracle.iam.identity.sysprov.model.entity.ReconciliationEventHistoryEOImpl;

////////////////////////////////////////////////////////////////////////////////
// class ReconciliationEventHistoryVORowImpl
// ~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/**
 ** ---------------------------------------------------------------------
 ** --- File generated by Oracle ADF Business Components Design Time.
 ** --- Tue Mar 07 07:51:54 CET 2017
 ** --- Custom code may be added to this class.
 ** --- Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public class ReconciliationEventHistoryVORowImpl extends ViewRowImpl {

  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  public static final int HISTORY_KEY      = AttributesEnum.historyKey.ordinal();
  public static final int EVENT_KEY        = AttributesEnum.eventKey.ordinal();
  public static final int ACTION_PERFORMED = AttributesEnum.actionPerformed.ordinal();
  public static final int STATUS           = AttributesEnum.status.ordinal();
  public static final int NOTE             = AttributesEnum.note.ordinal();

  //////////////////////////////////////////////////////////////////////////////
  // Member classes
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // class AttributesEnum
  /**
   ** AttributesEnum: generated enum for identifying attributes and accessors.
   ** Do not modify.
   */
  private static enum AttributesEnum {
	  historyKey
    , eventKey
    , actionPerformed
    , status
    , note
    ;
  };

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>ReconciliationEventHistoryVORowImpl</code> view object
   ** that allows use as a JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public ReconciliationEventHistoryVORowImpl() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Accessor and Mutator methods
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getReconciliationEventHistoryEO
  /**
   ** Returns the Reconciliation Event History entity object.
   **
   ** @return                    the ReconciliationEventHistoryEO
   */
  public ReconciliationEventHistoryEOImpl getReconciliationEventHistoryEO() {
    return (ReconciliationEventHistoryEOImpl)getEntity(0);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setHistoryKey
  /**
   ** Sets the attribute value for <code>HISTORY_KEY</code> using the alias name
   ** <code>historyKey</code>.
   **
   ** @param  value              the attribute value for <code>HISTORY_KEY</code>
   **                            using the alias name <code>historyKey</code>.
   **                            Allowed object is {@link Long}.
   */
  public void setHistoryKey(final Long value) {
    setAttributeInternal(HISTORY_KEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getHistoryKey
  /**
   ** Returns the attribute value for <code>HISTORY_KEY</code> using the alias
   ** name <code>historyKey</code>.
   **
   ** @return                    the attribute value for <code>HISTORY_KEY</code>
   **                            using the alias name <code>historyKey</code>.
   **                            Possible object is {@link Long}.
   */
  public Long getHistoryKey() {
    return (Long)getAttributeInternal(HISTORY_KEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setEventKey
  /**
   ** Sets the attribute value for <code>EVENT_KEY</code> using the alias name
   ** <code>eventKey</code>.
   **
   ** @param  value              the attribute value for <code>EVENT_KEY</code>
   **                            using the alias name <code>eventKey</code>.
   **                            Allowed object is {@link Long}.
   */
  public void setEventKey(final Long value) {
    setAttributeInternal(EVENT_KEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEventKey
  /**
   ** Returns the attribute value for <code>EVENT_KEY</code> using the alias
   ** name <code>eventKey</code>.
   **
   ** @return                    the attribute value for <code>EVENT_KEY</code>
   **                            using the alias name <code>eventKey</code>.
   **                            Possible object is {@link Long}.
   */
  public Long getEventKey() {
    return (Long)getAttributeInternal(EVENT_KEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setActionPerformed
  /**
   ** Sets the attribute value for <code>ACTION_PERFORMED</code> using the alias
   ** name <code>actionPerformed</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>ACTION_PERFORMED</code> using the alias
   **                            name <code>actionPerformed</code>.
   **                            <br>
   **                            Allowed account is {@link String}.
   */
  public void setActionPerformed(final String value) {
    setAttributeInternal(ACTION_PERFORMED, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getActionPerformed
  /**
   ** Returns the attribute value for <code>ACTION_PERFORMED</code> using the
   ** alias name <code>actionPerformed</code>.
   **
   ** @return                    the attribute value for
   **                            <code>ACTION_PERFORMED</code> using the alias
   **                            name <code>actionPerformed</code>.
   **                            <br>
   **                            Possible account is {@link String}.
   */
  public String getActionPerformed() {
    return (String)getAttributeInternal(ACTION_PERFORMED);
  }
  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setStatus
  /**
   ** Sets the attribute value for <code>STATUS</code> using the alias name
   ** <code>status</code>.
   **
   ** @param  value              the attribute value for <code>STATUS</code>
   **                            using the alias name <code>status</code>.
   **                            Allowed account is {@link String}.
   */
  public void setStatus(final String value) {
    setAttributeInternal(STATUS, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getStatus
  /**
   ** Returns the attribute value for <code>STATUS</code> using the alias name
   ** <code>status</code>.
   **
   ** @return                    the attribute value for <code>STATUS</code>
   **                            using the alias name <code>status</code>.
   **                            Possible account is {@link String}.
   */
  public String getStatus() {
    return (String)getAttributeInternal(STATUS);
  }
}