/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Provisioning Management

    File        :   ResourceObjectAdministratorVORowImpl.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    ResourceObjectAdministratorVORowImpl.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysprov.model.view;

import oracle.jbo.server.ViewRowImpl;

////////////////////////////////////////////////////////////////////////////////
// class ResourceObjectAdministratorVORowImpl
// ~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/**
 ** ---------------------------------------------------------------------
 ** --- File generated by Oracle ADF Business Components Design Time.
 ** --- Tue Mar 07 07:51:54 CET 2017
 ** --- Custom code may be added to this class.
 ** --- Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public class ResourceObjectAdministratorVORowImpl extends ViewRowImpl {

  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  public static final int ENTITY      = 0;
  public static final int OBJECTKEY   = AttributesEnum.objectKey.ordinal();
  public static final int GROUPKEY    = AttributesEnum.groupKey.ordinal();
  public static final int GROUPNAME   = AttributesEnum.groupName.ordinal();
  public static final int WRITE       = AttributesEnum.writeAccess.ordinal();
  public static final int DELETE      = AttributesEnum.deleteAccess.ordinal();
  public static final int ACTION      = AttributesEnum.pendingAction.ordinal();
  public static final int ADD         = AttributesEnum.add.ordinal();
  public static final int DEL         = AttributesEnum.del.ordinal();
  public static final int MOD         = AttributesEnum.mod.ordinal();

  //////////////////////////////////////////////////////////////////////////////
  // Member classes
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // class AttributesEnum
  /**
   ** AttributesEnum: generated enum for identifying attributes and accessors.
   ** Do not modify.
   */
  private static enum AttributesEnum {
      objectKey
    , groupKey
    , groupName
    , writeAccess
    , deleteAccess
    , pendingAction
    , add
    , del
    , mod
    ;
  };

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>ResourceObjectAdministratorVORowImpl</code> view object
   ** that allows use as a JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public ResourceObjectAdministratorVORowImpl() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Accessor and Mutator methods
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setObjectKey
  /**
   ** Sets the attribute value for <code>OBJECTKEY</code> using the alias name
   ** <code>objectKey</code>.
   **
   ** @param  value              the attribute value for <code>OBJECTKEY</code>
   **                            using the alias name <code>objectKey</code>.
   **                            Allowed object is {@link Long}.
   */
  public void setObjectKey(final Long value) {
    setAttributeInternal(OBJECTKEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getObjectKey
  /**
   ** Returns the attribute value for <code>OBJECTKEY</code> using the alias name
   ** <code>objectKey</code>.
   **
   ** @return                    the attribute value for <code>OBJECTKEY</code>
   **                            using the alias name <code>objectKey</code>.
   **                            Possible object is {@link Long}.
   */
  public Long getObjectsKey() {
    return (Long)getAttributeInternal(OBJECTKEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setGroupKey
  /**
   ** Sets the attribute value for <code>GROUPKEY</code> using the alias name
   ** <code>groupKey</code>.
   **
   ** @param  value              the attribute value for <code>GROUPKEY</code>
   **                            using the alias name <code>groupKey</code>.
   **                            Allowed object is {@link Long}.
   */
  public void setGroupKey(final Long value) {
    setAttributeInternal(GROUPKEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getGroupKey
  /**
   ** Returns the attribute value for <code>GROUPKEY</code> using the alias name
   ** <code>name</code>.
   **
   ** @return                    the attribute value for <code>GROUPKEY</code>
   **                            using the alias name <code>groupKey</code>.
   **                            Possible object is {@link Long}.
   */
  public Long getGroupKey() {
    return (Long)getAttributeInternal(GROUPKEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setGroupName
  /**
   ** Sets the attribute value for <code>GROUPNAME</code> using the alias name
   ** <code>groupName</code>.
   **
   ** @param  value              the attribute value for <code>GROUPNAME</code>
   **                            using the alias name <code>groupName</code>.
   **                            Allowed object is {@link String}.
   */
  public void setGroupName(final String value) {
    setAttributeInternal(GROUPNAME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getGroupName
  /**
   ** Returns the attribute value for <code>GROUPNAME</code> using the alias
   ** name <code>groupName</code>.
   **
   ** @return                    the attribute value for <code>GROUPNAME</code>
   **                            using the alias name <code>groupName</code>.
   **                            Possible object is {@link String}.
   */
  public String getGroupName() {
    return (String)getAttributeInternal(GROUPNAME);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setWriteAccess
  /**
   ** Sets the attribute value for <code>WRITE</code> using the alias name
   ** <code>writeAccess</code>.
   **
   ** @param  value              the attribute value for <code>WRITE</code>
   **                            using the alias name <code>writeAccess</code>.
   **                            Allowed object is {@link Boolean}.
   */
  public void setWriteAccess(final Boolean value) {
    setAttributeInternal(WRITE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getWriteAccess
  /**
   ** Returns the attribute value for <code>WRITE</code> using the alias name
   ** <code>writeAccess</code>.
   **
   ** @return                    the attribute value for <code>WRITE</code>
   **                            using the alias name <code>writeAccess</code>.
   **                            Possible object is {@link Boolean}.
   */
  public Boolean getWriteAccess() {
    return (Boolean)getAttributeInternal(WRITE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setDeleteAccess
  /**
   ** Sets the attribute value for <code>DELETE</code> using the alias name
   ** <code>deleteAccess</code>.
   **
   ** @param  value              the attribute value for <code>DELETE</code>
   **                            using the alias name <code>deleteAccess</code>.
   **                            Allowed object is {@link Boolean}.
   */
  public void setDeleteAccess(final Boolean value) {
    setAttributeInternal(DELETE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getDeleteAccess
  /**
   ** Returns the attribute value for <code>DELETE</code> using the alias name
   ** <code>deleteAccess</code>.
   **
   ** @return                    the attribute value for <code>DELETE</code>
   **                            using the alias name
   **                            <code>deleteAccess</code>.
   **                            Possible object is {@link Boolean}.
   */
  public Boolean getDeleteAccess() {
    return (Boolean)getAttributeInternal(DELETE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setPendingAction
  /**
   ** Sets the attribute value for the calculated attribute
   ** <code>ACTION</code> using the alias name <code>pendingAction</code>.
   **
   ** @param  value              the attribute value for the calculated
   **                            attribute <code>ACTION</code> using the alias
   **                            name <code>pendingAction</code>.
   **                            Allowed object is {@link String}.
   */
  public void setPendingAction(final String value) {
    setAttributeInternal(ACTION, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getPendingAction
  /**
   ** Returns the attribute value for the calculated attribute
   ** <code>ACTION</code> using the alias name <code>pendingAction</code>.
   **
   ** @return                    the attribute value for the calculated
   **                            attribute <code>ACTION</code> using the alias
   **                            name <code>pendingAction</code>.
   **                            Possible object is {@link String}.
   */
  public String getPendingAction() {
    return (String)getAttributeInternal(ACTION);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setAdd
  /**
   ** Sets the attribute value for the calculated attribute <code>ADD</code>
   ** using the alias name <code>add</code>.
   **
   ** @param  value              the attribute value for the calculated
   **                            attribute <code>ADD</code> using the alias name
   **                            <code>add</code>.
   **                            Allowed object is {@link String}.
   */
  public void setAdd(final String value) {
    setAttributeInternal(ADD, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getAdd
  /**
   ** Returns the attribute value for the calculated attribute <code>ADD</code>
   ** using the alias name <code>add</code>.
   **
   ** @return                    the attribute value for the calculated
   **                            attribute <code>ADD</code> using the alias name
   **                            <code>add</code>.
   **                            Possible object is {@link String}.
   */
  public String getAdd() {
    return (String)getAttributeInternal(ADD);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setDel
  /**
   ** Sets the attribute value for the calculated attribute <code>DEL</code>
   ** using the alias name <code>del</code>.
   **
   ** @param  value              the attribute value for the calculated
   **                            attribute <code>DEL</code> using the alias name
   **                            <code>del</code>.
   **                            Allowed object is {@link String}.
   */
  public void setDel(final String value) {
    setAttributeInternal(DEL, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getDel
  /**
   ** Returns the attribute value for the calculated attribute <code>DEL</code>
   ** using the alias name <code>del</code>.
   **
   ** @return                    the attribute value for the calculated
   **                            attribute <code>DEL</code> using the alias name
   **                            <code>del</code>.
   **                            Possible object is {@link String}.
   */
  public String getDel() {
    return (String)getAttributeInternal(DEL);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setMod
  /**
   ** Sets the attribute value for the calculated attribute <code>MOD</code>
   ** using the alias name <code>mod</code>.
   **
   ** @param  value              the attribute value for the calculated
   **                            attribute <code>MOD</code> using the alias name
   **                            <code>mod</code>.
   **                            Allowed object is {@link String}.
   */
  public void setMod(final String value) {
    setAttributeInternal(MOD, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getMod
  /**
   ** Returns the attribute value for the calculated attribute <code>MOD</code>
   ** using the alias name <code>mod</code>.
   **
   ** @return                    the attribute value for the calculated
   **                            attribute <code>MOD</code> using the alias name
   **                            <code>mod</code>.
   **                            Possible object is {@link String}.
   */
  public String getMod() {
    return (String)getAttributeInternal(MOD);
  }
}