/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Provisioning Management

    File        :   ResourceObjectVORowImpl.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    ResourceObjectVORowImpl.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysprov.model.view;

import oracle.jbo.RowIterator;

import oracle.jbo.server.ViewRowImpl;

import oracle.iam.identity.sysprov.model.entity.ResourceObjectEOImpl;

////////////////////////////////////////////////////////////////////////////////
// class ResourceObjectVORowImpl
// ~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~
/**
 ** ---------------------------------------------------------------------
 ** --- File generated by Oracle ADF Business Components Design Time.
 ** --- Tue Mar 07 07:51:54 CET 2017
 ** --- Custom code may be added to this class.
 ** --- Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public class ResourceObjectVORowImpl extends ViewRowImpl {

  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  public static final int KEY            = AttributesEnum.objectsKey.ordinal();
  public static final int NAME           = AttributesEnum.objectsName.ordinal();
  public static final int TYPE           = AttributesEnum.objectsType.ordinal();
  public static final int ORDERFOR       = AttributesEnum.objectsOrderFor.ordinal();
  public static final int ALLOWALL       = AttributesEnum.objectsAllowAll.ordinal();
  public static final int ALLOWMULTIPLE  = AttributesEnum.objectsAllowMultiple.ordinal();
  public static final int NOTE           = AttributesEnum.objectsNote.ordinal();
  public static final int ACCOUNT        = AttributesEnum.accountVO.ordinal();
  public static final int ADMINISTRATOR  = AttributesEnum.administratorVO.ordinal();
  public static final int RECONCILIATION = AttributesEnum.reconciliationVO.ordinal();

  //////////////////////////////////////////////////////////////////////////////
  // Member classes
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // class AttributesEnum
  /**
   ** AttributesEnum: generated enum for identifying attributes and accessors.
   ** Do not modify.
   */
  private static enum AttributesEnum {
      objectsKey
    , objectsName
    , objectsType
    , objectsOrderFor
    , objectsAllowAll
    , objectsAllowMultiple
    , objectsNote
    , accountVO
    , administratorVO
    , reconciliationVO
    ;
  };

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>ResourceObjectVORowImpl</code> view object that
   ** allows use as a JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public ResourceObjectVORowImpl() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Accessor and Mutator methods
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getResourceObjectEO
  /**
   ** Returns the Resource Object entity object.
   **
   ** @return                    the ResourceObjectEO
   **                            <br>
   **                            Possible object is
   **                            {@link ResourceObjectEOImpl}.
   */
  public ResourceObjectEOImpl getResourceObjectEO() {
    return (ResourceObjectEOImpl)getEntity(0);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setObjectsKey
  /**
   ** Sets the attribute value for <code>KEY</code> using the alias name
   ** <code>objectsKey</code>.
   **
   ** @param  value              the attribute value for <code>KEY</code> using
   **                            the alias name <code>objectsKey</code>.
   **                            <br>
   **                            Allowed object is {@link String}.
   */
  public void setObjectsKey(final String value) {
    setAttributeInternal(KEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getObjectsKey
  /**
   ** Returns the attribute value for <code>KEY</code> using the alias name
   ** <code>objectsKey</code>.
   **
   ** @return                    the attribute value for <code>KEY</code> using
   **                            the alias name <code>objectsKey</code>.
   **                            <br>
   **                            Possible object is {@link String}.
   */
  public String getObjectsKey() {
    return (String)getAttributeInternal(KEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setObjectsName
  /**
   ** Sets the attribute value for <code>NAME</code> using the alias name
   ** <code>objectsName</code>.
   **
   ** @param  value              the attribute value for <code>NAME</code> using
   **                            the alias name <code>objectsName</code>.
   **                            <br>
   **                            Allowed object is {@link String}.
   */
  public void setObjectsName(final String value) {
    setAttributeInternal(NAME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getObjectsName
  /**
   ** Returns the attribute value for <code>NAME</code> using the alias name
   ** <code>objectsName</code>.
   **
   ** @return                    the attribute value for <code>NAME</code> using
   **                            the alias name <code>objectsName</code>.
   **                            <br>
   **                            Possible object is {@link String}.
   */
  public String getObjectsName() {
    return (String)getAttributeInternal(NAME);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setObjectsType
  /**
   ** Sets the attribute value for <code>TYPE</code> using the alias name
   ** <code>objectsType</code>.
   **
   ** @param  value              the attribute value for <code>TYPE</code> using
   **                            the alias name <code>objectsType</code>.
   **                            <br>
   **                            Allowed object is {@link String}.
   */
  public void setObjectsType(final String value) {
    setAttributeInternal(TYPE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getObjectsType
  /**
   ** Returns the attribute value for <code>TYPE</code> using the alias name
   ** <code>objectsType</code>.
   **
   ** @return                    the attribute value for <code>TYPE</code> using
   **                            the alias name <code>objectsType</code>.
   **                            <br>
   **                            Possible object is {@link String}.
   */
  public String getObjectsType() {
    return (String)getAttributeInternal(TYPE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setObjectsOrderFor
  /**
   ** Sets the attribute value for <code>ORDERFOR</code> using the alias name
   ** <code>objectsOrderFor</code>.
   **
   ** @param  value              the attribute value for <code>ORDERFOR</code>
   **                            using the alias name
   **                            <code>objectsOrderFor</code>.
   **                            <br>
   **                            Allowed object is {@link String}.
   */
  public void setObjectsOrderFor(final String value) {
    setAttributeInternal(ORDERFOR, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getObjectsOrderFor
  /**
   ** Returns the attribute value for <code>ORDERFOR</code> using the alias name
   ** <code>objectsOrderFor</code>.
   **
   ** @return                     the attribute value for <code>ORDERFOR</code>
   **                            using the alias name
   **                            <code>objectsOrderFor</code>.
   **                            <br>
   **                            Possible object is {@link String}.
   */
  public String getObjectsOrderFor() {
    return (String)getAttributeInternal(ORDERFOR);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setObjectsAllowAll
  /**
   ** Sets the attribute value for <code>ALLOWALL</code> using the alias name
   ** <code>objectsAllowAll</code>.
   **
   ** @param  value              the attribute value for <code>ALLOWALL</code>
   **                            using the alias name
   **                            <code>objectsAllowAll</code>.
   **                            <br>
   **                            Allowed object is {@link String}.
   */
  public void setObjectsAllowAll(final String value) {
    setAttributeInternal(ALLOWALL, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getObjectsAllowAll
  /**
   ** Returns the attribute value for <code>ALLOWALL</code> using the alias name
   ** <code>objectsAllowAll</code>.
   **
   ** @return                    the attribute value for <code>ALLOWALL</code>
   **                            using the alias name
   **                            <code>objectsAllowAll</code>.
   **                            <br>
   **                            Possible object is {@link String}.
   */
  public String getObjectsAllowAll() {
    return (String)getAttributeInternal(ALLOWALL);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setObjectsAllowMultiple
  /**
   ** Sets the attribute value for <code>ALLOWMULTIPLE</code> using the alias
   ** name <code>objectsAllowMultiple</code>.
   **
   ** @param  value              the attribute value for <code>ALLOWALL</code>
   **                            using the alias name
   **                            <code>objectsAllowMultiple</code>.
   **                            <br>
   **                            Allowed object is {@link String}.
   */
  public void setObjectsAllowMultiple(final String value) {
    setAttributeInternal(ALLOWMULTIPLE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getObjectsAllowMultiple
  /**
   ** Returns the attribute value for <code>ALLOWMULTIPLE</code> using the alias
   ** name <code>objectsAllowMultiple</code>.
   **
   ** @return                    the attribute value for <code>ALLOWALL</code>
   **                            using the alias name
   **                            <code>objectsAllowMultiple</code>.
   **                            Possible object is {@link String}.
   */
  public String getObjectsAllowMultiple() {
    return (String)getAttributeInternal(ALLOWMULTIPLE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setObjectsNote
  /**
   ** Sets the attribute value for <code>NOTE</code> using the alias name
   ** <code>objectsNote</code>.
   **
   ** @param  value              the attribute value for <code>NOTE</code> using
   **                            the alias name <code>objectsNote</code>.
   **                            <br>
   **                            Allowed object is {@link String}.
   */
  public void setObjectsNote(final String value) {
    setAttributeInternal(NOTE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getObjectsName
  /**
   ** Returns the attribute value for <code>NOTE</code> using the alias name
   ** <code>objectsNote</code>.
   **
   ** @return                    the attribute value for <code>NOTE</code> using
   **                            the alias name <code>objectsNote</code>.
   **                            <br>
   **                            <br>
   **                            Possible object is {@link String}.
   */
  public String getObjectsNote() {
    return (String)getAttributeInternal(NOTE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getAccountVO
  /**
   ** Returns the attribute value for <code>ACCOUNT</code> using the alias name
   ** <code>accountVO</code>.
   **
   ** @return                    the attribute value for <code>ACCOUNT</code>
   **                            using the alias name <code>accountVO</code>.
   **                            <br>
   **                            Possible object is {@link RowIterator}.
   */
  public RowIterator getAccountVO() {
    return (RowIterator)getAttributeInternal(ACCOUNT);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getAdministratorVO
  /**
   ** Returns the attribute value for <code>ADMINISTRATOR</code> using the alias
   ** name <code>administratorVO</code>.
   **
   ** @return                    the attribute value for
   **                            <code>ADMINISTRATOR</code>
   **                            using the alias name
   **                            <code>administratorVO</code>.
   **                            <br>
   **                            Possible object is {@link RowIterator}.
   */
  public RowIterator getAdministratorVO() {
    return (RowIterator)getAttributeInternal(ADMINISTRATOR);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getReconciliationVO
  /**
   ** Returns the attribute value for <code>RECONCILIATION</code> using the
   ** alias name <code>reconciliationVO</code>.
   **
   ** @return                    the attribute value for
   **                            <code>RECONCILIATION</code> using the alias
   **                            name <code>reconciliationVO</code>.
   **                            <br>
   **                            Possible object is {@link RowIterator}.
   */
  public RowIterator getReconciliationVO() {
    return (RowIterator)getAttributeInternal(RECONCILIATION);
  }
}