/*
    Oracle Deutschland BV & Co. KG

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2024. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Manager Connector Library
    Subsystem   :   Grafana Connector

    File        :   CreateResult.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@icloud.com

    Purpose     :   This file implements the class
                    CreateResult.


    Revisions    Date        Editor      Comment
    ------------+-----------+-----------+-----------------------------------
    1.0.0.0      2024-03-22  DSteding    First release version
*/

package oracle.iam.identity.icf.connector.grafana.response;

import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

////////////////////////////////////////////////////////////////////////////////
// final class CreateResult
// ~~~~~ ~~~~~ ~~~~~~~~~~~~
/**
 ** The REST response representation the Service Provider send back about the
 ** result of a transaction to create a resource.
 **
 ** @author  dieter.steding@icloud.com
 ** @version 1.0.0.0
 ** @since   1.0.0.0
 */
public final class CreateResult {

  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  /**
   ** The JSON element of the internal identifier attribute for users, teams and
   ** organizations generated by the Service Provider.
   */
  public static final String ID           = "id";
  /**
   ** The JSON element of the internal identifier attribute for teams generated
   ** by the Service Provider.
   */
  public static final String TEAM         = "teamId";
  /**
   ** The JSON element of the internal identifier attribute for organizations
   ** generated by the Service Provider.
   */
  public static final String ORGANIZATION = "orgId";
  /**
   ** The JSON element of a genuine message.
   */
  public static final String MESSAGE      = "message";

  //////////////////////////////////////////////////////////////////////////////
  // instance attributes
  //////////////////////////////////////////////////////////////////////////////

  /**
   ** The internal identifier of the <code>User</code> resource generated by the
   ** Service Provider at time of creation.
   */
  private final String id;
  /**
   ** The message of the transaction generated by Service Provider.
   */
  private final String message;

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs an empty <code>CreateResult</code> REST representation that
   ** allows use as a JavaBean.
   **
   ** @param  id                 the internal identifier of the
   **                            <code>CreateResult</code> resource generated by
   **                            the Service Provider at time of creation.
   **                            <br>
   **                            Allowed object is {@link String}.
   ** @param  message            the message generated by the Service Provider.
   **                            <br>
   **                            Allowed object is {@link String}.
   */
  @JsonCreator
  public CreateResult(final @JsonProperty(ID) @JsonAlias({TEAM, ORGANIZATION}) String id, final @JsonProperty(MESSAGE) String message) {
    // ensure inheritance
    super();

    // initialize instance attributes
    this.id      = id;
    this.message = message;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Accessor methods
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   id
  /**
   ** Returns the identifier of the <code>Entity</code>.
   **
   ** @return                    the identifier of the <code>Entity</code>.
   **                            <br>
   **                            Possible object is {@link String}.
   */
  public final String id() {
    return this.id;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   message
  /**
   ** Returns the message of the <code>Result</code>.
   **
   ** @return                    the message of the <code>Result</code>.
   **                            <br>
   **                            Possible object is {@link String}.
   */
  public final String message() {
    return this.message;
  }
}