/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Provisioning Management

    File        :   EndpointAMClient.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    EndpointAMClient.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysprov.module.client;

import java.util.Map;

import oracle.jbo.client.remote.ApplicationModuleImpl;

import oracle.iam.identity.sysprov.module.common.EndpointAM;

////////////////////////////////////////////////////////////////////////////////
// class EndpointAMClient
// ~~~~~ ~~~~~~~~~~~~~~~~
/**
 ** The remote {@link ApplicationModuleImpl} to coordinate certain task
 ** belonging to <code>IT Resource</code>s.
 ** <p>
 ** ---------------------------------------------------------------------
 ** ---    File generated by Oracle ADF Business Components Design Time.
 ** ---    Mon Mar 06 19:50:30 CET 2017
 ** ---    Custom code may be added to this class.
 ** ---    Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 **
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public class EndpointAMClient extends    ApplicationModuleImpl
                              implements EndpointAM {

  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  // the official serial version ID which says cryptically which version we're
  // compatible with
  @SuppressWarnings("compatibility:-5331924571591837062")
  private static final long serialVersionUID = -2533239766244103766L;

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>EndpointAMClient</code> application module that allows
   ** use as a JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public EndpointAMClient() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methods of implemented interfaces
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchByIdentifier (EndpointAM)
  /**
   ** Finds a certain <code>IT Resource</code> by executing a query against the
   ** persistence layer which leverage the primary key of the entity object.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>IT Resource</code> to fetch from
   **                            the persistence layer.
   **                            Allowed object is {@link Long}.
   */
  @Override
  public void fetchByIdentifier(final Long identifier) {
    this.riInvokeExportedMethod(this, "fetchByIdentifier", new String[]{"java.lang.Long"}, new Object[] {identifier});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchByName (EndpointAM)
  /**
   ** Finds a certain <code>IT Resource</code> by executing a query against the
   ** persistence layer which leverage the unique key of the entity object.
   **
   ** @param  name               the unique identifier of the
   **                            <code>IT Resource</code> to fetch from
   **                            the persistence layer.
   **                            Allowed object is {@link String}.
   */
  @Override
  public void fetchByName(final String name) {
    this.riInvokeExportedMethod(this, "fetchByName", new String[]{"java.lang.String"}, new Object[] {name});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   createDetail (EndpointAM)
  /**
   ** Initialize the model to create a new <code>IT Resource</code>.
   */
  @Override
  public void createDetail() {
    this.riInvokeExportedMethod(this, "createDetail", null, null);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchDetail (EndpointAM)
  /**
   ** Initialize the model to create a new <code>IT Resource</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>IT Resource</code> to fetch from the
   **                            persistence layer.
   **                            Allowed object is {@link Long}.
   */
  @Override
  public void fetchDetail(final Long identifier) {
    this.riInvokeExportedMethod(this, "fetchDetail", new String [] {"java.lang.Long"}, new Object[] {identifier});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   refreshAttribute (EndpointAM)
  /**
   ** Refresh the attributes belonging to a certain <code>IT Resource</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>IT Resource</code> to initialize.
   **                            Allowed object is {@link Long}.
   */
  @Override
  public void refreshAttribute(final Long identifier) {
    riInvokeExportedMethod(this, "refreshAttribute", new String [] {"java.lang.Long"}, new Object[] {identifier});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   requeryParameter (EndpointAM)
  /**
   ** Refresh the <code>Parameter</code>s belonging to a certain
   ** <code>IT Resource</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>IT Resource</code> to query.
   **                            Allowed object is {@link Long}.
   ** @param  pending            the collection of pending changes belonging to
   **                            added, deleted and modified values.
   */
  @Override
  public void requeryParameter(final Long identifier, final Map<String, Map<String, Object>> pending) {
    riInvokeExportedMethod(this, "requeryParameter", new String [] {"java.lang.Long", "java.util.Map<String, java.util.Map>"}, new Object[] {identifier, pending});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   requeryAdministrator (EndpointAM)
  /**
   ** Refresh the <code>Administrators</code>s belonging to a certain
   ** <code>IT Resource</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>IT Resource</code> to query.
   **                            Allowed object is {@link Long}.
   ** @param  pending            the collection of pending changes belonging to
   **                            added, deleted and modified values.
   */
  @Override
  public void requeryAdministrator(final Long identifier, final Map<String, Map<String, Object>> pending) {
    riInvokeExportedMethod(this, "requeryAdministrator", new String [] {"java.lang.Long", "java.util.Map<String, java.util.Map>"}, new Object[] {identifier, pending});
  }
}