/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Provisioning Management

    File        :   ResourceObjectAMClient.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    ResourceObjectAMClient.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysprov.module.client;

import oracle.jbo.client.remote.ApplicationModuleImpl;

import oracle.iam.identity.sysprov.module.common.ResourceObjectAM;

////////////////////////////////////////////////////////////////////////////////
// class ResourceObjectAMClient
// ~~~~~ ~~~~~~~~~~~~~~~~~~~~~~
/**
 ** The remote {@link ApplicationModuleImpl} to coordinate certain task
 ** belonging to <code>Resource Object</code>s.
 ** <p>
 ** ---------------------------------------------------------------------
 ** ---    File generated by Oracle ADF Business Components Design Time.
 ** ---    Mon Mar 06 19:50:30 CET 2017
 ** ---    Custom code may be added to this class.
 ** ---    Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 **
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public class ResourceObjectAMClient extends    ApplicationModuleImpl
                                    implements ResourceObjectAM {

  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  // the official serial version ID which says cryptically which version we're
  // compatible with
  @SuppressWarnings("compatibility:-5448938022075565175")
  private static final long serialVersionUID = -7235882150876258806L;

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>ResourceObjectAMClient</code> application module that
   ** allows use as a JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public ResourceObjectAMClient() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methods of implemented interfaces
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchByIdentifier (ResourceObjectAM)
  /**
   ** Finds a certain <code>Resource Object</code> by executing a query against
   ** the persistence layer which leverage the primary key of the entity object.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Resource Object</code> to fetch from
   **                            the persistence layer.
   */
  @Override
  public void fetchByIdentifier(final String identifier) {
    this.riInvokeExportedMethod(this, "fetchByIdentifier", new String[]{"java.lang.String"}, new Object[] {identifier});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchByName (ResourceObjectAM)
  /**
   ** Finds a certain <code>Resource Object</code> by executing a query against
   ** the persistence layer which leverage the unique key of the entity object.
   **
   ** @param  name               the unique identifier of the
   **                            <code>Resource Object</code> to fetch from
   **                            the persistence layer.
   */
  @Override
  public void fetchByName(final String name) {
    this.riInvokeExportedMethod(this, "fetchByName", new String[]{"java.lang.String"}, new Object[] {name});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   createDetail (ResourceObjectAM)
  /**
   ** Initialize the model to create a new <code>Resource Object</code>.
   */
  @Override
  public void createDetail() {
    this.riInvokeExportedMethod(this, "createDetail", null, null);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchDetail (ResourceObjectAM)
  /**
   ** Initialize the model to create a new <code>Resource Object</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Resource Object</code> to fetch from the
   **                            persistence layer.
   **                            Allowed object is {@link String}.
   */
  @Override
  public void fetchDetail(final String identifier) {
    this.riInvokeExportedMethod(this, "fetchDetail", new String [] {"java.lang.String"}, new Object[] {identifier});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   refreshAttribute (ResourceObjectAM)
  /**
   ** Refresh the attributes belonging to a certain
   ** <code>Resource Object</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Resource Object</code> to initialize.
   **                            Allowed object is {@link String}.
   */
  @Override
  public void refreshAttribute(final String identifier) {
    riInvokeExportedMethod(this, "refreshAttribute", new String [] {"java.lang.String"}, new Object[] {identifier});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   refreshReconciliation (ResourceObjectAM)
  /**
   ** Refresh the reconciliation belonging to a certain
   ** <code>Resource Object</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Resource Object</code> to initialize.
   **                            Allowed object is {@link String}.
   */
  @Override
  public void refreshReconciliation(final String identifier) {
    riInvokeExportedMethod(this, "refreshReconciliation", new String [] {"java.lang.String"}, new Object[] {identifier});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   refreshAdministrator (ResourceObjectAM)
  /**
   ** Refresh the administrators belonging to a certain
   ** <code>Resource Object</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Resource Object</code> to initialize.
   **                            Allowed object is {@link String}.
   */
  @Override
  public void refreshAdministrator(final String identifier) {
    riInvokeExportedMethod(this, "refreshAdministrator", new String [] {"java.lang.String"}, new Object[] {identifier});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   refreshAccount (ResourceObjectAM)
  /**
   ** Refresh the accounts belonging to a certain <code>Resource Object</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Resource Object</code> to initialize.
   **                            Allowed object is {@link String}.
   */
  @Override
  public void refreshAccount(final String identifier) {
    riInvokeExportedMethod(this, "refreshAccount", new String [] {"java.lang.String"}, new Object[] {identifier});
  }
}