/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2020. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Employee Self Service Portal
    Subsystem   :   Vehicle Backend Model Component

    File        :   ColorVORowImpl.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    ColorVORowImpl.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    1.0.0.0     2020-02-23  DSteding    First release version
*/

package bka.employee.portal.vehicle.model.view;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;

////////////////////////////////////////////////////////////////////////////////
// class ColorVORowImpl
// ~~~~~ ~~~~~~~~~~~~~~
/**
 ** The <code>Row</code> to coordinate database queries and the view
 ** rows that result from executing queries belonging to
 ** <code>Vehicle Color</code>s.
 **
 ** ---------------------------------------------------------------------
 ** --- File generated by Oracle ADF Business Components Design Time.
 ** --- Mon Jun 11 20:43:53 CEST 2018
 ** --- Custom code may be added to this class.
 ** --- Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 1.0.0.0
 ** @since   1.0.0.0
 */
public class ColorVORowImpl extends ViewRowImpl {


  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  public static final int ID         = AttributesEnum.id.ordinal();
  public static final int ROWVERSION = AttributesEnum.rowVersion.ordinal();
  public static final int CREATEDBY  = AttributesEnum.createdBy.ordinal();
  public static final int CREATEDON  = AttributesEnum.createdOn.ordinal();
  public static final int UPDATEDBY  = AttributesEnum.updatedBy.ordinal();
  public static final int UPDATEDON  = AttributesEnum.updatedOn.ordinal();
  public static final int MEANING    = AttributesEnum.meaning.ordinal();

  //////////////////////////////////////////////////////////////////////////////
  // Member classes
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // class AttributesEnum
  /**
   ** AttributesEnum: generated enum for identifying attributes and accessors.
   ** Do not modify.
   */
  enum AttributesEnum {
      id
    , rowVersion
    , createdBy
    , createdOn
    , updatedBy
    , updatedOn
    , meaning
    ;
  };

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>ColorVORowImpl</code> view object that allows use as
   ** a JavaBean.
   ** <br>
   ** Zero argumment constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public ColorVORowImpl() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Accessor and Mutator methods
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setId
  /**
   ** Sets the attribute value for <code>ID</code> using the alias name
   ** <code>id</code>.
   **
   ** @param  value              the attribute value for <code>ID</code>
   **                            using the alias name <code>id</code>.
   **                            Allowed object is {@link String}.
   */
  public void setId(final String value) {
    setAttributeInternal(ID, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getId
  /**
   ** Returns the attribute value for <code>ID</code> using the alias
   ** name <code>id</code>.
   **
   ** @return                    the attribute value for <code>ID</code>
   **                            using the alias name <code>id</code>.
   **                            Possible object is {@link String}.
   */
  public String getId() {
    return (String)getAttributeInternal(ID);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setRowVersion
  /**
   ** Sets the attribute value for <code>ROWVERSION</code> using the alias name
   ** <code>rowVersion</code>.
   **
   ** @param  value              the attribute value for <code>ROWVERSION</code>
   **                            using the alias name <code>rowVersion</code>.
   **                            Allowed object is {@link String}.
   */
  public void setRowVersion(final String value) {
    setAttributeInternal(ROWVERSION, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getRowVersion
  /**
   ** Returns the attribute value for <code>ROWVERSION</code> using the alias
   ** name <code>rowVersion</code>.
   **
   ** @return                    the attribute value for <code>ROWVERSION</code>
   **                            using the alias name <code>rowVersion</code>.
   **                            Possible object is {@link String}.
   */
  public String getRowVersion() {
    return (String)getAttributeInternal(ROWVERSION);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setCreatedBy
  /**
   ** Sets the attribute value for <code>CREATEDBY</code> using the alias name
   ** <code>createdBy</code>.
   **
   ** @param  value              the attribute value for <code>CREATEDBY</code>
   **                            using the alias name <code>createdBy</code>.
   **                            Allowed object is {@link String}.
   */
  public void setCreatedBy(final String value) {
    setAttributeInternal(CREATEDBY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getCreatedBy
  /**
   ** Returns the attribute value for <code>CREATEDBY</code> using the alias
   ** name <code>createdBy</code>.
   **
   ** @return                    the attribute value for <code>CREATEDBY</code>
   **                            using the alias name <code>createdBy</code>.
   **                            Possible object is {@link String}.
   */
  public String getCreatedBy() {
    return (String)getAttributeInternal(CREATEDBY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setCreatedOn
  /**
   ** Sets the attribute value for <code>CREATEDON</code> using the alias name
   ** <code>createdOn</code>.
   **
   ** @param  value              the attribute value for <code>CREATEDON</code>
   **                            using the alias name <code>createdOn</code>.
   **                            Allowed object is {@link Timestamp}.
   */
  public void setCreatedOn(final Timestamp value) {
    setAttributeInternal(CREATEDON, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getCreatedOn
  /**
   ** Returns the attribute value for <code>CREATEDON</code> using the alias
   ** name <code>createdOn</code>.
   **
   ** @return                    the attribute value for <code>CREATEDON</code>
   **                            using the alias name <code>createdOn</code>.
   **                            Possible object is {@link Timestamp}.
   */
  public Timestamp getCreatedOn() {
    return (Timestamp)getAttributeInternal(CREATEDON);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setUpdatedBy
  /**
   ** Sets the attribute value for <code>UPDATEDBY</code> using the alias name
   ** <code>updatedBy</code>.
   **
   ** @param  value              the attribute value for <code>UPDATEDBY</code>
   **                            using the alias name <code>updatedBy</code>.
   **                            Allowed object is {@link String}.
   */
  public void setUpdatedBy(final String value) {
    setAttributeInternal(UPDATEDBY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getUpdatedBy
  /**
   ** Returns the attribute value for <code>UPDATEDBY</code> using the alias
   ** name <code>updatedBy</code>.
   **
   ** @return                    the attribute value for <code>UPDATEDBY</code>
   **                            using the alias name <code>updatedBy</code>.
   **                            Possible object is {@link String}.
   */
  public String getUpdatedBy() {
    return (String)getAttributeInternal(UPDATEDBY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setUpdatedOn
  /**
   ** Sets the attribute value for <code>UPDATEDON</code> using the alias name
   ** <code>updatedOn</code>.
   **
   ** @param  value              the attribute value for <code>UPDATEDON</code>
   **                            using the alias name <code>updatedOn</code>.
   **                            Allowed object is {@link Timestamp}.
   */
  public void setUpdatedOn(final Timestamp value) {
    setAttributeInternal(UPDATEDON, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getUpdatedOn
  /**
   ** Returns the attribute value for <code>UPDATEDON</code> using the alias
   ** name <code>updatedOn</code>.
   **
   ** @return                    the attribute value for <code>UPDATEDON</code>
   **                            using the alias name <code>updatedOn</code>.
   **                            Possible object is {@link Timestamp}.
   */
  public Timestamp getUpdatedOn() {
    return (Timestamp)getAttributeInternal(UPDATEDON);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setMeaning
  /**
   ** Sets the attribute value for <code>MEANING</code> using the alias name
   ** <code>meaning</code>.
   **
   ** @param  value              the attribute value for <code>MEANING</code>
   **                            using the alias name <code>meaning</code>.
   **                            Allowed object is {@link String}.
   */
  public void setMeaning(final String value) {
    setAttributeInternal(MEANING, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getMeaning
  /**
   ** Returns the attribute value for <code>MEANING</code> using the alias
   ** name <code>meaning</code>.
   **
   ** @return                    the attribute value for <code>MEANING</code>
   **                            using the alias name <code>meaning</code>.
   **                            Possible object is {@link String}.
   */
  public String getMeaning() {
    return (String)getAttributeInternal(MEANING);
  }
}