/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2016. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Employee Self Service Portal
    Subsystem   :   Vehicle Backend Model Component

    File        :   VehicleVORowImpl.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   sylvert.bernet@oracle.com

    Purpose     :   This file implements the class
                    VehicleVORowImpl.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    1.0.0.0     26-06-2020  SBernet     First release version
*/
package bka.employee.portal.vehicle.model.view;

import bka.employee.portal.vehicle.model.view.common.ColorVO;
import bka.employee.portal.vehicle.model.view.common.TypeVO;

import java.math.BigInteger;

import java.sql.Timestamp;

import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;

////////////////////////////////////////////////////////////////////////////////
// class VehicleVORowImpl
// ~~~~~ ~~~~~~~~~~~~~~~~
/**
 ** The <code>Row</code> to coordinate database queries and the view
 ** rows that result from executing queries belonging to
 ** <code>Vehicle</code>s.
 **
 ** ---------------------------------------------------------------------
 ** ---    File generated by Oracle ADF Business Components Design Time.
 ** ---    Wed Jun 03 17:54:16 CEST 2020
 ** ---    Custom code may be added to this class.
 ** ---    Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** @author  sylvert.bernet@oracle.com
 ** @version 1.0.0.0
 ** @since   1.0.0.0
 */
public class VehicleVORowImpl extends ViewRowImpl {

  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  public static final int ID             = AttributesEnum.id.ordinal();
  public static final int CARPLATENUMBER = AttributesEnum.carPlateNumber.ordinal();
  public static final int USRKEY         = AttributesEnum.usrKey.ordinal();
  public static final int BRANDKEY       = AttributesEnum.brandKey.ordinal();
  public static final int COLORKEY       = AttributesEnum.colorKey.ordinal();
  public static final int TYPEKEY        = AttributesEnum.typeKey.ordinal();
  public static final int ROWVERSION     = AttributesEnum.rowversion.ordinal();
  public static final int CREATEDBY      = AttributesEnum.createdBy.ordinal();
  public static final int CREATEDON      = AttributesEnum.createdOn.ordinal();
  public static final int UPDATEDBY      = AttributesEnum.updatedBy.ordinal();
  public static final int UPDATEDON      = AttributesEnum.updatedOn.ordinal();
  public static final int BRANDICON      = AttributesEnum.brandIcon.ordinal();
  public static final int BRANDVO        = AttributesEnum.BrandVO.ordinal();
  public static final int TYPEVO         = AttributesEnum.TypeVO.ordinal();
  public static final int COLORVO        = AttributesEnum.ColorVO.ordinal();															   
  //////////////////////////////////////////////////////////////////////////////
  // Member classes
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // class AttributesEnum;
  /**
   ** AttributesEnum: generated enum for identifying attributes and accessors.
   ** Do not modify.
   */
  enum AttributesEnum {
      id
	, carPlateNumber
	, usrKey
	, brandKey
	, colorKey
	, typeKey
	, rowversion
    , createdBy
    , createdOn
    , updatedBy
    , updatedOn
	, brandIcon
	, BrandVO
	, TypeVO
	, ColorVO
    ;
  };

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>VehicleVORowImpl</code> view object that allows use as a
   ** JavaBean.
   ** <br>
   ** Zero argumment constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public VehicleVORowImpl() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Accessor and Mutator methods
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setId
  /**
   ** Sets the attribute value for <code>ID</code> using the alias name
   ** <code>id</code>.
   **
   ** @param  value              the attribute value for <code>ID</code>
   **                            using the alias name <code>id</code>.
   **                            Allowed object is {@link String}.
   */
  public void setId(final String value) {
    setAttributeInternal(ID, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getId
  /**
   ** Returns the attribute value for <code>ID</code> using the alias
   ** name <code>id</code>.
   **
   ** @return                    the attribute value for <code>ID</code>
   **                            using the alias name <code>id</code>.
   **                            Possible object is {@link String}.
   */
  public String getId() {
    return (String)getAttributeInternal(ID);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setLicensePlateNumber
  /**
   ** Sets the attribute value for <code>CARPLATENUMBER</code> using the alias name
   ** <code>carPlateNumber</code>.
   **
   ** @param  value              the attribute value for <code>CARPLATENUMBER</code>
   **                            using the alias name <code>carPlateNumber</code>.
   **                            Allowed object is {@link String}.
   */
  public void setCarPlateNumber(final String value) {
    setAttributeInternal(CARPLATENUMBER, value);
  }
  
  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getCarPlateNumber
  /**
   ** Returns the attribute value for <code>CARPLATENUMBER</code> using the alias
   ** name <code>carPlateNumber</code>.
   **
   ** @return                    the attribute value for <code>CARPLATENUMBER</code>
   **                            using the alias name <code>carPlateNumber</code>.
   **                            Possible object is {@link String}.
   */
  public String getCarPlateNumber() {
    return (String)getAttributeInternal(CARPLATENUMBER);
  }
  
  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setBrandKey
  /**
   ** Sets the attribute value for <code>BRANDKEY</code> using the alias name
   ** <code>brandKey</code>.
   **
   ** @param  value              the attribute value for <code>BRANDKEY</code>
   **                            using the alias name <code>brandKey</code>.
   **                            Allowed object is {@link String}.
   */
  public void setBrandKey(final String value) {
    setAttributeInternal(BRANDKEY, value);
  }
  
  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getBrandKey
  /**
   ** Returns the attribute value for <code>BRANDKEY</code> using the alias
   ** name <code>brandKey</code>.
   **
   ** @return                    the attribute value for <code>BRANDKEY</code>
   **                            using the alias name <code>brandKey</code>.
   **                            Possible object is {@link String}.
   */
  public String getBrandKey() {
    return (String)getAttributeInternal(BRANDKEY);
  }
  
  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setTypeKey
  /**
   ** Sets the attribute value for <code>TYPEKEY</code> using the alias name
   ** <code>typeKey</code>.
   **
   ** @param  value              the attribute value for <code>TYPEKEY</code>
   **                            using the alias name <code>typeKey</code>.
   **                            Allowed object is {@link String}.
   */
  public void setTypeKey(final String value) {
    setAttributeInternal(TYPEKEY, value);
  }
  
  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getTypeKey
  /**
   ** Returns the attribute value for <code>TYPEKEY</code> using the alias
   ** name <code>typeKey</code>.
   **
   ** @return                    the attribute value for <code>TYPEKEY</code>
   **                            using the alias name <code>typeKey</code>.
   **                            Possible object is {@link String}.
   */
  public String getTypeKey() {
    return (String)getAttributeInternal(TYPEKEY);
  }
  
  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setTypeKey
  /**
   ** Sets the attribute value for <code>COLORKEY</code> using the alias name
   ** <code>colorKey</code>.
   **
   ** @param  value              the attribute value for <code>COLORKEY</code>
   **                            using the alias name <code>colorKey</code>.
   **                            Allowed object is {@link String}.
   */
  public void setColorKey(final String value) {
    setAttributeInternal(COLORKEY, value);
  }
  
  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getTypeKey
  /**
   ** Returns the attribute value for <code>COLORKEY</code> using the alias
   ** name <code>colorKey</code>.
   **
   ** @return                    the attribute value for <code>COLORKEY</code>
   **                            using the alias name <code>colorKey</code>.
   **                            Possible object is {@link String}.
   */
  public String getColorKey() {
    return (String)getAttributeInternal(COLORKEY);
  }
  
  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setTypeKey
  /**
   ** Sets the attribute value for <code>USRKEY</code> using the alias name
   ** <code>usrKey</code>.
   **
   ** @param  value              the attribute value for <code>USRKEY</code>
   **                            using the alias name <code>usrKey</code>.
   **                            Allowed object is {@link String}.
   */
  public void setUsrKey(final String value) {
    setAttributeInternal(USRKEY, value);
  }
  
  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getTypeKey
  /**
   ** Returns the attribute value for <code>USRKEY</code> using the alias
   ** name <code>colorKey</code>.
   **
   ** @return                    the attribute value for <code>USRKEY</code>
   **                            using the alias name <code>usrKey</code>.
   **                            Possible object is {@link String}.
   */
  public String getUsrKey() {
    return (String)getAttributeInternal(USRKEY);
  }
  
  
  
  // Methode:   setRowVersion
  /**
   ** Sets the attribute value for <code>ROWVERSION</code> using the alias name
   ** <code>rowVersion</code>.
   **
   ** @param  value              the attribute value for <code>ROWVERSION</code>
   **                            using the alias name <code>rowVersion</code>.
   **                            Allowed object is {@link String}.
   */
  public void setRowVersion(final String value) {
    setAttributeInternal(ROWVERSION, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getRowVersion
  /**
   ** Returns the attribute value for <code>ROWVERSION</code> using the alias
   ** name <code>rowVersion</code>.
   **
   ** @return                    the attribute value for <code>ROWVERSION</code>
   **                            using the alias name <code>rowVersion</code>.
   **                            Possible object is {@link String}.
   */
  public String getRowVersion() {
    return (String)getAttributeInternal(ROWVERSION);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setCreatedBy
  /**
   ** Sets the attribute value for <code>CREATEDBY</code> using the alias name
   ** <code>createdBy</code>.
   **
   ** @param  value              the attribute value for <code>CREATEDBY</code>
   **                            using the alias name <code>createdBy</code>.
   **                            Allowed object is {@link String}.
   */
  public void setCreatedBy(final String value) {
    setAttributeInternal(CREATEDBY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getCreatedBy
  /**
   ** Returns the attribute value for <code>CREATEDBY</code> using the alias
   ** name <code>createdBy</code>.
   **
   ** @return                    the attribute value for <code>CREATEDBY</code>
   **                            using the alias name <code>createdBy</code>.
   **                            Possible object is {@link String}.
   */
  public String getCreatedBy() {
    return (String)getAttributeInternal(CREATEDBY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setCreatedOn
  /**
   ** Sets the attribute value for <code>CREATEDON</code> using the alias name
   ** <code>createdOn</code>.
   **
   ** @param  value              the attribute value for <code>CREATEDON</code>
   **                            using the alias name <code>createdOn</code>.
   **                            Allowed object is {@link Timestamp}.
   */
  public void setCreatedOn(final Timestamp value) {
    setAttributeInternal(CREATEDON, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getCreatedOn
  /**
   ** Returns the attribute value for <code>CREATEDON</code> using the alias
   ** name <code>createdOn</code>.
   **
   ** @return                    the attribute value for <code>CREATEDON</code>
   **                            using the alias name <code>createdOn</code>.
   **                            Possible object is {@link Timestamp}.
   */
  public Timestamp getCreatedOn() {
    return (Timestamp)getAttributeInternal(CREATEDON);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setUpdatedBy
  /**
   ** Sets the attribute value for <code>UPDATEDBY</code> using the alias name
   ** <code>updatedBy</code>.
   **
   ** @param  value              the attribute value for <code>UPDATEDBY</code>
   **                            using the alias name <code>updatedBy</code>.
   **                            Allowed object is {@link String}.
   */
  public void setUpdatedBy(final String value) {
    setAttributeInternal(UPDATEDBY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getUpdatedBy
  /**
   ** Returns the attribute value for <code>UPDATEDBY</code> using the alias
   ** name <code>updatedBy</code>.
   **
   ** @return                    the attribute value for <code>UPDATEDBY</code>
   **                            using the alias name <code>updatedBy</code>.
   **                            Possible object is {@link String}.
   */
  public String getUpdatedBy() {
    return (String)getAttributeInternal(UPDATEDBY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setUpdatedOn
  /**
   ** Sets the attribute value for <code>UPDATEDON</code> using the alias name
   ** <code>updatedOn</code>.
   **
   ** @param  value              the attribute value for <code>UPDATEDON</code>
   **                            using the alias name <code>updatedOn</code>.
   **                            Allowed object is {@link Timestamp}.
   */
  public void setUpdatedOn(final Timestamp value) {
    setAttributeInternal(UPDATEDON, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getUpdatedOn
  /**
   ** Returns the attribute value for <code>UPDATEDON</code> using the alias
   ** name <code>updatedOn</code>.
   **
   ** @return                    the attribute value for <code>UPDATEDON</code>
   **                            using the alias name <code>updatedOn</code>.
   **                            Possible object is {@link Timestamp}.
   */
  public Timestamp getUpdatedOn() {
    return (Timestamp)getAttributeInternal(UPDATEDON);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setBrandIcon
  /**
   ** Sets the attribute value for <code>BRANDICON</code> using the alias name
   ** <code>brandIcon</code>.
   **
   ** @param  value              the attribute value for <code>BRANDICON</code>
   **                            using the alias name <code>brandIcon</code>.
   **                            Allowed object is {@link String}.
   */
  public void setBrandIcon(final String value) {
    setAttributeInternal(BRANDICON, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getBrandIcon
  /**
   ** Returns the attribute value for <code>BRANDICON</code> using the alias
   ** name <code>brandIcon</code>.
   **
   ** @return                    the attribute value for <code>BRANDICON</code>
   **                            using the alias name <code>brandIcon</code>.
   **                            Possible object is {@link String}.
   */
  public String getBrandIcon() {
    return (String)getAttributeInternal(BRANDICON);
  }
  
  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setBrandVO
  /**
   ** Sets the attribute value for <code>BRANDVO</code> using the alias name
   ** <code>brandVO</code>.
   **
   ** @param  value              the attribute value for <code>BRANDVO</code>
   **                            using the alias name <code>brandVO</code>.
   **                            Allowed object is {@link String}.
   */
  public void setBrandVO(final Object value) {
    setAttributeInternal(BRANDVO, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setTypeVO
  /**
   ** Sets the attribute value for <code>TYPEVO</code> using the alias name
   ** <code>typeVO</code>.
   **
   ** @param  value              the attribute value for <code>TYPEVO</code>
   **                            using the alias name <code>typeVO</code>.
   **                            Allowed object is {@link TypeVO}.
   */
  public void setTypeVO(final Object value) {
    setAttributeInternal(TYPEVO, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setColorVO
  /**
   ** Sets the attribute value for <code>COLORVO</code> using the alias name
   ** <code>colorVO</code>.
   **
   ** @param  value              the attribute value for <code>COLORVO</code>
   **                            using the alias name <code>colorVO</code>.
   **                            Allowed object is {@link ColorVO}.
   */
  public void setColorVO(final Object value) {
    setAttributeInternal(COLORVO, value);
  }
}

