/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2020. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Employee Self Service Portal
    Subsystem   :   Vehicle Backend Model Component

    File        :   VehicleVOImpl.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   sylvert.bernet@oracle.com

    Purpose     :   This file implements the class
                    VehicleVOImpl.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    1.0.0.0     2020-05-28  SBernet     First release version
*/

package bka.employee.portal.vehicle.model.view;

import bka.employee.portal.model.PortalViewObjectImpl;
import bka.employee.portal.vehicle.model.view.common.VehicleVO;

////////////////////////////////////////////////////////////////////////////////
// class VehicleVOImpl
// ~~~~~ ~~~~~~~~~~~~~
/**
 ** The <code>View Object</code> to coordinate database queries and the view
 ** rows that result from executing queries belonging to
 ** <code>Vehicle</code>s.
 ** <p>
 ** A <code>View Object</code> manages a view row set (ViewRowSetImpl). When the
 ** application calls a RowSet method on a <code>View Object</code>, the call is
 ** delegated to the its view row set, which performs the actual operation.
 ** <p>
 ** A <code>View Object</code>'s base definition is provided by a View
 ** Definition object, which is built from the meta-data stored in an XML file.
 ** <br>
 ** The <code>View Object</code> inherits many of its definitions from its View
 ** Definition, but applications can override them in instances.
 ** <p>
 ** A <code>View Object</code> persists until it, or the
 ** <code>Application Module</code> from which it was created, is explicitly
 ** deleted (using remove methods). You can use a given <code>View Object</code>
 ** definition more than once within an <code>Application Module</code>; the
 ** Business Component framework uses View instance names to distinguish between
 ** them.
 ** ---------------------------------------------------------------------
 ** ---    File generated by Oracle ADF Business Components Design Time.
 ** ---    Wed Jun 03 17:54:17 CEST 2020
 ** ---    Custom code may be added to this class.
 ** ---    Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** 
 ** @author  sylvert.bernet@oracle.com
 ** @version 1.0.0.0
 ** @since   1.0.0.0
 */
public class VehicleVOImpl extends PortalViewObjectImpl
                           implements VehicleVO {

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>VehicleVOImpl</code> view object that allows use as a
   ** JavaBean.
   ** <br>
   ** Zero argumment constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public VehicleVOImpl() {
    // ensure inheritance
    super();
  }
}