/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2021 All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   Password Reset

    File        :   RegistrationAMImpl.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    RegistrationAMImpl.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    1.0.0.0     2021-13-09  DSteding    First release version
*/

package bka.iam.identity.password.module;

import oracle.jbo.server.ApplicationModuleImpl;

import bka.iam.identity.password.model.view.AccountPasswordVOImpl;
import bka.iam.identity.password.model.view.IdentityPasswordVOImpl;

import bka.iam.identity.password.module.common.ResetPasswordAM;

////////////////////////////////////////////////////////////////////////////////
// class ResetPasswordAMImpl
// ~~~~~ ~~~~~~~~~~~~~~~~~~~
/**
 ** The <code>Entity Object</code> to coordinate representations of database
 ** rows belonging to <code>Password</code>s.
 ** <p>
 ** An <code>Entity Object</code> provides an object-oriented representation of
 ** the data it caches from a database object, such as a table or view. Database
 ** rows are presented as individual Entities, in which attributes typically
 ** correspond to columns in the corresponding table.
 ** ---------------------------------------------------------------------
 ** ---    File generated by Oracle ADF Business Components Design Time.
 ** ---    Mon Sep 13 08:37:29 CEST 2021
 ** ---    Custom code may be added to this class.
 ** ---    Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public class ResetPasswordAMImpl extends   ApplicationModuleImpl
                                implements ResetPasswordAM {

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>ResetPasswordAMImpl</code> application module that
   ** allows use as a JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public ResetPasswordAMImpl() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Accessor methods
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   getAccountPasswordVO
  /**
   ** Container's getter for {@link AccountPasswordVOImpl}.
   **
   ** @return                    the implementation of view object
   **                            <code>AccountPasswordVO</code>.
   */
  public AccountPasswordVOImpl getAccountPasswordVO() {
    return (AccountPasswordVOImpl)findViewObject("AccountPasswordVO");
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   getIdentityPasswordVO
  /**
   ** Container's getter for {@link IdentityPasswordVOImpl}.
   **
   ** @return                    the implementation of view object
   **                            <code>IdentityPasswordVO</code>.
   */
  public IdentityPasswordVOImpl getIdentityPasswordVO() {
    return (IdentityPasswordVOImpl)findViewObject("IdentityPasswordVO");
  }
}