/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Authorization Management

    File        :   EntitlementAMClient.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    EntitlementAMClient.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysauthz.module.client;

import java.util.Map;
import java.util.List;

import oracle.jbo.client.remote.ApplicationModuleImpl;

import oracle.iam.platform.authopss.vo.EntityPublication;

import oracle.iam.ui.platform.model.common.IdentityModelAdapterBean;

import oracle.iam.identity.sysauthz.module.common.EntitlementAM;

////////////////////////////////////////////////////////////////////////////////
// class EntitlementAMClient
// ~~~~~ ~~~~~~~~~~~~~~~~~~~
/**
 ** The remote {@link ApplicationModuleImpl} to coordinate certain task
 ** belonging to entitlements.
 ** <p>
 ** ---------------------------------------------------------------------
 ** ---    File generated by Oracle ADF Business Components Design Time.
 ** ---    Mon Mar 06 19:50:30 CET 2017
 ** ---    Custom code may be added to this class.
 ** ---    Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public class EntitlementAMClient extends    ApplicationModuleImpl
                                 implements EntitlementAM {

  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  // the official serial version ID which says cryptically which version we're
  // compatible with
  @SuppressWarnings("compatibility:-8689632683577693875")
  private static final long serialVersionUID = -5962383133524763595L;

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>EntitlementAMClient</code> application module that
   ** allows use as a JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public EntitlementAMClient() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methods of implemented interfaces
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchByIdentifier (EntitlementAM)
  /**
   ** Finds a certain <code>Entitlement</code> by executing a query against the
   ** persistence layer which leverage the primary key of the entity object.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Entitlement</code> to fetch from the
   **                            persistence layer.
   */
  @Override
  public void fetchByIdentifier(final String identifier) {
    riInvokeExportedMethod(this, "fetchByIdentifier", new String[]{"java.lang.String"}, new Object[] {identifier});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchByName (EntitlementAM)
  /**
   ** Finds a certain <code>Entitlement</code> by executing a query against the
   ** persistence layer which leverage the unique key of the entity object.
   **
   ** @param  name               the unique identifier of the
   **                            <code>Entitlement</code> to fetch from the
   **                            persistence layer.
   */
  @Override
  public void fetchByName(final String name) {
    riInvokeExportedMethod(this, "fetchByName", new String[]{"java.lang.String"}, new Object[] {name});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   assignEntitlementPublication (EntitlementAM)
  /**
   ** Assigns the passed <code>Entity Publication</code>s to an
   ** <code>Entitlement</code>.
   **
   ** @param  selection          the {@link List} of organizations represented
   **                            by {@link IdentityModelAdapterBean} to be
   **                            assigned.
   */
  @Override
  public void assignEntitlementPublication(final List<IdentityModelAdapterBean> selection) {
    riInvokeExportedMethod(this, "assignEntitlementPublication", new String[] { "java.util.List<IdentityModelAdapterBean>"}, new Object[] {selection});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   revokeEntitlementPublication (EntitlementAM)
  /**
   ** Revokes the passed <code>Entity Publication</code>s from an
   ** <code>Entitlement</code>.
   **
   ** @param  selection          the {@link List} of {@link EntityPublication}
   **                            to revoke.
   */
  @Override
  public void revokeEntitlementPublication(final List<EntityPublication> selection) {
    riInvokeExportedMethod(this, "revokeEntitlementPublication", new String[] { "java.util.List<oracle.iam.platform.authopss.vo.EntityPublication>" }, new Object[] { selection });
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   refreshAttribute (EntitlementAM)
  /**
   ** Refresh the attributes belonging to a certain <code>Entitlement</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Entitlement</code> to initialize.
   **                            Allowed object is {@link String}.
   */
  @Override
  public void refreshAttribute(final String identifier) {
    riInvokeExportedMethod(this, "refreshAttribute", new String [] {"java.lang.String"}, new Object[] {identifier});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   requeryPublication (EntitlementAM)
  /**
   ** Initialize the <code>Entity Publication</code>s belonging to a certain
   ** <code>Entitlement</code> to take in account pending changes on
   ** publications.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Entitlement</code> to initialize.
   **                            Allowed object is {@link String}.
   ** @param  pending            the collection of pending changes belonging to
   **                            assigned, revoked and modified publications.
   */
  @Override
  public void requeryPublication(final String identifier, final List<Map<String, Object>> pending) {
    riInvokeExportedMethod(this, "requeryPublication", new String [] {"java.lang.String", "java.util.List<java.util.Map>"}, new Object[] {identifier, pending});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   updatePublication (EntitlementAM)
  /**
   ** Performing an update on the passed <code>Entity Publications</code>.
   **
   ** @param  entityType         the type of the entity to update, either
   **                            <ul>
   **                              <li>Entitlement
   **                              <li>Entitlement
   **                            </ul>.
   ** @param  entityId           the system identifier of the entity to update.
   ** @param  metadata           the data providing the changes.
   */
  @Override
  public void updatePublication(final String entityType, final String entityId, final Map<String, Map<String, Object>> metadata) {
    riInvokeExportedMethod(this, "updatePublication", new String[]{"java.lang.String", "java.lang.String", "java.util.Map<String, Map<String, Object>>"}, new Object[] {entityType, entityId, metadata});
  }
}