/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Configuration Management

    File        :   LookupValueVORowImpl.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    LookupValueVORowImpl.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysconfig.model.view;

import oracle.jbo.domain.ClobDomain;

import oracle.jbo.server.ViewRowImpl;

////////////////////////////////////////////////////////////////////////////////
// class LookupValueVORowImpl
// ~~~~~ ~~~~~~~~~~~~~~~~~~~~
/**
 ** ---------------------------------------------------------------------
 ** --- File generated by Oracle ADF Business Components Design Time.
 ** --- Tue Mar 07 07:51:54 CET 2017
 ** --- Custom code may be added to this class.
 ** --- Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public class LookupValueVORowImpl extends ViewRowImpl {

  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  public static final int VALUEKEY      = AttributesEnum.valueKey.ordinal();
  public static final int LOOKUPKEY     = AttributesEnum.lookupKey.ordinal();
  public static final int ENCODED       = AttributesEnum.encoded.ordinal();
  public static final int DECODED       = AttributesEnum.decoded.ordinal();
  public static final int DISABLED      = AttributesEnum.disabled.ordinal();
  public static final int NOTE          = AttributesEnum.note.ordinal();
  public static final int PENDINGACTION = AttributesEnum.pendingAction.ordinal();
  public static final int ADD           = AttributesEnum.add.ordinal();
  public static final int MOD           = AttributesEnum.mod.ordinal();
  public static final int DEL           = AttributesEnum.del.ordinal();

  //////////////////////////////////////////////////////////////////////////////
  // Member classes
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // class AttributesEnum
  /**
   ** AttributesEnum: generated enum for identifying attributes and accessors.
   ** Do not modify.
   */
  @SuppressWarnings({ "oracle.jbo.attribute-enumeration-classes-rule", "oracle.jbo.attribute-order-rule" })
  private static enum AttributesEnum {
      valueKey
    , lookupKey
    , encoded
    , decoded
    , disabled
    , note
    , pendingAction
    , add
    , mod
    , del
    ;
  };

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>LookupValueVORowImpl</code> view object that allows use
   ** as a JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public LookupValueVORowImpl() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Accessor and Mutator methods
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setLookupKey
  /**
   ** Sets the attribute value for <code>LOOKUPKEY</code> using the alias name
   ** <code>lookupKey</code>.
   **
   ** @param  value              the attribute value for <code>LOOKUPKEY</code>
   **                            using the alias name <code>lookupKey</code>.
   **                            Allowed object is {@link String}.
   */
  public void setLookupKey(final String value) {
    setAttributeInternal(LOOKUPKEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getLookupKey
  /**
   ** Returns the attribute value for <code>LOOKUPKEY</code> using the alias
   ** name <code>lookupKey</code>.
   **
   ** @return                    the attribute value for <code>LOOKUPKEY</code>
   **                            using the alias name <code>lookupKey</code>.
   **                            Possible object is {@link String}.
   */
  public String getLookupKey() {
    return (String)getAttributeInternal(LOOKUPKEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setValueKey
  /**
   ** Sets the attribute value for <code>VALUEKEY</code> using the alias name
   ** <code>valueKey</code>.
   **
   ** @param  value              the attribute value for <code>VALUEKEY</code>
   **                            using the alias name <code>valueKey</code>.
   **                            Allowed object is {@link String}.
   */
  public void setValueKey(final String value) {
    setAttributeInternal(VALUEKEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getValueKey
  /**
   ** Returns the attribute value for <code>VALUEKEY</code> using the alias
   ** name <code>valueKey</code>.
   **
   ** @return                    the attribute value for <code>VALUEKEY</code>
   **                            using the alias name <code>valueKey</code>.
   **                            Possible object is {@link String}.
   */
  public String getValueKey() {
    return (String)getAttributeInternal(VALUEKEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setEncoded
  /**
   ** Sets the attribute value for <code>ENCODED</code> using the alias name
   ** <code>encoded</code>.
   **
   ** @param  value              the attribute value for <code>ENCODED</code>
   **                            using the alias name <code>encoded</code>.
   **                            Allowed object is {@link String}.
   */
  public void setEncoded(final String value) {
    setAttributeInternal(ENCODED, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEncoded
  /**
   ** Returns the attribute value for <code>ENCODED</code> using the alias name
   ** <code>encoded</code>.
   **
   ** @return                    the attribute value for <code>ENCODED</code>
   **                            using the alias name <code>encoded</code>.
   **                            Possible object is {@link String}.
   */
  public String getEncoded() {
    return (String)getAttributeInternal(ENCODED);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setDecoded
  /**
   ** Sets the attribute value for <code>DECODED</code> using the alias name
   ** <code>decoded</code>.
   **
   ** @param  value              the attribute value for <code>DECODED</code>
   **                            using the alias name <code>decoded</code>.
   **                            Allowed object is {@link String}.
   */
  public void setDecoded(final String value) {
    setAttributeInternal(DECODED, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getDecoded
  /**
   ** Returns the attribute value for <code>DECODED</code> using the alias name
   ** <code>decoded</code>.
   **
   ** @return                    the attribute value for <code>DECODED</code>
   **                            using the alias name <code>decoded</code>.
   **                            Possible object is {@link String}.
   */
  public String getDecoded() {
    return (String)getAttributeInternal(DECODED);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setDisabled
  /**
   ** Sets the attribute value for <code>DISABLED</code> using the alias name
   ** <code>disabled</code>.
   **
   ** @param  value              the attribute value for <code>DISABLED</code>
   **                            using the alias name <code>disabled</code>.
   **                            Allowed object is {@link String}.
   */
  public void setDisabled(final String value) {
    setAttributeInternal(DISABLED, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getDisabled
  /**
   ** Returns the attribute value for <code>DISABLED</code> using the alias name
   ** <code>disabled</code>.
   **
   ** @return                    the attribute value for <code>DISABLED</code>
   **                            using the alias name <code>disabled</code>.
   **                            Possible object is {@link String}.
   */
  public String getDisabled() {
    return (String)getAttributeInternal(DISABLED);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setNote
  /**
   ** Sets the attribute value for <code>NOTE</code> using the alias name
   ** <code>note</code>.
   **
   ** @param  value              the attribute value for <code>NOTE</code> using
   **                            the alias name <code>note</code>.
   **                            Allowed object is {@link ClobDomain}.
   */
  public void setNote(final ClobDomain value) {
    setAttributeInternal(NOTE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getNote
  /**
   ** Returns the attribute value for <code>NOTE</code> using the alias name
   ** <code>note</code>.
   **
   ** @return                    the attribute value for <code>NOTE</code> using
   **                            the alias name <code>note</code>.
   **                            Possible object is {@link ClobDomain}.
   */
  public ClobDomain getNote() {
    return (ClobDomain)getAttributeInternal(NOTE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setPendingAction
  /**
   ** Sets the attribute value for <code>PENDINGACTION</code> using the alias
   ** name <code>pendingAction</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>PENDINGACTION</code> using the alias name
   **                            <code>pendingAction</code>.
   **                            Allowed object is {@link String}.
   */
  public void setPendingAction(final String value) {
    setAttributeInternal(PENDINGACTION, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getPendingAction
  /**
   ** Returns the attribute value for <code>PENDINGACTION</code> using the alias
   ** name <code>pendingAction</code>.
   **
   ** @return                    the attribute value for
   **                            <code>PENDINGACTION</code> using the alias name
   **                            <code>pendingAction</code>.
   **                            Possible object is {@link String}.
   */
  public String getPendingAction() {
    return (String)getAttributeInternal(PENDINGACTION);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setAdd
  /**
   ** Sets the attribute value for <code>ADD</code> using the alias name
   ** <code>add</code>.
   **
   ** @param  value              the attribute value for <code>ADD</code> using
   **                            the alias name <code>add</code>.
   **                            Allowed object is {@link String}.
   */
  public void setAdd(final String value) {
    setAttributeInternal(ADD, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getAdd
  /**
   ** Returns the attribute value for <code>ADD</code> using the alias name
   ** <code>add</code>.
   **
   ** @return                    the attribute value for <code>ADD</code> using
   **                            the alias name <code>add</code>.
   **                            Possible object is {@link String}.
   */
  public String getAdd() {
    return (String)getAttributeInternal(ADD);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setMod
  /**
   ** Sets the attribute value for <code>MOD</code> using the alias name
   ** <code>mod</code>.
   **
   ** @param  value              the attribute value for <code>MOD</code> using
   **                            the alias name <code>mod</code>.
   **                            Allowed object is {@link String}.
   */
  public void setMod(final String value) {
    setAttributeInternal(MOD, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getMod
  /**
   ** Returns the attribute value for <code>MOD</code> using the alias name
   ** <code>mod</code>.
   **
   ** @return                    the attribute value for <code>MOD</code> using
   **                            the alias name <code>mod</code>.
   **                            Possible object is {@link String}.
   */
  public String getMod() {
    return (String)getAttributeInternal(MOD);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setDel
  /**
   ** Sets the attribute value for <code>DEL</code> using the alias name
   ** <code>del</code>.
   **
   ** @param  value              the attribute value for <code>DEL</code> using
   **                            the alias name <code>del</code>.
   **                            Allowed object is {@link String}.
   */
  public void setDel(final String value) {
    setAttributeInternal(DEL, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getDel
  /**
   ** Returns the attribute value for <code>DEL</code> using the alias name
   ** <code>del</code>.
   **
   ** @return                    the attribute value for <code>DEL</code> using
   **                            the alias name <code>del</code>.
   **                            Possible object is {@link String}.
   */
  public String getDel() {
    return (String)getAttributeInternal(DEL);
  }
}