/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Configuration Management

    File        :   NotificationTemplateVORowImpl.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    NotificationTemplateVORowImpl.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysconfig.model.view;

import oracle.jbo.server.ViewRowImpl;

import oracle.iam.identity.sysconfig.model.entity.NotificationTemplateEOImpl;

////////////////////////////////////////////////////////////////////////////////
// class NotificationTemplateVORowImpl
// ~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/**
 ** ---------------------------------------------------------------------
 ** --- File generated by Oracle ADF Business Components Design Time.
 ** --- Tue Mar 07 07:51:54 CET 2017
 ** --- Custom code may be added to this class.
 ** --- Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public class NotificationTemplateVORowImpl extends ViewRowImpl {

  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  public static final int ID            = AttributesEnum.id.ordinal();
  public static final int NAME          = AttributesEnum.name.ordinal();
  public static final int EVENT         = AttributesEnum.event.ordinal();
  public static final int DESCRIPTION   = AttributesEnum.description.ordinal();
  public static final int STATUS        = AttributesEnum.status.ordinal();
  public static final int SNMP          = AttributesEnum.snmp.ordinal();
  public static final int DATALEVEL     = AttributesEnum.dataLevel.ordinal();

  //////////////////////////////////////////////////////////////////////////////
  // Member classes
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // class AttributesEnum
  /**
   ** AttributesEnum: generated enum for identifying attributes and accessors.
   ** Do not modify.
   */
  @SuppressWarnings({ "oracle.jbo.attribute-enumeration-classes-rule", "oracle.jbo.attribute-order-rule" })
  private static enum AttributesEnum {
      id
    , name
    , event
    , description
    , status
    , snmp
    , dataLevel
    ;
  };

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>NotificationTemplateVORowImpl</code> view object that
   ** allows use as a JavaBean.
   ** <br>
   ** Zero argument constructor runOn by the framework.
   ** <br>
   ** Default Constructor
   */
  public NotificationTemplateVORowImpl() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Accessor and Mutator methods
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getNotificationTemplateEO
  /**
   ** Returns the Notification Template entity object.
   **
   ** @return                    the NotificationTemplateEO
   */
  public NotificationTemplateEOImpl getNotificationTemplateEO() {
    return (NotificationTemplateEOImpl)getEntity(0);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setId
  /**
   ** Sets the attribute value for <code>ID</code> using the alias name
   ** <code>id</code>.
   **
   ** @param  value              the attribute value for <code>ID</code> using
   **                            the alias name <code>id</code>.
   **                            Allowed object is {@link Long}.
   */
  public void setId(final Long value) {
    setAttributeInternal(ID, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getId
  /**
   ** Returns the attribute value for <code>ID</code> using the alias name
   ** <code>id</code>.
   **
   ** @return                    the attribute value for <code>ID</code> using
   **                            the alias name <code>id</code>.
   **                            Possible object is {@link Long}.
   */
  public Long getId() {
    return (Long)getAttributeInternal(ID);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setName
  /**
   ** Sets the attribute value for <code>NAME</code> using the alias name
   ** <code>name</code>.
   **
   ** @param  value              the attribute value for <code>NAME</code> using
   **                            the alias name <code>name</code>.
   **                            Allowed object is {@link String}.
   */
  public void setName(final String value) {
    setAttributeInternal(NAME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getName
  /**
   ** Returns the attribute value for <code>NAME</code> using the alias
   ** name <code>name</code>.
   **
   ** @return                    the attribute value for <code>NAME</code> using
   **                            the alias name <code>name</code>.
   **                            Possible object is {@link String}.
   */
  public String getName() {
    return (String)getAttributeInternal(NAME);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setEvent
  /**
   ** Sets the attribute value for <code>EVENT</code> using the alias name
   ** <code>event</code>.
   **
   ** @param  value              the attribute value for <code>EVENT</code>
   **                            using the alias name <code>event</code>.
   **                            Allowed object is {@link String}.
   */
  public void setEvent(final String value) {
    setAttributeInternal(EVENT, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEvent
  /**
   ** Returns the attribute value for <code>EVENT</code> using the alias name
   ** <code>event</code>.
   **
   ** @return                    the attribute value for <code>EVENT</code>
   **                            using the alias name <code>event</code>.
   **                            Possible object is {@link String}.
   */
  public String getEvent() {
    return (String)getAttributeInternal(EVENT);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setDescription
  /**
   ** Sets the attribute value for <code>DESCRIPTION</code> using the alias name
   ** <code>description</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>DESCRIPTION</code> using the alias name
   **                            <code>description</code>.
   **                            Allowed object is {@link String}.
   */
  public void setDescription(final String value) {
    setAttributeInternal(DESCRIPTION, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getDescription
  /**
   ** Returns the attribute value for <code>DESCRIPTION</code> using the alias
   ** name <code>description</code>.
   **
   ** @return                    the attribute value for
   **                            <code>DESCRIPTION</code> using the alias name
   **                            <code>description</code>.
   **                            Possible object is {@link String}.
   */
  public String getDescription() {
    return (String)getAttributeInternal(DESCRIPTION);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setStatus
  /**
   ** Sets the attribute value for <code>STATUS</code> using the alias name
   ** <code>status</code>.
   **
   ** @param  value              the attribute value for <code>STATUS</code>
   **                            using the alias name <code>status</code>.
   **                            Allowed object is {@link String}.
   */
  public void setStatus(final String value) {
    setAttributeInternal(STATUS, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getStatus
  /**
   ** Returns the attribute value for <code>STATUS</code> using the alias name
   ** <code>status</code>.
   **
   ** @return                    the attribute value for <code>STATUS</code>
   **                            using the alias name <code>status</code>.
   **                            Possible object is {@link String}.
   */
  public String getStatus() {
    return (String)getAttributeInternal(STATUS);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setSnmp
  /**
   ** Sets the attribute value for <code>SNMP</code> using the alias name
   ** <code>snmp</code>.
   **
   ** @param  value              the attribute value for <code>SNMP</code>
   **                            using the alias name <code>snmp</code>.
   **                            Allowed object is {@link String}.
   */
  public void setSnmp(final String value) {
    setAttributeInternal(SNMP, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getSnmp
  /**
   ** Returns the attribute value for <code>SNMP</code> using the alias name
   ** <code>snmp</code>.
   **
   ** @return                    the attribute value for <code>SNMP</code>
   **                            using the alias name <code>snmp</code>.
   **                            Possible object is {@link String}.
   */
  public String getSnmp() {
    return (String)getAttributeInternal(SNMP);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setDataLevel
  /**
   ** Sets the attribute value for <code>DATALEVEL</code> using the alias name
   ** <code>dataLevel</code>.
   **
   ** @param  value              the attribute value for <code>DATALEVEL</code>
   **                            using the alias name <code>dataLevel</code>.
   **                            Allowed object is {@link String}.
   */
  public void setDataLevel(final String value) {
    setAttributeInternal(DATALEVEL, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getDataLevel
  /**
   ** Returns the attribute value for <code>DATALEVEL</code> using the alias
   ** name <code>dataLevel</code>.
   **
   ** @return                    the attribute value for <code>DATALEVEL</code>
   **                            using the alias name <code>dataLevel</code>.
   **                            Possible object is {@link String}.
   */
  public String getDataLevel() {
    return (String)getAttributeInternal(DATALEVEL);
  }
}