/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Configuration Management

    File        :   PropertyVORowImpl.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    PropertyVORowImpl.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysconfig.model.view;

import oracle.jbo.RowSet;

import oracle.jbo.domain.ClobDomain;

import oracle.jbo.server.ViewRowImpl;

import oracle.iam.identity.sysconfig.model.entity.PropertyEOImpl;

////////////////////////////////////////////////////////////////////////////////
// class PropertyVORowImpl
// ~~~~~ ~~~~~~~~~~~~~~~~~
/**
 ** ---------------------------------------------------------------------
 ** --- File generated by Oracle ADF Business Components Design Time.
 ** --- Tue Mar 07 07:51:54 CET 2017
 ** --- Custom code may be added to this class.
 ** --- Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public class PropertyVORowImpl extends ViewRowImpl {

  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  public static final int PROPERTYKEY   = AttributesEnum.propertyKey.ordinal();
  public static final int PROPERTYNAME  = AttributesEnum.propertyName.ordinal();
  public static final int VALUE         = AttributesEnum.value.ordinal();
  public static final int NAME          = AttributesEnum.name.ordinal();
  public static final int DATALEVEL     = AttributesEnum.dataLevel.ordinal();
  public static final int SYSTEM        = AttributesEnum.system.ordinal();
  public static final int LOGINREQUIRED = AttributesEnum.loginRequired.ordinal();
  public static final int RUNON         = AttributesEnum.runOn.ordinal();
  public static final int NOTE          = AttributesEnum.note.ordinal();
  public static final int DATALEVEL_SET = AttributesEnum.dataLevelSet.ordinal();
  public static final int RUNON_SET     = AttributesEnum.runOnSet.ordinal();

  //////////////////////////////////////////////////////////////////////////////
  // Member classes
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // class AttributesEnum
  /**
   ** AttributesEnum: generated enum for identifying attributes and accessors.
   ** Do not modify.
   */
  @SuppressWarnings({ "oracle.jbo.attribute-enumeration-classes-rule", "oracle.jbo.attribute-order-rule" })
  private static enum AttributesEnum {
      propertyKey
    , propertyName
    , value
    , name
    , dataLevel
    , system
    , loginRequired
    , runOn
    , note
    , runOnSet
    , dataLevelSet
    ;
  };

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>PropertyVORowImpl</code> view object that allows use
   ** as a JavaBean.
   ** <br>
   ** Zero argument constructor runOn by the framework.
   ** <br>
   ** Default Constructor
   */
  public PropertyVORowImpl() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Accessor and Mutator methods
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getPropertyEO
  /**
   ** Returns the Property entity object.
   **
   ** @return                    the PropertyEO
   */
  public PropertyEOImpl getPropertyEO() {
    return (PropertyEOImpl)getEntity(0);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setPropertyKey
  /**
   ** Sets the attribute value for <code>PROPERTYKEY</code> using the alias name
   ** <code>propertyKey</code>.
   **
   ** @param  value              the attribute value for <code>PROPERTYKEY</code>
   **                            using the alias name <code>propertyKey</code>.
   **                            Allowed object is {@link Long}.
   */
  public void setPropertyKey(final Long value) {
    setAttributeInternal(PROPERTYKEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getPropertyKey
  /**
   ** Returns the attribute value for <code>PROPERTYKEY</code> using the alias
   ** name <code>propertyKey</code>.
   **
   ** @return                    the attribute value for <code>PROPERTYKEY</code>
   **                            using the alias name <code>propertyKey</code>.
   **                            Possible object is {@link Long}.
   */
  public Long getPropertyKey() {
    return (Long)getAttributeInternal(PROPERTYKEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setPropertyName
  /**
   ** Sets the attribute value for <code>PROPERTYNAME</code> using the alias
   ** name <code>propertyName</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>PROPERTYNAME</code> using the alias name
   **                            <code>propertyName</code>.
   **                            Allowed object is {@link String}.
   */
  public void setPropertyName(final String value) {
    setAttributeInternal(PROPERTYNAME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getPropertyName
  /**
   ** Returns the attribute value for <code>PROPERTYNAME</code> using the alias
   ** name <code>propertyName</code>.
   **
   ** @return                    the attribute value for
   **                            <code>PROPERTYNAME</code> using the alias name
   **                            <code>propertyName</code>.
   **                            Possible object is {@link String}.
   */
  public String getPropertyName() {
    return (String)getAttributeInternal(PROPERTYNAME);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setValue
  /**
   ** Sets the attribute value for <code>VALUE</code> using the alias name
   ** <code>value</code>.
   **
   ** @param  value              the attribute value for <code>VALUE</code>
   **                            using the alias name <code>value</code>.
   **                            Allowed object is {@link String}.
   */
  public void setValue(final String value) {
    setAttributeInternal(VALUE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getValue
  /**
   ** Returns the attribute value for <code>VALUE</code> using the alias name
   ** <code>value</code>.
   **
   ** @return                    the attribute value for <code>VALUE</code>
   **                            using the alias name <code>value</code>.
   **                            Possible object is {@link String}.
   */
  public String getValue() {
    return (String)getAttributeInternal(VALUE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setName
  /**
   ** Sets the attribute value for <code>NAME</code> using the alias name
   ** <code>name</code>.
   **
   ** @param  value              the attribute value for <code>NAME</code>
   **                            using the alias name <code>name</code>.
   **                            Allowed object is {@link String}.
   */
  public void setName(final String value) {
    setAttributeInternal(NAME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getName
  /**
   ** Returns the attribute value for <code>NAME</code> using the alias name
   ** <code>name</code>.
   **
   ** @return                    the attribute value for <code>NAME</code>
   **                            using the alias name <code>name</code>.
   **                            Possible object is {@link String}.
   */
  public String getName() {
    return (String)getAttributeInternal(NAME);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setDataLevel
  /**
   ** Sets the attribute value for <code>DATALEVEL</code> using the alias name
   ** <code>dataLevel</code>.
   **
   ** @param  value              the attribute value for <code>DATALEVEL</code>
   **                            using the alias name <code>dataLevel</code>.
   **                            Allowed object is {@link String}.
   */
  public void setDataLevel(final String value) {
    setAttributeInternal(DATALEVEL, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getDataLevel
  /**
   ** Returns the attribute value for <code>DATALEVEL</code> using the alias
   ** name <code>dataLevel</code>.
   **
   ** @return                    the attribute value for <code>DATALEVEL</code>
   **                            using the alias name <code>dataLevel</code>.
   **                            Possible object is {@link String}.
   */
  public String getDataLevel() {
    return (String)getAttributeInternal(DATALEVEL);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setSystem
  /**
   ** Sets the attribute value for <code>SYSTEM</code> using the alias name
   ** <code>system</code>.
   **
   ** @param  value              the attribute value for <code>SYSTEM</code>
   **                            using the alias name <code>system</code>.
   **                            Allowed object is {@link String}.
   */
  public void setSystem(final String value) {
    setAttributeInternal(SYSTEM, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getSystem
  /**
   ** Returns the attribute value for <code>SYSTEM</code> using the alias name
   ** <code>system</code>.
   **
   ** @return                    the attribute value for <code>SYSTEM</code>
   **                            using the alias name <code>system</code>.
   **                            Possible object is {@link String}.
   */
  public String getSystem() {
    return (String)getAttributeInternal(SYSTEM);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setLoginRequired
  /**
   ** Sets the attribute value for <code>LOGINREQUIRED</code> using the alias
   ** name <code>loginRequired</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>LOGINREQUIRED</code> using the alias name
   **                            <code>loginRequired</code>.
   **                            Allowed object is {@link String}.
   */
  public void setLoginRequired(final String value) {
    setAttributeInternal(LOGINREQUIRED, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getField
  /**
   ** Returns the attribute value for <code>LOGINREQUIRED</code> using the alias
   ** name <code>loginRequired</code>.
   **
   ** @return                    the attribute value for
   **                            <code>LOGINREQUIRED</code> using the alias name
   **                            <code>loginRequired</code>.
   **                            Possible object is {@link String}.
   */
  public String getLoginRequired() {
    return (String)getAttributeInternal(LOGINREQUIRED);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setRunOn
  /**
   ** Sets the attribute value for <code>RUNON</code> using the alias name
   ** <code>runOn</code>.
   ** <p>
   ** <b>Note</b>:
   ** <br>
   ** The Java system of the attributes must be {@link String} because the model
   ** defines it as this system.
   ** <br>
   ** The model adapter is responsible to convert it to the proper system of
   ** {@link Boolean}.
   **
   ** @param  value              the attribute value for <code>RUNON</code>
   **                            using the alias name <code>runOn</code>.
   **                            Allowed object is {@link String}.
   */
  public void setRunOn(final String value) {
    setAttributeInternal(RUNON, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getRunOn
  /**
   ** Returns the attribute value for <code>RUNON</code> using the alias name
   ** <code>runOn</code>.
   ** <p>
   ** <b>Note</b>:
   ** <br>
   ** The Java system of the attributes must be {@link String} because the model
   ** defines it as this system.
   ** <br>
   ** The model adapter is responsible to convert it to the proper system of
   ** {@link Boolean}.
   **
   ** @return                    the attribute value for <code>RUNON</code>
   **                            using the alias name <code>runOn</code>.
   **                            Possible object is {@link String}.
   */
  public String getRunOn() {
    return (String)getAttributeInternal(RUNON);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setNote
  /**
   ** Sets the attribute value for <code>NOTE</code> using the alias name
   ** <code>note</code>.
   **
   ** @param  value              the attribute value for <code>NOTE</code> using
   **                            the alias name <code>note</code>.
   **                            Allowed object is {@link ClobDomain}.
   */
  public void setNote(final ClobDomain value) {
    setAttributeInternal(NOTE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getNote
  /**
   ** Returns the attribute value for <code>NOTE</code> using the alias name
   ** <code>note</code>.
   **
   ** @return                    the attribute value for <code>NOTE</code> using
   **                            the alias name <code>note</code>.
   **                            Possible object is {@link ClobDomain}.
   */
  public ClobDomain getNote() {
    return (ClobDomain)getAttributeInternal(NOTE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setDataLevelSet
  /**
   ** Sets the attribute value for <code>DATALEVEL_SET</code> using the alias
   ** name <code>dataLevelSet</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>DATALEVEL_SET</code> using the alias name
   **                            <code>dataLevelSet</code>.
   **                            Allowed object is {@link RowSet}.
   */
  public void setDataLevelSet(final RowSet value) {
    setAttributeInternal(DATALEVEL_SET, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getDataLevelSet
  /**
   ** Returns the attribute value for <code>DATALEVEL_SET</code> using the alias
   ** name <code>dataLevelSet</code>.
   ** <p>
   ** <b>Note</b>:
   ** <br>
   ** The Java system of the attributes must be {@link String} because the model
   ** defines it as this system.
   ** <br>
   ** The model adapter is responsible to convert it to the proper system of
   ** {@link Boolean}.
   **
   ** @return                    the attribute value for
   **                            <code>DATALEVEL_SET</code> using the alias name
   **                            <code>dataLevelSet</code>.
   **                            Possible object is {@link RowSet}.
   */
  public RowSet getDataLevelSet() {
    return (RowSet)getAttributeInternal(DATALEVEL_SET);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setRunOnSet
  /**
   ** Sets the attribute value for <code>RUNON_SET</code> using the alias name
   ** <code>runOnSet</code>.
   **
   ** @param  value              the attribute value for <code>RUNON_SET</code>
   **                            using the alias name <code>runOnSet</code>.
   **                            Allowed object is {@link RowSet}.
   */
  public void setRunOnSet(final RowSet value) {
    setAttributeInternal(RUNON_SET, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getRunOnSet
  /**
   ** Returns the attribute value for <code>RUNON_SET</code> using the alias
   ** name <code>runOnSet</code>.
   ** <p>
   ** <b>Note</b>:
   ** <br>
   ** The Java system of the attributes must be {@link String} because the model
   ** defines it as this system.
   ** <br>
   ** The model adapter is responsible to convert it to the proper system of
   ** {@link Boolean}.
   **
   ** @return                    the attribute value for <code>RUNON_SET</code>
   **                            using the alias name <code>runOnSet</code>.
   **                            Possible object is {@link RowSet}.
   */
  public RowSet getRunOnSet() {
    return (RowSet)getAttributeInternal(RUNON_SET);
  }
}