/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2020. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Employee Self Service Portal
    Subsystem   :   Vehicle Backend Model Component

    File        :   VehicleEOImpl.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   sylvert.bernet@oracle.com

    Purpose     :   This file implements the class
                    VehicleEOImpl.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    1.0.0.0     2020-06-15  SBernet     First release version
*/
package bka.employee.portal.vehicle.model.entity;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;

////////////////////////////////////////////////////////////////////////////////
// class VehicleEOImpl
// ~~~~~ ~~~~~~~~~~~~~
/**
 ** The <code>Entity Object</code> to coordinate representations of database
 ** rows belonging to <code>Vehicle</code>s.
 ** <p>
 ** An <code>Entity Object</code> provides an object-oriented representation of
 ** the data it caches from a database object, such as a table or view. Database
 ** rows are presented as individual Entities, in which attributes typically
 ** correspond to columns in the corresponding table.
 ** ---------------------------------------------------------------------
 ** --- File generated by Oracle ADF Business Components Design Time.
 ** --- Mon Jun 15 13:48:24 CEST 2020
 ** --- Custom code may be added to this class.
 ** --- Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** @author  sylvert.bernet@oracle.com
 ** @version 1.0.0.0
 ** @since   1.0.0.0 
 */
public class VehicleEOImpl extends EntityImpl {

  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  public static final int ID             = AttributesEnum.id.ordinal();
  public static final int CARPLATENUMBER = AttributesEnum.carPlateNumber.ordinal();
  public static final int USRKEY         = AttributesEnum.usrKey.ordinal();
  public static final int BRANDKEY       = AttributesEnum.brandKey.ordinal();
  public static final int COLORKEY       = AttributesEnum.colorKey.ordinal();
  public static final int TYPEKEY        = AttributesEnum.typeKey.ordinal();
  public static final int ROWVERSION     = AttributesEnum.rowVersion.ordinal();
  public static final int CREATEDBY      = AttributesEnum.createdBy.ordinal();
  public static final int CREATEDON      = AttributesEnum.createdOn.ordinal();
  public static final int UPDATEDBY      = AttributesEnum.updatedBy.ordinal();
  public static final int UPDATEDON      = AttributesEnum.updatedOn.ordinal();
  public static final int COLOREO        = AttributesEnum.ColorEO.ordinal();
  public static final int TYPEEO         = AttributesEnum.TypeEO.ordinal();
  public static final int BRANDEO        = AttributesEnum.BrandEO.ordinal();																   
  //////////////////////////////////////////////////////////////////////////////
  // Member classes
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // class AttributesEnum
  // ~~~~~ ~~~~~~~~~~~~~~
  /**
   ** Generated enum for identifying attributes and accessors.
   ** <p>
   ** DO NOT MODIFY.
   */
  protected enum AttributesEnum {
      id
    , carPlateNumber
    , usrKey
    , typeKey
    , brandKey
    , colorKey
    , rowVersion
    , createdBy
    , createdOn
    , updatedBy
    , updatedOn
    , ColorEO
    , TypeEO
    , BrandEO
	;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs an empty <code>VehicleEOImpl</code> values object that allows use
   ** as a JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public VehicleEOImpl() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methods grouped by functionality
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   createPrimaryKey
  /**
   ** Factory method to create a primary row identifier.
   ** <p>
   ** Users should not modify keys: JDeveloper treats keys as if they are
   ** immutable.
   ** <p>
   ** Call getObjectKey() on a row object to get its unique identifier.
   **
   ** @param  carPlateNumber     the value to embed in the primary key.
   **                            Allowed object is {@link String}.
   **
   ** @return                    a {@link Key} object based on given key
   **                            constituents.
   */
  public static Key createPrimaryKey(final String carPlateNumber) {
    return new Key(new Object[] { carPlateNumber });
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   getDefinitionObject
  /**
   ** Returns the named Entity Object definition for client authorization
   ** groups.
   ** <p>
   ** This method use the fully qualified name
   ** <code>bka.employee.portal.vehicle.entity.TypeEO</code>
   ** to get the entity definition from <code>MetaObjectManager</code> and
   ** returns the corresponding Entity definition object.
   **
   ** @return                    the entity definition object corresponding to
   **                            the fully qualified name
   **                            <code>oracle.hcm.model.entity.VehicleEO</code>
   */
  public static synchronized EntityDefImpl getDefinitionObject() {
    return EntityDefImpl.findDefObject("bka.employee.portal.vehicle.model.entity.VehicleEO");
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   create
  /**
   ** Add attribute defaulting logic in this method.
   ** 
   ** @param                    attributeList list of attribute names/values
   **						                to initialize the row
   */
  protected void create(AttributeList attributeList) {
    super.create(attributeList);
    SequenceImpl vhcSeq = new SequenceImpl("VHC_SEQ", getDBTransaction());
    setAttributeInternal(ID, vhcSeq.getSequenceNumber());
  }
}