/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2021 All Rights reserved

    -----------------------------------------------------------------------

    System      :   Identity Manager Service Simulation
    Subsystem   :   Google API Gateway

    File        :   Product.java

    Compiler    :   JDK 1.8

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    Product.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    1.0.0.0     2021-28-01  DSteding    First release version
*/

package oracle.iam.system.simulation.apigee.schema;

import java.util.List;
import java.util.ArrayList;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Collection;

import com.fasterxml.jackson.core.JsonProcessingException;

import oracle.iam.system.simulation.scim.schema.Support;

////////////////////////////////////////////////////////////////////////////////
// class Product
// ~~~~~ ~~~~~~~
/**
 ** <code>Product</code>s bundles together the following:
 ** <ul>
 **   <li>Collection of API resources (URIs)
 **   <li>Service plan
 **   <li>Metadata specific to your business for monitoring or analytics
 **      (optional)
 ** </ul>
 ** An API <code>Product</code> consists of a list of API resources (URIs) and
 ** custom metadata required by the API provider. API products enable you to
 ** bundle and distribute your APIs to multiple developer groups simultaneously
 ** without having to modify code. API <code>Product</code>s provide the basis
 ** for access control in Apigee, as they provide control over the set of API
 ** resources that apps are allowed to consume.
 ** <p>
 ** As part of the app provisioning workflow, developers select from a list of
 ** API products. This selection of an API product is usually made in the
 ** context of a developer portal. The developer app is provisioned with a key
 ** and secret (generated by and stored on Apigee Edge) that enable the app to
 ** access the URIs bundled in the selected API product. To access API resources
 ** bundled in an API product, the app must present the API key issued by Apigee
 ** Edge. Apigee Edge will resolve the key that is presented against an API
 ** product, and then check associated API resources and quota settings.
 ** <p>
 ** The API supports multiple API <code>Product</code>s per app key, which
 ** enables app developers to consume multiple API products without requiring
 ** multiple keys. Also, a key can be 'promoted' from one API product to
 ** another. This enables you to promote developers from 'free' to 'premium' API
 ** <code>Product</code>s seamlessly and without user interruption. 
 **
 ** @author  dieter.steding@oracle.com
 ** @version 1.0.0.0
 ** @since   1.0.0.0
 */
public class Product extends Entity<Product> {

  //////////////////////////////////////////////////////////////////////////////
  // instance attributes
  //////////////////////////////////////////////////////////////////////////////
  
  /**
   ** The API <code>Product</code> name.
   */
  @JsonProperty("name")
  private String         name;

  /**
   ** The name to be displayed in the UI or developer portal to developers
   ** registering for API access.
   */
  @JsonProperty("displayName")
  private String         displayName;

  /**
   ** The string describing the API <code>Product</code>.
   */
  @JsonProperty("description")
  private String         description;

  /**
   ** The approval type as 'manual' or 'auto'.
   */
  @JsonProperty("approvalType")
  private String         approval;

  /**
   ** The number of request messages permitted per app by this API product for
   ** the specified {@link #timeInterval} and {@link #timeUnit}.
   ** <br>
   ** For example, a quota of 50, for a {@link #timeInterval} of 12 and a
   ** {@link #timeUnit} of hours means 50 requests are allowed every 12 hours.
   */
  @JsonProperty("quota")
  private String         quota;

  /**
   ** The time interval over which the number of request messages is calculated.
   */
  @JsonProperty("quotaInterval")
  private String         timeInterval;

  /**
   ** The time unit defined for the timeInterval.
   ** <br>
   ** The following values are allowed:
   ** <ul>
   **   <li>minute
   **   <li>hour
   **   <li>day
   **   <li>month
   ** <ul>
   */
  @JsonProperty("quotaTimeUnit")
  private String         timeUnit;

  /**
   ** Collection of API resources bundled in the API Product.
   */
  @JsonProperty("apiResources")
  private List<String>   resource;

  /**
   ** The collection of environment names in an organization.
   ** <br>
   ** Requests to environments not listed are rejected.
   */
  @JsonProperty("environments")
  private List<String>   environment = new ArrayList<String>();

  /**
   ** The comma-separated list of OAuth scopes that are validated at runtime.
   ** <br>
   ** Apigee Edge validates that the scopes in any access token presented match
   ** the scopes defined in the OAuth policy assoicated with the API product.
   */
  @JsonProperty("scopes")
  private List<String>   scope;

  /**
   ** The comma-separated list of API proxy names to which this API product is
   ** bound.
   ** <br>
   ** By specifying API proxies, you can associate resources in the API
   ** <code>Product</code> with specific API proxies, preventing developers from
   ** accessing those resources through other API proxies.
   ** <br>
   ** Requests to API proxies not listed are rejected.
   ** <br>
   ** <b>Note</b>.
   ** <br>
   ** The API proxy names must already exist in the specified environment as
   ** they will be validated upon creation.
   */
  @JsonProperty("proxies")
  private List<String>    proxy;

  /**
   ** API <code>Product</code> attribute name and value.
   */
  @JsonProperty("attributes")
  private List<Attribute> attribute;

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs an empty <code>Product</code> REST Resource that allows use
   ** as a JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public Product() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Accessor and Mutator methods
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   name
  /**
   ** Sets the unique identifier of the <code>Product</code>.
   **
   ** @param  value              the unique identifier of the
   **                            <code>Product</code>.
   **                            <br>
   **                            Allowed object is {@link String}.
   **
   ** @return                    the <code>Product</code> to allow method
   **                            chaining.
   **                            <br>
   **                            Possible object is <code>Product</code>.
   */
  public final Product name(final String value) {
    this.name = value;
    return this;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   name
  /**
   ** Returns the unique identifier of the <code>Product</code>.
   **
   ** @return                    the unique identifier of the
   **                            <code>Product</code>.
   **                            <br>
   **                            Possible object is {@link String}.
   */
  public final String name() {
    return this.name;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   displayName
  /**
   ** Sets the display name of the <code>Product</code>.
   **
   ** @param  value              the display name of the <code>Product</code>.
   **                            <br>
   **                            Allowed object is {@link String}.
   **
   ** @return                    the <code>Product</code> to allow method
   **                            chaining.
   **                            <br>
   **                            Possible object is <code>Product</code>.
   */
  public final Product displayName(final String value) {
    this.displayName = value;
    return this;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   displayName
  /**
   ** Returns the display name of the <code>Product</code>.
   **
   ** @return                    the display name of the <code>Product</code>.
   **                            <br>
   **                            Possible object is {@link String}.
   */
  public final String displayName() {
    return this.displayName;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   description
  /**
   ** Sets the description of the <code>Product</code>.
   **
   ** @param  value              the description of the <code>Product</code>.
   **                            <br>
   **                            Allowed object is {@link String}.
   **
   ** @return                    the <code>Product</code> to allow method
   **                            chaining.
   **                            <br>
   **                            Possible object is <code>Product</code>.
   */
  public final Product description(final String value) {
    this.description = value;
    return this;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   description
  /**
   ** Returns the description of the <code>Product</code>.
   **
   ** @return                    the description of the <code>Product</code>.
   **                            <br>
   **                            Possible object is {@link String}.
   */
  public final String description() {
    return this.description;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   approval
  /**
   ** Sets the approval type of the <code>Product</code>.
   **
   ** @param  value              the approval type of the <code>Product</code>.
   **                            <br>
   **                            Allowed object is {@link String}.
   **
   ** @return                    the <code>Product</code> to allow method
   **                            chaining.
   **                            <br>
   **                            Possible object is <code>Product</code>.
   */
  public final Product approval(final String value) {
    this.approval = value;
    return this;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   approval
  /**
   ** Returns the approval type of the <code>Product</code>.
   **
   ** @return                    the approval type of the <code>Product</code>.
   **                            <br>
   **                            Possible object is {@link String}.
   */
  public final String approval() {
    return this.approval;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   quota
  /**
   ** Sets the quota of the <code>Product</code>.
   **
   ** @param  value              the quota of the <code>Product</code>.
   **                            <br>
   **                            Allowed object is {@link String}.
   **
   ** @return                    the <code>Product</code> to allow method
   **                            chaining.
   **                            <br>
   **                            Possible object is <code>Product</code>.
   */
  public final Product quota(final String value) {
    this.quota = value;
    return this;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   quota
  /**
   ** Returns the quota of the <code>Product</code>.
   **
   ** @return                    the quota of the <code>Product</code>.
   **                            <br>
   **                            Possible object is {@link String}.
   */
  public final String quota() {
    return this.quota;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   timeInterval
  /**
   ** Sets the time interval of the <code>Product</code>.
   **
   ** @param  value              the time interval of the <code>Product</code>.
   **                            <br>
   **                            Allowed object is {@link String}.
   **
   ** @return                    the <code>Product</code> to allow method
   **                            chaining.
   **                            <br>
   **                            Possible object is <code>Product</code>.
   */
  public final Product timeInterval(final String value) {
    this.timeInterval = value;
    return this;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   timeInterval
  /**
   ** Returns the time interval of the <code>Product</code>.
   **
   ** @return                    the time interval of the <code>Product</code>.
   **                            <br>
   **                            Possible object is {@link String}.
   */
  public final String timeInterval() {
    return this.timeInterval;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   timeUnit
  /**
   ** Sets the time unit of the <code>Product</code>.
   **
   ** @param  value              the time unit of the <code>Product</code>.
   **                            <br>
   **                            Allowed object is {@link String}.
   **
   ** @return                    the <code>Product</code> to allow method
   **                            chaining.
   **                            <br>
   **                            Possible object is <code>Product</code>.
   */
  public final Product timeUnit(final String value) {
    this.timeUnit = value;
    return this;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   timeUnit
  /**
   ** Returns the time unit of the <code>Product</code>.
   **
   ** @return                    the time unit of the <code>Product</code>.
   **                            <br>
   **                            Possible object is {@link String}.
   */
  public final String timeUnit() {
    return this.timeUnit;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   proxy
  /**
   ** Sets the proxies associated with the <code>Product</code>.
   **
   ** @param  value              the proxies associated with the
   **                            <code>Product</code>.
   **                            <br>
   **                            Allowed object is {@link List} where each
   **                            element is of type {@link String}.
   **
   ** @return                    the <code>Product</code> to allow method
   **                            chaining.
   **                            <br>
   **                            Possible object is <code>Tenant</code>.
   */
  public Product proxy(final List<String> value) {
    this.proxy = value;
    return this;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   proxy
  /**
   ** Returns the proxies associated with the <code>Product</code>.
   ** <p>
   ** This accessor method returns a reference to the live list, not a snapshot.
   ** Therefore any modification you make to the returned list will be present
   ** inside the JSON object.
   **
   ** @return                    the proxies associated with the
   **                            <code>Product</code>.
   **                            <br>
   **                            Possible object is {@link List} where each
   **                            element is of type {@link String}.
   */
  public List<String> proxy() {
    return this.proxy;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   resource
  /**
   ** Sets the resources associated with the <code>Product</code>.
   **
   ** @param  value              the resources associated with the
   **                            <code>Product</code>.
   **                            <br>
   **                            Allowed object is {@link List} where each
   **                            element is of type {@link String}.
   **
   ** @return                    the <code>Product</code> to allow method
   **                            chaining.
   **                            <br>
   **                            Possible object is <code>Tenant</code>.
   */
  public Product resource(final List<String> value) {
    this.resource = value;
    return this;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   resource
  /**
   ** Returns the resources associated with the <code>Product</code>.
   ** <p>
   ** This accessor method returns a reference to the live list, not a snapshot.
   ** Therefore any modification you make to the returned list will be present
   ** inside the JSON object.
   **
   ** @return                    the resources associated with the
   **                            <code>Product</code>.
   **                            <br>
   **                            Possible object is {@link List} where each
   **                            element is of type {@link String}.
   */
  public List<String> resource() {
    return this.resource;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   scope
  /**
   ** Sets the scopes associated with the <code>Product</code>.
   **
   ** @param  value              the scopes associated with the
   **                            <code>Product</code>.
   **                            <br>
   **                            Allowed object is {@link List} where each
   **                            element is of type {@link String}.
   **
   ** @return                    the <code>Product</code> to allow method
   **                            chaining.
   **                            <br>
   **                            Possible object is <code>Tenant</code>.
   */
  public Product scope(final List<String> value) {
    this.scope = value;
    return this;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   scope
  /**
   ** Returns the scopes associated with the <code>Product</code>.
   ** <p>
   ** This accessor method returns a reference to the live list, not a snapshot.
   ** Therefore any modification you make to the returned list will be present
   ** inside the JSON object.
   **
   ** @return                    the scopes associated with the
   **                            <code>Product</code>.
   **                            <br>
   **                            Possible object is {@link List} where each
   **                            element is of type {@link String}.
   */
  public List<String> scope() {
    return this.scope;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   environment
  /**
   ** Sets the environments associated with the <code>Product</code>.
   **
   ** @param  value              the environments associated with the
   **                            <code>Product</code>.
   **                            <br>
   **                            Allowed object is {@link List} where each
   **                            element is of type {@link String}.
   **
   ** @return                    the <code>Product</code> to allow method
   **                            chaining.
   **                            <br>
   **                            Possible object is <code>Tenant</code>.
   */
  public Product environment(final List<String> value) {
    this.environment = value;
    return this;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   environment
  /**
   ** Returns the environments associated with the <code>Product</code>.
   ** <p>
   ** This accessor method returns a reference to the live list, not a snapshot.
   ** Therefore any modification you make to the returned list will be present
   ** inside the JSON object.
   **
   ** @return                    the environments associated with the
   **                            <code>Product</code>.
   **                            <br>
   **                            Possible object is {@link List} where each
   **                            element is of type {@link String}.
   */
  public List<String> environment() {
    return this.environment;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   attribute
  /**
   ** Sets the extended attribute of the <code>Product</code> mapped at
   ** <code>name</code>.
   **
   ** @param  name               the name of the  attribute.
   **                            <br>
   **                            Allowed object is {@link String}.
   ** @param  value              the value of the  attribute.
   **                            <br>
   **                            Allowed object is {@link String}.
   **
   ** @return                    the <code>Product</code> to allow method
   **                            chaining.
   **                            <br>
   **                            Possible object is <code>Product</code>.
   */
  public final Product attribute(final String name, final String value) {
    if (this.attribute == null) {
      this.attribute = new ArrayList<Attribute>();
    }
    this.attribute.add(new Attribute(name, value));
    return this;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   attribute
  /**
   ** Retusn the extended attribute of the <code>Product</code> mapped at
   ** <code>name</code>.
   **
   ** @param  name               the name of the  attribute.
   **                            <br>
   **                            Allowed object is {@link String}.
   **
   ** @return                    the extended attribute of the
   **                            <code>Product</code>.
   **                            <br>
   **                            Possible object is {@link String}.
   */
  public final String attribute(final String name) {
    String value = null;
    if (this.attribute != null) {
      for (Attribute cursor : this.attribute) {
        if (cursor.name().equals(name)) {
          value = cursor.value();
          break;
        }
      }
    }
    return value;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   attribute
  /**
   ** Return the extended attribute of the <code>Product</code>.
   ** <p>
   ** This accessor method returns a reference to the live collection, not a
   ** snapshot. Therefore any modification you make to the returned list will
   ** be present inside the JSON object.
   **
   ** @return                    the extended attribute of the
   **                            <code>Product</code>.
   **                            <br>
   **                            Allowed object is {@link Collection} where each
   **                            element is of type {@link Attribute}.
   */
  public final Collection<Attribute> attribute() {
    return this.attribute;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methods group by functionality
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   hashCode (overridden)
  /**
   ** Returns a hash code value for the object.
   ** <br>
   ** This method is supported for the benefit of hash tables such as those
   ** provided by {@link java.util.HashMap}.
   ** <p>
   ** The general contract of <code>hashCode</code> is:
   ** <ul>
   **   <li>Whenever it is invoked on the same object more than once during an
   **       execution of a Java application, the <code>hashCode</code> method
   **       must consistently return the same integer, provided no information
   **       used in <code>equals</code> comparisons on the object is modified.
   **       This integer need not remain consistent from one execution of an
   **       application to another execution of the same application.
   **   <li>If two objects are equal according to the
   **       <code>equals(Object)</code> method, then calling the
   **       <code>hashCode</code> method on each of the two objects must
   **       produce the same integer result.
   **   <li>It is <em>not</em> required that if two objects are unequal
   **       according to the {@link java.lang.Object#equals(java.lang.Object)}
   **       method, then calling the <code>hashCode</code> method on each of the
   **       two objects must produce distinct integer results. However, the
   **       programmer should be aware that producing distinct integer results
   **       for unequal objects may improve the performance of hash tables.
   ** </ul>
   **
   ** @return                    a hash code value for this object.
   **                            <br>
   **                            Possible object is <code>int</code>.
   */
  @Override
  public int hashCode() {
    int result = super.hashCode();
    result = PRIME * result + (this.name        != null ? this.name.hashCode()        : 0);
    result = PRIME * result + (this.displayName != null ? this.displayName.hashCode() : 0);
    result = PRIME * result + (this.description != null ? this.description.hashCode() : 0);
    result = PRIME * result + (this.scope       != null ? this.scope.hashCode()       : 0);
    result = PRIME * result + (this.proxy       != null ? this.proxy.hashCode()       : 0);
    result = PRIME * result + (this.resource    != null ? this.resource.hashCode()    : 0);
    result = PRIME * result + (this.environment != null ? this.environment.hashCode() : 0);
    return result;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   toString (overridden)
  /**
   ** Returns the string representation for this instance in its minimal form.
   **
   ** @return                    the string representation for this instance in
   **                            its minimal form.
   **                            <br>
   **                            Possible object is {@link String}.
   */
  @Override
  public String toString() {
    try {
      return Support.objectWriter().writeValueAsString(this);
    }
    catch (JsonProcessingException e) {
      e.printStackTrace();
      return null;
    }
  }
}