/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Configuration Management

    File        :   LookupAM.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the interface
                    LookupAM.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysconfig.module.common;

import java.util.Map;
import java.util.List;

import oracle.jbo.ApplicationModule;

import oracle.iam.identity.sysconfig.schema.LookupAdapter;
import oracle.iam.identity.sysconfig.schema.LookupValueAdapter;

////////////////////////////////////////////////////////////////////////////////
// class LookupAM
// ~~~~~ ~~~~~~~~
/**
 ** The <code>Application Module</code> to coordinate the particular task
 ** belonging <code>Lookup Definitions</code> and <code>Lookup Value</code>s.
 ** <p>
 ** ---------------------------------------------------------------------
 ** ---    File generated by Oracle ADF Business Components Design Time.
 ** ---    Mon Mar 20 14:49:55 CET 2017
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public interface LookupAM extends ApplicationModule {

  //////////////////////////////////////////////////////////////////////////////
  // Methods grouped by functionality
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchByIdentifier
  /**
   ** Finds a certain <code>Lookup Definition</code> by executing a query
   ** against the persistence layer which leverage the primary key of the entity
   ** object.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Lookup Definition</code> to fetch from
   **                            the persistence layer.
   **                            Allowed object is {@link String}.
   */
  void fetchByIdentifier(final String identifier);

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchByName
  /**
   ** Finds a certain <code>Lookup Definition</code> by executing a query
   ** against the persistence layer which leverage the unique key of the entity
   ** object.
   **
   ** @param  lookupName         the unique identifier of the
   **                            <code>Lookup Definition</code> to fetch from
   **                            the persistence layer.
   **                            Allowed object is {@link String}.
   */
  void fetchByName(final String lookupName);

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchDetail
  /**
   ** Initialize the model to maintain an existing
   ** <code>Lookup Definition</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Lookup Definition</code> to fetch from the
   **                            persistence layer.
   **                            Allowed object is {@link String}.
   */
  void fetchDetail(final String identifier);

  //////////////////////////////////////////////////////////////////////////////
  // Method:   createDetail
  /**
   ** Initialize the model to create a new <code>Lookup Definition</code>.
   */
  void createDetail();

  //////////////////////////////////////////////////////////////////////////////
  // Method:   createDetail
  /**
   ** Creates a new <code>Lookup Definition</code>.
   **
   ** @param  mab                the {@link LookupAdapter} model adapter bean,
   **                            with fields set.
   ** @param  value              the {@link List} of {@link LookupValueAdapter}
   **                            model adapter beans, with fields set.
   */
 void createDetail(final LookupAdapter mab, final List<LookupValueAdapter> value);

  //////////////////////////////////////////////////////////////////////////////
  // Method:   modifyDetail
  /**
   ** Modifies an existing <code>Lookup Definition</code>.
   **
   ** @param  mab                the {@link LookupAdapter} model adapter bean,
   **                            with fields set to create.
   ** @param  added              the {@link List} of {@link LookupValueAdapter}
   **                            model adapter beans, with fields set to be
   **                            added to the <code>Lookup Definition</code>
   **                            after its modified.
   ** @param  modified           the {@link List} of {@link LookupValueAdapter}
   **                            model adapter beans, with fields set to be
   **                            modified to the <code>Lookup Definition</code>
   **                            after its modified.
   ** @param  deleted            the {@link List} of {@link LookupValueAdapter}
   **                            model adapter beans, with fields set to be
   **                            deleted to the <code>Lookup Definition</code>
   **                            after its modified.
   */
  void modifyDetail(final LookupAdapter mab, final List<LookupValueAdapter> added, final List<LookupValueAdapter> modified, final List<LookupValueAdapter> deleted);

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchPicker
  /**
   ** Initialize the model to fetch values from a
   ** <code>Lookup Definition</code>.
   **
   ** @param  lookupName         the unique identifier of the
   **                            <code>Lookup Definition</code> the values needs
   **                            to be fetched from the persistence layer.
   **                            Allowed object is {@link String}.
   */
  void fetchPicker(final String lookupName);

  //////////////////////////////////////////////////////////////////////////////
  // Method:   refreshAttribute
  /**
   ** Refresh the a certain <code>Lookup Definition</code> details.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Lookup Definition</code> to refresh.
   **                            Allowed object is {@link String}.
   */
  void refreshAttribute(final String identifier);

  //////////////////////////////////////////////////////////////////////////////
  // Method:   createValue
  /**
   ** Initialize the <code>Lookup Value</code>s belonging to a certain
   ** <code>Lookup Definition</code> and will be provisioned by the
   ** <code>Lookup Definition</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Lookup Definition</code> to initialize.
   **                            Allowed object is {@link String}.
   ** @param  pending            the collection of pending changes belonging to
   **                            added, deleted and modified values.
   */
  void createValue(final String identifier, final Map<String, Map<String, Object>> pending);

  //////////////////////////////////////////////////////////////////////////////
  // Method:   refreshValue
  /**
   ** Refresh the <code>Lookup Value</code>s belonging to a certain
   ** <code>Lookup Definition</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Lookup Definition</code> to refresh.
   **                            Allowed object is {@link String}.
   */
  void refreshValue(final String identifier);

  //////////////////////////////////////////////////////////////////////////////
  // Method:   requeryValue
  /**
   ** Requery the <code>Lookup Value</code>s belonging to a certain
   ** <code>Lookup Definition</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Lookup Definition</code> to query.
   **                            Allowed object is {@link String}.
   ** @param  pending            the collection of pending changes belonging to
   **                            assigned, removed and modified values.
   */
  void requeryValue(final String identifier, final Map<String, Map<String, Object>> pending);
}