/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Configuration Management

    File        :   PropertyAM.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the interface
                    PropertyAM.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysconfig.module.common;

import oracle.jbo.ApplicationModule;

import oracle.iam.identity.sysconfig.schema.PropertyAdapter;

////////////////////////////////////////////////////////////////////////////////
// class PropertyAM
// ~~~~~ ~~~~~~~~~~
/**
 ** The <code>Application Module</code> to coordinate the particular task
 ** belonging <code>Properties</code>.
 ** <p>
 ** ---------------------------------------------------------------------
 ** ---    File generated by Oracle ADF Business Components Design Time.
 ** ---    Mon Mar 20 14:49:55 CET 2017
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public interface PropertyAM extends ApplicationModule {

  //////////////////////////////////////////////////////////////////////////////
  // Methods grouped by functionality
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchByIdentifier
  /**
   ** Finds a certain <code>Property</code> by executing a query against the
   ** persistence layer which leverage the primary key of the entity object.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Property</code> to fetch from the
   **                            persistence layer.
   **                            Allowed object is {@link Long}.
   */
  void fetchByIdentifier(final Long identifier);

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchByName
  /**
   ** Finds a certain <code>Property</code> by executing a query against the
   ** persistence layer which leverage the unique key of the entity object.
   **
   ** @param  lookupName         the unique identifier of the
   **                            <code>Property</code> to fetch from the
   **                            persistence layer.
   **                            Allowed object is {@link String}.
   */
  void fetchByName(final String lookupName);

  //////////////////////////////////////////////////////////////////////////////
  // Method:   createDetail
  /**
   ** Initialize the model to create a new <code>Property</code>.
   */
  void createDetail();

  //////////////////////////////////////////////////////////////////////////////
  // Method:   createDetail
  /**
   ** Creates a new <code>Property</code>.
   **
   ** @param  mab                the {@link PropertyAdapter} model adapter bean,
   **                            with fields set.
   */
 void createDetail(final PropertyAdapter mab);

  //////////////////////////////////////////////////////////////////////////////
  // Method:   modifyDetail
  /**
   ** Modifies an existing <code>Property</code>.
   **
   ** @param  mab                the {@link PropertyAdapter} model adapter bean,
   **                            with fields set to create.
   */
  void modifyDetail(final PropertyAdapter mab);

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchDetail
  /**
   ** Initialize the model to maintain an existing <code>Property</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Property</code> to fetch from the
   **                            persistence layer.
   **                            Allowed object is {@link Long}.
   */
  void fetchDetail(final Long identifier);

  //////////////////////////////////////////////////////////////////////////////
  // Method:   refreshAttribute
  /**
   ** Refresh the a certain <code>Property</code> details.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Property</code> to refresh.
   **                            Allowed object is {@link Long}.
   */
  void refreshAttribute(final Long identifier);
}