/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Authorization Management

    File        :   EntitlementInstanceVORowImpl.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    EntitlementInstanceVORowImpl.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysauthz.model.view;

import java.util.Date;

import oracle.jbo.server.ViewRowImpl;

import oracle.iam.identity.sysauthz.model.entity.EntitlementInstanceEOImpl;

////////////////////////////////////////////////////////////////////////////////
// class EntitlementInstanceVORowImpl
// ~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/**
 ** ---------------------------------------------------------------------
 ** --- File generated by Oracle ADF Business Components Design Time.
 ** --- Tue Mar 07 07:51:54 CET 2017
 ** --- Custom code may be added to this class.
 ** --- Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public class EntitlementInstanceVORowImpl extends ViewRowImpl {

  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  public static final int INSTANCEKEY            = AttributesEnum.instanceKey.ordinal();
  public static final int PROVISIONSTATUS        = AttributesEnum.provisionStatus.ordinal();
  public static final int PROVISIONMECHANISM     = AttributesEnum.provisionMechanism.ordinal();
  public static final int VALIDFROM              = AttributesEnum.validFrom.ordinal();
  public static final int VALIDUNTIL             = AttributesEnum.validUntil.ordinal();
  public static final int RISKUPDATE             = AttributesEnum.riskUpdate.ordinal();
  public static final int ITEMRISK               = AttributesEnum.itemRisk.ordinal();
  public static final int PROVISIONINGRISK       = AttributesEnum.provisioningRisk.ordinal();
  public static final int SUMMARYRISK            = AttributesEnum.summaryRisk.ordinal();
  public static final int ENTITLEMENTKEY         = AttributesEnum.entitlementKey.ordinal();
  public static final int ENTITLEMENTCODE        = AttributesEnum.entitlementCode.ordinal();
  public static final int ENTITLEMENTVALUE       = AttributesEnum.entitlementValue.ordinal();
  public static final int ENTITLEMENTDISPLAYNAME = AttributesEnum.entitlementDisplayName.ordinal();
  public static final int ENTITLEMENTDESCRIPTION = AttributesEnum.entitlementDescription.ordinal();
  public static final int POLICYKEY              = AttributesEnum.policyKey.ordinal();
  public static final int POLICYNAME             = AttributesEnum.policyName.ordinal();
  public static final int RESOURCEKEY            = AttributesEnum.resourceKey.ordinal();
  public static final int RESOURCENAME           = AttributesEnum.resourceName.ordinal();
  public static final int BENEFICIARYKEY         = AttributesEnum.beneficiaryKey.ordinal();
  public static final int BENEFICIARYLOGIN       = AttributesEnum.beneficiaryLogin.ordinal();
  public static final int BENEFICIARYFIRSTNAME   = AttributesEnum.beneficiaryFirstName.ordinal();
  public static final int BENEFICIARYLASTNAME    = AttributesEnum.beneficiaryLastName.ordinal();
  public static final int ORGANIZATIONKEY        = AttributesEnum.organizationKey.ordinal();
  public static final int ORGANIZATIONNAME       = AttributesEnum.organizationName.ordinal();
  public static final int ACCOUNTKEY             = AttributesEnum.accountKey.ordinal();
  public static final int ACCOUNTTYPE            = AttributesEnum.accountType.ordinal();
  public static final int ACCOUNTNAME            = AttributesEnum.accountName.ordinal();

  //////////////////////////////////////////////////////////////////////////////
  // Member classes
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // class AttributesEnum
  /**
   ** AttributesEnum: generated enum for identifying attributes and accessors.
   ** Do not modify.
   */
  @SuppressWarnings({ "oracle.jbo.attribute-enumeration-classes-rule", "oracle.jbo.attribute-order-rule" })
  private static enum AttributesEnum {
      instanceKey
    , provisionStatus
    , provisionMechanism
    , validFrom
    , validUntil
    , riskUpdate
    , itemRisk
    , provisioningRisk
    , summaryRisk
    , entitlementKey
    , entitlementCode
    , entitlementValue
    , entitlementDisplayName
    , entitlementDescription
    , policyKey
    , policyName
    , resourceKey
    , resourceName
    , beneficiaryKey
    , beneficiaryLogin
    , beneficiaryFirstName
    , beneficiaryLastName
    , organizationKey
    , organizationName
    , accountKey
    , accountType
    , accountName
    ;
  };

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>ApplicationInstanceVORowImpl</code> view object that
   ** allows use as a JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public EntitlementInstanceVORowImpl() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Accessor and Mutator methods
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEntitlementInstanceEO
  /**
   ** Returns the EntitlementInstance entity object.
   **
   ** @return                    the getEntitlementInstanceEO
   */
  public EntitlementInstanceEOImpl getEntitlementInstanceEO() {
    return (EntitlementInstanceEOImpl)getEntity(0);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setIdentifier
  /**
   ** Sets the attribute value for <code>INSTANCEKEY</code> using the alias name
   ** <code>instanceKey</code>.
   **
   ** @param  value              the attribute value for <code>INSTANCEKEY</code>
   **                            using the alias name <code>instanceKey</code>.
   **                            Allowed object is {@link Long}.
   */
  public void setIdentifier(final Long value) {
    setAttributeInternal(INSTANCEKEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getIdentifier
  /**
   ** Returns the attribute value for <code>INSTANCEKEY</code> using the alias name
   ** <code>instanceKey</code>.
   **
   ** @return                    the attribute value for <code>INSTANCEKEY</code>
   **                            using the alias name <code>instanceKey</code>.
   **                            Possible object is {@link Long}.
   */
  public Long getIdentifier() {
    return (Long)getAttributeInternal(INSTANCEKEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setEntitlementInstanceCode
  /**
   ** Sets the attribute value for <code>ENTITLEMENTCODE</code> using the alias
   ** name <code>entitlementCode</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>ENTITLEMENTCODE</code> using the alias
   **                            name <code>entitlementCode</code>.
   **                            Allowed object is {@link String}.
   */
  public void setEntitlementInstanceCode(final String value) {
    setAttributeInternal(ENTITLEMENTCODE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setEntitlementStatus
  /**
   ** Sets the attribute value for <code>PROVISIONSTATUS</code> using the
   ** alias name <code>provisionStatus</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>PROVISIONSTATUS</code> using the alias
   **                            name <code>provisionStatus</code>.
   **                            Allowed object is {@link String}.
   */
  public void setEntitlementStatus(final String value) {
    setAttributeInternal(PROVISIONSTATUS, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEntitlementStatus
  /**
   ** Returns the attribute value for <code>PROVISIONSTATUS</code> using the
   ** alias name <code>provisionStatus</code>.
   **
   ** @return                    the attribute value for
   **                            <code>PROVISIONSTATUS</code> using the alias
   **                            name <code>provisionStatus</code>.
   **                            Possible display is {@link String}.
   */
  public String getEntitlementStatus() {
    return (String)getAttributeInternal(PROVISIONSTATUS);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getProvisionMechanism
  /**
   ** Returns the attribute value for <code>PROVISIONMECHANISM</code> using the
   ** alias name <code>provisionMechanism</code>.
   **
   ** @return                    the attribute value for
   **                            <code>PROVISIONMECHANISM</code> using the alias
   **                            name <code>provisionMechanism</code>.
   **                            Possible object is {@link String}.
   */
  public String getProvisionMechanism() {
    return (String)getAttributeInternal(PROVISIONMECHANISM);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setProvisionMechanism
  /**
   ** Sets the attribute value for <code>PROVISIONMECHANISM</code> using the alias
   ** name <code>provisionMechanism</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>PROVISIONMECHANISM</code> using the alias
   **                            name <code>provisionMechanism</code>.
   **                            Allowed object is {@link String}.
   */
  public void setProvisionMechanism(final String value) {
    setAttributeInternal(PROVISIONMECHANISM, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getValidFrom
  /**
   ** Returns the attribute value for <code>VALIDFROM</code> using the
   ** alias name <code>validFrom</code>.
   **
   ** @return                    the attribute value for
   **                            <code>VALIDFROM</code> using the alias
   **                            name <code>validFrom</code>.
   **                            Possible object is {@link Date}.
   */
  public Date getValidFrom() {
    return (Date)getAttributeInternal(VALIDFROM);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setValidFrom
  /**
   ** Sets the attribute value for <code>VALIDFROM</code> using the alias
   ** name <code>validFrom</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>VALIDFROM</code> using the alias
   **                            name <code>validFrom</code>.
   **                            Allowed object is {@link Date}.
   */
  public void setValidFrom(final Date value) {
    setAttributeInternal(VALIDFROM, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getValidUntil
  /**
   ** Returns the attribute value for <code>VALIDUNTIL</code> using the
   ** alias name <code>validUntil</code>.
   **
   ** @return                    the attribute value for
   **                            <code>VALIDUNTIL</code> using the alias
   **                            name <code>validUntil</code>.
   **                            Possible object is {@link Date}.
   */
  public Date getValidUntil() {
    return (Date)getAttributeInternal(VALIDUNTIL);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setValidUntil
  /**
   ** Sets the attribute value for <code>VALIDUNTIL</code> using the alias
   ** name <code>validUntil</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>VALIDUNTIL</code> using the alias
   **                            name <code>validUntil</code>.
   **                            Allowed object is {@link Date}.
   */
  public void setValidUntil(final Date value) {
    setAttributeInternal(VALIDUNTIL, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getRiskUpdate
  /**
   ** Returns the attribute value for <code>RISKUPDATE</code> using the
   ** alias name <code>riskUpdate</code>.
   **
   ** @return                    the attribute value for
   **                            <code>RISKUPDATE</code> using the alias
   **                            name <code>riskUpdate</code>.
   **                            Possible object is {@link Date}.
   */
  public Date getRiskUpdate() {
    return (Date)getAttributeInternal(RISKUPDATE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setRiskUpdate
  /**
   ** Sets the attribute value for <code>RISKUPDATE</code> using the alias
   ** name <code>riskUpdate</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>RISKUPDATE</code> using the alias
   **                            name <code>riskUpdate</code>.
   **                            Allowed object is {@link Date}.
   */
  public void setRiskUpdate(final Date value) {
    setAttributeInternal(RISKUPDATE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getItemRisk
  /**
   ** Returns the attribute value for <code>ITEMRISK</code> using the
   ** alias name <code>itemRisk</code>.
   **
   ** @return                    the attribute value for
   **                            <code>ITEMRISK</code> using the alias
   **                            name <code>itemRisk</code>.
   **                            Possible object is {@link Integer}.
   */
  public Integer getItemRisk() {
    return (Integer)getAttributeInternal(ITEMRISK);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setItemRisk
  /**
   ** Sets the attribute value for <code>ITEMRISK</code> using the alias
   ** name <code>itemRisk</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>ITEMRISK</code> using the alias
   **                            name <code>itemRisk</code>.
   **                            Allowed object is {@link Integer}.
   */
  public void setItemRisk(final Integer value) {
    setAttributeInternal(ITEMRISK, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getProvisioningRisk
  /**
   ** Returns the attribute value for <code>PROVISIONINGRISK</code> using the
   ** alias name <code>provisioningRisk</code>.
   **
   ** @return                    the attribute value for
   **                            <code>PROVISIONINGRISK</code> using the alias
   **                            name <code>provisioningRisk</code>.
   **                            Possible object is {@link Integer}.
   */
  public Integer getProvisioningRisk() {
    return (Integer)getAttributeInternal(PROVISIONINGRISK);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setProvisioningRisk
  /**
   ** Sets the attribute value for <code>PROVISIONINGRISK</code> using the alias
   ** name <code>provisioningRisk</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>PROVISIONINGRISK</code> using the alias
   **                            name <code>provisioningRisk</code>.
   **                            Allowed object is {@link Integer}.
   */
  public void setProvisioningRisk(final Integer value) {
    setAttributeInternal(PROVISIONINGRISK, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getSummaryRisk
  /**
   ** Returns the attribute value for <code>SUMMARYRISK</code> using the
   ** alias name <code>summaryRisk</code>.
   **
   ** @return                    the attribute value for
   **                            <code>SUMMARYRISK</code> using the alias
   **                            name <code>summaryRisk</code>.
   **                            Possible object is {@link Integer}.
   */
  public Integer getSummaryRisk() {
    return (Integer)getAttributeInternal(SUMMARYRISK);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setSummaryRisk
  /**
   ** Sets the attribute value for <code>SUMMARYRISK</code> using the alias
   ** name <code>summaryRisk</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>SUMMARYRISK</code> using the alias
   **                            name <code>summaryRisk</code>.
   **                            Allowed object is {@link Integer}.
   */
  public void setSummaryRisk(final Integer value) {
    setAttributeInternal(SUMMARYRISK, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setEntitlementKey
  /**
   ** Sets the attribute value for <code>ENTITLEMENTKEY</code> using the alias name
   ** <code>entitlementKey</code>.
   **
   ** @param  value              the attribute value for <code>ENTITLEMENTKEY</code>
   **                            using the alias name <code>entitlementKey</code>.
   **                            Allowed object is {@link Long}.
   */
  public void setEntitlementKey(final Long value) {
    setAttributeInternal(ENTITLEMENTKEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEntitlementKey
  /**
   ** Returns the attribute value for <code>ENTITLEMENTKEY</code> using the alias name
   ** <code>entitlementKey</code>.
   **
   ** @return                    the attribute value for <code>ENTITLEMENTKEY</code>
   **                            using the alias name <code>entitlementKey</code>.
   **                            Possible object is {@link Long}.
   */
  public Long getEntitlementKey() {
    return (Long)getAttributeInternal(ENTITLEMENTKEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setEntitlementCode
  /**
   ** Sets the attribute value for <code>ENTITLEMENTCODE</code> using the alias
   ** name <code>entitlementCode</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>ENTITLEMENTCODE</code> using the alias
   **                            name <code>entitlementCode</code>.
   **                            Allowed object is {@link String}.
   */
  public void setEntitlementCode(final String value) {
    setAttributeInternal(ENTITLEMENTCODE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEntitlementCode
  /**
   ** Returns the attribute value for <code>ENTITLEMENTCODE</code> using the
   ** alias name <code>entitlementCode</code>.
   **
   ** @return                    the attribute value for
   **                            <code>ENTITLEMENTCODE</code> using the alias
   **                            name <code>entitlementCode</code>.
   **                            Possible object is {@link String}.
   */
  public String getEntitlementCode() {
    return (String)getAttributeInternal(ENTITLEMENTCODE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setEntitlementValue
  /**
   ** Sets the attribute value for <code>ENTITLEMENTVALUE</code> using the alias
   ** name <code>entitlementValue</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>ENTITLEMENTVALUE</code> using the alias
   **                            name <code>entitlementValue</code>.
   **                            Allowed object is {@link String}.
   */
  public void setEntitlementValue(final String value) {
    setAttributeInternal(ENTITLEMENTVALUE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEntitlementValue
  /**
   ** Returns the attribute value for <code>ENTITLEMENTVALUE</code> using the
   ** alias name <code>entitlementValue</code>.
   **
   ** @return                    the attribute value for
   **                            <code>ENTITLEMENTVALUE</code> using the alias
   **                            name <code>entitlementValue</code>.
   **                            Possible object is {@link String}.
   */
  public String getEntitlementValue() {
    return (String)getAttributeInternal(ENTITLEMENTVALUE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setEntitlementDisplayName
  /**
   ** Sets the attribute value for <code>DISPLAYNAME</code> using the alias name
   ** <code>displayName</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>ENTITLEMENTDISPLAYNAME</code> using the
   **                            alias name <code>entitlementDisplayName</code>.
   **                            Allowed object is {@link String}.
   */
  public void setEntitlementDisplayName(final String value) {
    setAttributeInternal(ENTITLEMENTDISPLAYNAME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEntitlementDisplayName
  /**
   ** Returns the attribute value for <code>ENTITLEMENTDISPLAYNAME</code> using
   ** the alias name <code>entitlementDisplayName</code>.
   **
   ** @return                    the attribute value for
   **                            <code>ENTITLEMENTDISPLAYNAME</code> using the
   **                            alias name <code>entitlementDisplayName</code>.
   **                            Possible object is {@link String}.
   */
  public String getEntitlementDisplayName() {
    return (String)getAttributeInternal(ENTITLEMENTDISPLAYNAME);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setEntitlementDescription
  /**
   ** Sets the attribute value for <code>ENTITLEMENTDESCRIPTION</code> using the
   ** alias name <code>entitlementDescription</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>ENTITLEMENTDESCRIPTION</code> using the
   **                            alias name <code>entitlementDescription</code>.
   **                            Allowed object is {@link String}.
   */
  public void setEntitlementDescription(final String value) {
    setAttributeInternal(ENTITLEMENTDESCRIPTION, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEntitlementDescription
  /**
   ** Returns the attribute value for <code>ENTITLEMENTDESCRIPTION</code> using
   ** the alias name <code>entitlementDescription</code>.
   **
   ** @return                    the attribute value for
   **                            <code>ENTITLEMENTDESCRIPTION</code> using the
   **                            alias name <code>entitlementDescription</code>.
   **                            Possible object is {@link String}.
   */
  public String getEntitlementDescription() {
    return (String)getAttributeInternal(ENTITLEMENTDESCRIPTION);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getPolicyKey
  /**
   ** Returns the attribute value for <code>POLICYKEY</code> using the
   ** alias name <code>policyKey</code>.
   **
   ** @return                    the attribute value for
   **                            <code>POLICYKEY</code> using the alias
   **                            name <code>policyKey</code>.
   **                            Possible object is {@link Long}.
   */
  public Long getPolicyKey() {
    return (Long)getAttributeInternal(POLICYKEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setPolicyKey
  /**
   ** Sets the attribute value for <code>POLICYKEY</code> using the alias
   ** name <code>policyKey</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>POLICYKEY</code> using the alias
   **                            name <code>policyKey</code>.
   **                            Allowed object is {@link Long}.
   */
  public void setPolicyKey(final Long value) {
    setAttributeInternal(POLICYKEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setPolicyName
  /**
   ** Sets the attribute value for <code>POLICYNAME</code> using the alias
   ** name <code>policyName</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>POLICYNAME</code> using the alias
   **                            name <code>policyName</code>.
   **                            Allowed object is {@link String}.
   */
  public void setPolicyName(final String value) {
    setAttributeInternal(POLICYNAME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getPolicyName
  /**
   ** Returns the attribute value for <code>POLICYNAME</code> using the
   ** alias name <code>policyName</code>.
   **
   ** @return                    the attribute value for
   **                            <code>POLICYNAME</code> using the alias
   **                            name <code>policyName</code>.
   **                            Possible object is {@link String}.
   */
  public String getPolicyName() {
    return (String)getAttributeInternal(POLICYNAME);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setResourceKey
  /**
   ** Sets the attribute value for <code>RESOURCEKEY</code> using the alias name
   ** <code>resourceKey</code>.
   **
   ** @param  value              the attribute value for <code>RESOURCEKEY</code>
   **                            using the alias name <code>resourceKey</code>.
   **                            Allowed object is {@link String}.
   */
  public void setResourceKey(final Long value) {
    setAttributeInternal(RESOURCEKEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getResourceKey
  /**
   ** Returns the attribute value for <code>RESOURCEKEY</code> using the alias
   ** name <code>resourceKey</code>.
   **
   ** @return                    the attribute value for <code>RESOURCEKEY</code>
   **                            using the alias name <code>resourceKey</code>.
   **                            Possible object is {@link String}.
   */
  public Long getResourceKey() {
    return (Long)getAttributeInternal(RESOURCEKEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setResourceName
  /**
   ** Sets the attribute value for <code>RESOURCENAME</code> using the alias
   ** name <code>resourceName</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>RESOURCENAME</code> using the alias
   **                            name <code>resourceName</code>.
   **                            Allowed object is {@link String}.
   */
  public void setResourceName(final String value) {
    setAttributeInternal(RESOURCENAME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getResourceName
  /**
   ** Returns the attribute value for <code>RESOURCENAME</code> using the
   ** alias name <code>resourceName</code>.
   **
   ** @return                    the attribute value for
   **                            <code>RESOURCENAME</code> using the alias
   **                            name <code>resourceName</code>.
   **                            Possible object is {@link String}.
   */
  public String getResourceName() {
    return (String)getAttributeInternal(RESOURCENAME);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setBeneficiaryKey
  /**
   ** Sets the attribute value for <code>BENEFICIARYKEY</code> using the alias
   ** name <code>beneficiaryKey</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>BENEFICIARYKEY</code> using the alias
   **                            name <code>beneficiaryKey</code>.
   **                            Allowed object is {@link Long}.
   */
  public void setBeneficiaryKey(final Long value) {
    setAttributeInternal(BENEFICIARYKEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getBeneficiaryKey
  /**
   ** Returns the attribute value for <code>BENEFICIARYKEY</code> using the
   ** alias name <code>beneficiaryKey</code>.
   **
   ** @return                    the attribute value for
   **                            <code>BENEFICIARYKEY</code> using the alias
   **                            name <code>beneficiaryKey</code>.
   **                            Possible object is {@link Long}.
   */
  public Long getBeneficiaryKey() {
    return (Long)getAttributeInternal(BENEFICIARYKEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setBeneficiaryLogin
  /**
   ** Sets the attribute value for <code>BENEFICIARYLOGIN</code> using the alias
   ** name <code>beneficiaryLogin</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>BENEFICIARYLOGIN</code> using the alias
   **                            name <code>beneficiaryLogin</code>.
   **                            Allowed object is {@link String}.
   */
  public void setBeneficiaryLogin(final String value) {
    setAttributeInternal(BENEFICIARYLOGIN, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getBeneficiaryLogin
  /**
   ** Returns the attribute value for <code>BENEFICIARYLOGIN</code> using the
   ** alias name <code>beneficiaryLogin</code>.
   **
   ** @return                    the attribute value for
   **                            <code>BENEFICIARYLOGIN</code> using the alias
   **                            name <code>beneficiaryLogin</code>.
   **                            Possible object is {@link String}.
   */
  public String getBeneficiaryLogin() {
    return (String)getAttributeInternal(BENEFICIARYLOGIN);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setBeneficiaryFirstName
  /**
   ** Sets the attribute value for <code>BENEFICIARYFIRSTNAME</code> using the
   ** alias name <code>beneficiaryFirstName</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>BENEFICIARYFIRSTNAME</code> using the
   **                            alias name <code>beneficiaryFirstName</code>.
   **                            Allowed object is {@link String}.
   */
  public void setBeneficiaryFirstName(final String value) {
    setAttributeInternal(BENEFICIARYFIRSTNAME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getBeneficiaryFirstName
  /**
   ** Returns the attribute value for <code>BENEFICIARYFIRSTNAME</code> using
   ** the alias name <code>beneficiaryFirstName</code>.
   **
   ** @return                    the attribute value for
   **                            <code>BENEFICIARYFIRSTNAME</code> using the
   **                            alias name <code>beneficiaryFirstName</code>.
   **                            Possible object is {@link String}.
   */
  public String getBeneficiaryFirstName() {
    return (String)getAttributeInternal(BENEFICIARYFIRSTNAME);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setBeneficiaryLastName
  /**
   ** Sets the attribute value for <code>BENEFICIARYLASTNAME</code> using the
   ** alias name <code>beneficiaryLastName</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>BENEFICIARYLASTNAME</code> using the
   **                            alias name <code>beneficiaryLastName</code>.
   **                            Allowed object is {@link String}.
   */
  public void setBeneficiaryLastName(final String value) {
    setAttributeInternal(BENEFICIARYLASTNAME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getBeneficiaryLastName
  /**
   ** Returns the attribute value for <code>BENEFICIARYLASTNAME</code> using
   ** the alias name <code>beneficiaryLastName</code>.
   **
   ** @return                    the attribute value for
   **                            <code>BENEFICIARYLASTNAME</code> using the
   **                            alias name <code>beneficiaryLastName</code>.
   **                            Possible object is {@link String}.
   */
  public String getBeneficiaryLastName() {
    return (String)getAttributeInternal(BENEFICIARYLASTNAME);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setOrganizationKey
  /**
   ** Sets the attribute value for <code>ORGANIZATIONKEY</code> using the alias name
   ** <code>organizationKey</code>.
   **
   ** @param  value              the attribute value for <code>ORGANIZATIONKEY</code>
   **                            using the alias name <code>organizationKey</code>.
   **                            Allowed object is {@link String}.
   */
  public void setOrganizationKey(final Long value) {
    setAttributeInternal(ORGANIZATIONKEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getOrganizationKey
  /**
   ** Returns the attribute value for <code>ORGANIZATIONKEY</code> using the alias
   ** name <code>organizationKey</code>.
   **
   ** @return                    the attribute value for <code>ORGANIZATIONKEY</code>
   **                            using the alias name <code>organizationKey</code>.
   **                            Possible object is {@link String}.
   */
  public Long getOrganizationKey() {
    return (Long)getAttributeInternal(ORGANIZATIONKEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setOrganizationName
  /**
   ** Sets the attribute value for <code>ORGANIZATIONNAME</code> using the alias
   ** name <code>organizationName</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>ORGANIZATIONNAME</code> using the alias
   **                            name <code>organizationName</code>.
   **                            Allowed object is {@link String}.
   */
  public void setOrganizationName(final String value) {
    setAttributeInternal(ORGANIZATIONNAME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getOrganizationName
  /**
   ** Returns the attribute value for <code>ORGANIZATIONNAME</code> using the
   ** alias name <code>organizationName</code>.
   **
   ** @return                    the attribute value for
   **                            <code>ORGANIZATIONNAME</code> using the alias
   **                            name <code>organizationName</code>.
   **                            Possible object is {@link String}.
   */
  public String getOrganizationName() {
    return (String)getAttributeInternal(ORGANIZATIONNAME);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setAccountKey
  /**
   ** Sets the attribute value for <code>ACCOUNTKEY</code> using the alias name
   ** <code>accountKey</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>ACCOUNTKEY</code> using the alias name
   **                            <code>accountKey</code>.
   **                            Allowed object is {@link Long}.
   */
  public void setAccountKey(final Long value) {
    setAttributeInternal(ACCOUNTKEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getAccountKey
  /**
   ** Returns the attribute value for <code>ACCOUNTKEY</code> using the alias
   ** name <code>accountKey</code>.
   **
   ** @return                    the attribute value for
   **                            <code>ACCOUNTKEY</code> using the alias name
   **                            <code>accountKey</code>.
   **                            Possible object is {@link Long}.
   */
  public Long getAccountKey() {
    return (Long)getAttributeInternal(ACCOUNTKEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setAccountType
  /**
   ** Sets the attribute value for <code>ACCOUNTTYPE</code> using the alias name
   ** <code>accountType</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>ACCOUNTTYPE</code> using the alias name
   **                            <code>accountType</code>.
   **                            Allowed object is {@link String}.
   */
  public void setAccountType(final String value) {
    setAttributeInternal(ACCOUNTTYPE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getAccountType
  /**
   ** Returns the attribute value for <code>ACCOUNTTYPE</code> using the alias
   ** name <code>accountType</code>.
   **
   ** @return                    the attribute value for
   **                            <code>ACCOUNTTYPE</code> using the alias name
   **                            <code>accountType</code>.
   **                            Possible object is {@link String}.
   */
  public String getAccountType() {
    return (String)getAttributeInternal(ACCOUNTTYPE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setAccountName
  /**
   ** Sets the attribute value for <code>ACCOUNTNAME</code> using the alias name
   ** <code>accountName</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>ACCOUNTNAME</code> using the alias name
   **                            <code>accountName</code>.
   **                            Allowed object is {@link String}.
   */
  public void setAccountName(final String value) {
    setAttributeInternal(ACCOUNTNAME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getAccountName
  /**
   ** Returns the attribute value for <code>ACCOUNTNAME</code> using the alias
   ** name <code>accountName</code>.
   **
   ** @return                    the attribute value for
   **                            <code>ACCOUNTNAME</code> using the alias name
   **                            <code>accountName</code>.
   **                            Possible object is {@link String}.
   */
  public String getAccountName() {
    return (String)getAttributeInternal(ACCOUNTNAME);
  }
}