/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Authorization Management

    File        :   EntityPublicationVORowImpl.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    EntityPublicationVORowImpl.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysauthz.model.view;

import oracle.jbo.server.ViewRowImpl;

import oracle.iam.identity.sysauthz.model.entity.EntityPublicationEOImpl;

////////////////////////////////////////////////////////////////////////////////
// class EntityPublicationVORowImpl
// ~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~
/**
 ** ---------------------------------------------------------------------
 ** --- File generated by Oracle ADF Business Components Design Time.
 ** --- Tue Mar 07 07:51:54 CET 2017
 ** --- Custom code may be added to this class.
 ** --- Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public class EntityPublicationVORowImpl extends ViewRowImpl {

  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  public static final int PUBLICATIONID     = AttributesEnum.publicationId.ordinal();
  public static final int ENTITYID          = AttributesEnum.entityId.ordinal();
  public static final int ENTITYTYPE        = AttributesEnum.entityType.ordinal();
  public static final int SCOPEID           = AttributesEnum.scopeId.ordinal();
  public static final int SCOPENAME         = AttributesEnum.scopeName.ordinal();
  public static final int SCOPETYPE         = AttributesEnum.scopeType.ordinal();
  public static final int SCOPESTATUS       = AttributesEnum.scopeStatus.ordinal();
  public static final int HIERARCHICALSCOPE = AttributesEnum.hierarchicalScope.ordinal();

  //////////////////////////////////////////////////////////////////////////////
  // Member classes
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // class AttributesEnum
  /**
   ** AttributesEnum: generated enum for identifying attributes and accessors.
   ** Do not modify.
   */
  @SuppressWarnings({ "oracle.jbo.attribute-enumeration-classes-rule", "oracle.jbo.attribute-order-rule" })
  private static enum AttributesEnum {
      publicationId
    , entityId
    , entityType
    , scopeId
    , scopeName
    , scopeType
    , scopeStatus
    , hierarchicalScope
    ;
  };

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>EntityPublicationVORowImpl</code> view object that
   ** allows use as a JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public EntityPublicationVORowImpl() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Accessor and Mutator methods
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEntityPublicationEO
  /**
   ** Returns the Application Instance entity object.
   **
   ** @return                    the EntityPublicationEO
   */
  public EntityPublicationEOImpl getEntityPublicationEO() {
    return (EntityPublicationEOImpl)getEntity(0);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setIdentifier
  /**
   ** Sets the attribute value for <code>PUBLICATIONID</code> using the alias
   ** name <code>publicationId</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>PUBLICATIONID</code> using the alias name
   **                            <code>publicationId</code>.
   **                            Allowed object is {@link String}.
   */
  public void setIdentifier(final String value) {
    setAttributeInternal(PUBLICATIONID, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getIdentifier
  /**
   ** Returns the attribute value for <code>PUBLICATIONID</code> using the alias
   ** name <code>publicationId</code>.
   **
   ** @return                    the attribute value for
   **                            <code>PUBLICATIONID</code> using the alias name
   **                            <code>publicationId</code>.
   **                            Possible object is {@link String}.
   */
  public String getIdentifier() {
    return (String)getAttributeInternal(PUBLICATIONID);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setEntityId
  /**
   ** Sets the attribute value for <code>ENTITYID</code> using the alias
   ** name <code>entityId</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>ENTITYID</code> using the alias name
   **                            <code>entityId</code>.
   **                            Allowed object is {@link Long}.
   */
  public void setEntityId(final Long value) {
    setAttributeInternal(ENTITYID, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEntityId
  /**
   ** Returns the attribute value for <code>ENTITYID</code> using the alias
   ** name <code>entityId</code>.
   **
   ** @return                    the attribute value for
   **                            <code>ENTITYID</code> using the alias name
   **                            <code>entityId</code>.
   **                            Possible object is {@link Long}.
   */
  public Long getEntityId() {
    return (Long)getAttributeInternal(ENTITYID);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setEntityType
  /**
   ** Sets the attribute value for <code>ENTITYTYPE</code> using the alias name
   ** <code>entityType</code>.
   **
   ** @param  value              the attribute value for <code>ENTITYTYPE</code>
   **                            using the alias name <code>entityType</code>.
   **                            Allowed object is {@link String}.
   */
  public void setEntityType(final String value) {
    setAttributeInternal(ENTITYTYPE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEntityType
  /**
   ** Returns the attribute value for <code>ENTITYTYPE</code> using the alias name
   ** <code>entityType</code>.
   **
   ** @return                    the attribute value for <code>ENTITYTYPE</code> using
   **                            the alias name <code>entityType</code>.
   **                            Possible object is {@link String}.
   */
  public String getEntityType() {
    return (String)getAttributeInternal(ENTITYTYPE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setScopeId
  /**
   ** Sets the attribute value for <code>SCOPEID</code> using the alias
   ** name <code>scopeId</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>SCOPEID</code> using the alias name
   **                            <code>scopeId</code>.
   **                            Allowed object is {@link Long}.
   */
  public void setScopeId(final String value) {
    setAttributeInternal(SCOPEID, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getScopeId
  /**
   ** Returns the attribute value for <code>SCOPEID</code> using the
   ** alias name <code>scopeId</code>.
   **
   ** @return                    the attribute value for
   **                            <code>SCOPEID</code> using the alias name
   **                            <code>scopeId</code>.
   **                            Possible object is {@link String}.
   */
  public String getScopeId() {
    return (String)getAttributeInternal(SCOPEID);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setScopeName
  /**
   ** Sets the attribute value for <code>SCOPENAME</code> using the alias
   ** name <code>scopeName</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>SCOPENAME</code> using the alias name
   **                            <code>scopeName</code>.
   **                            Allowed object is {@link String}.
   */
  public void setScopeName(final String value) {
    setAttributeInternal(SCOPENAME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getScopeName
  /**
   ** Returns the attribute value for <code>SCOPENAME</code> using the
   ** alias name <code>scopeName</code>.
   **
   ** @return                    the attribute value for
   **                            <code>SCOPENAME</code> using the alias name
   **                            <code>dynamicscope</code>.
   **                            Possible object is {@link String}.
   */
  public String getScopeName() {
    return (String)getAttributeInternal(SCOPENAME);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setScopeType
  /**
   ** Sets the attribute value for <code>SCOPETYPE</code> using the alias
   ** name <code>scopeType</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>SCOPETYPE</code> using the alias name
   **                            <code>scopeType</code>.
   **                            Allowed object is {@link String}.
   */
  public void setScopeType(final String value) {
    setAttributeInternal(SCOPETYPE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getScopeType
  /**
   ** Returns the attribute value for <code>SCOPETYPE</code> using the
   ** alias name <code>scopeType</code>.
   **
   ** @return                    the attribute value for
   **                            <code>SCOPETYPE</code> using the alias name
   **                            <code>dynamicscope</code>.
   **                            Possible object is {@link String}.
   */
  public String getScopeType() {
    return (String)getAttributeInternal(SCOPETYPE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setScopeStatus
  /**
   ** Sets the attribute value for <code>SCOPESTATUS</code> using the alias
   ** name <code>scopeStatus</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>SCOPESTATUS</code> using the alias name
   **                            <code>scopeStatus</code>.
   **                            Allowed object is {@link String}.
   */
  public void setScopeStatus(final String value) {
    setAttributeInternal(SCOPESTATUS, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getScopeStatus
  /**
   ** Returns the attribute value for <code>SCOPESTATUS</code> using the
   ** alias name <code>scopeStatus</code>.
   **
   ** @return                    the attribute value for
   **                            <code>SCOPESTATUS</code> using the alias name
   **                            <code>dynamicscope</code>.
   **                            Possible object is {@link String}.
   */
  public String getScopeStatus() {
    return (String)getAttributeInternal(SCOPESTATUS);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setHierarchicalScope
  /**
   ** Sets the attribute value for <code>HIERARCHICALSCOPE</code> using the
   ** alias name <code>hierarchicalScope</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>HIERARCHICALSCOPE</code> using the alias
   **                            name <code>hierarchicalScope</code>.
   **                            Allowed object is {@link Boolean}.
   */
  public void setHierarchicalScope(final Boolean value) {
    setAttributeInternal(HIERARCHICALSCOPE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getHierarchicalScope
  /**
   ** Returns the attribute value for <code>HIERARCHICALSCOPE</code> using the
   ** alias name <code>hierarchicalScope</code>.
   **
   ** @return                    the attribute value for
   **                            <code>HIERARCHICALSCOPE</code> using the alias
   **                            name <code>hierarchicalScope</code>.
   **                            Possible object is {@link Boolean}.
   */
  public Boolean getHierarchicalScope() {
    return (Boolean)getAttributeInternal(HIERARCHICALSCOPE);
  }
}