/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Authorization Management

    File        :   ReportVORowImpl.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    ReportVORowImpl.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysauthz.model.view;

import oracle.jbo.RowIterator;
import oracle.jbo.server.ViewRowImpl;

import oracle.iam.identity.sysauthz.model.entity.ReportEOImpl;

////////////////////////////////////////////////////////////////////////////////
// class ReportVORowImpl
// ~~~~~ ~~~~~~~~~~~~~~~
/**
 ** ---------------------------------------------------------------------
 ** --- File generated by Oracle ADF Business Components Design Time.
 ** --- Tue Mar 07 07:51:54 CET 2017
 ** --- Custom code may be added to this class.
 ** --- Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public class ReportVORowImpl extends ViewRowImpl {

  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  public static final int PATH        = AttributesEnum.path.ordinal();
  public static final int NAME        = AttributesEnum.name.ordinal();
  public static final int DESCRIPTION = AttributesEnum.description.ordinal();
  public static final int OWNER       = AttributesEnum.owner.ordinal();
  public static final int PARAMETER   = AttributesEnum.parameter.ordinal();

  //////////////////////////////////////////////////////////////////////////////
  // Member classes
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // class AttributesEnum
  /**
   ** AttributesEnum: generated enum for identifying attributes and accessors.
   ** Do not modify.
   */
  @SuppressWarnings({ "oracle.jbo.attribute-enumeration-classes-rule", "oracle.jbo.attribute-order-rule" })
  private static enum AttributesEnum {
      path
    , name
    , description
    , owner
    , parameter
    ;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor

  /**
   ** Constructs a <code>ReportVORowImpl</code> view object that allows use as a
   ** JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public ReportVORowImpl() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Accessor and Mutator methods
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getReportEO
  /**
   ** Returns the Report entity object.
   **
   ** @return                    the getReportEO
   */
  public ReportEOImpl getReportEO() {
    return (ReportEOImpl)getEntity(0);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getReportParameterVO
  /**
   ** Returns the associated <code>RowIterator</code> using master-detail link
   ** ReportParameterVO.
   **
   ** @return                    the ReportParameterVO RowIterator.
   */
  public RowIterator getReportParameterVO() {
    return (RowIterator)getAttributeInternal(PARAMETER);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setIdentifier
  /**
   ** Sets the attribute value for <code>NAME</code> using the alias name
   ** <code>path</code>.
   **
   ** @param  value              the attribute value for <code>NAME</code> using
   **                            the alias name <code>path</code>.
   **                            Allowed object is {@link String}.
   */
  public void setIdentifier(final String value) {
    setAttributeInternal(PATH, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getIdentifier
  /**
   ** Returns the attribute value for <code>PATH</code> using the alias name
   ** <code>path</code>.
   **
   ** @return                    the attribute value for <code>PATH</code> using
   **                            the alias name <code>path</code>.
   **                            Possible object is {@link String}.
   */
  public Long getIdentifier() {
    return (Long)getAttributeInternal(PATH);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setName
  /**
   ** Sets the attribute value for <code>NAME</code> using the alias name
   ** <code>name</code>.
   **
   ** @param  value              the attribute value for <code>NAME</code>
   **                            using the alias name <code>name</code>.
   **                            Allowed display is {@link String}.
   */
  public void setName(final String value) {
    setAttributeInternal(NAME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getName
  /**
   ** Returns the attribute value for <code>NAME</code> using the alias
   ** name <code>name</code>.
   **
   ** @return                    the attribute value for <code>NAME</code>
   **                            using the alias name <code>name</code>.
   **                            Possible display is {@link String}.
   */
  public String getName() {
    return (String)getAttributeInternal(NAME);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setDescription
  /**
   ** Sets the attribute value for <code>DESCRIPTION</code> using the alias name
   ** <code>description</code>.
   **
   ** @param  value              the attribute value for <code>DESCRIPTION</code>
   **                            using the alias name <code>description</code>.
   **                            Allowed display is {@link String}.
   */
  public void setDescription(final String value) {
    setAttributeInternal(DESCRIPTION, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getDescription
  /**
   ** Returns the attribute value for <code>DESCRIPTION</code> using the alias
   ** name <code>description</code>.
   **
   ** @return                    the attribute value for
   **                            <code>DESCRIPTION</code> using the alias name
   **                            <code>description</code>.
   **                            Possible display is {@link String}.
   */
  public String getDescription() {
    return (String)getAttributeInternal(DESCRIPTION);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setOwner
  /**
   ** Sets the attribute value for <code>OWNER</code> using the alias name
   ** <code>owner</code>.
   **
   ** @param  value              the attribute value for <code>OWNER</code>
   **                            using the alias name <code>owner</code>.
   **                            Allowed display is {@link String}.
   */
  public void setOwner(final String value) {
    setAttributeInternal(OWNER, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getOwner
  /**
   ** Returns the attribute value for <code>OWNER</code> using the alias
   ** name <code>owner</code>.
   **
   ** @return                    the attribute value for <code>OWNER</code>
   **                            using the alias name <code>owner</code>.
   **                            Possible display is {@link String}.
   */
  public String getOwner() {
    return (String)getAttributeInternal(OWNER);
  }
}