/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Authorization Management

    File        :   ReportParameterVORowImpl.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    ReportParameterVORowImpl.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysauthz.model.view;

import oracle.jbo.server.ViewRowImpl;

import oracle.iam.identity.sysauthz.model.entity.ReportParameterEOImpl;

////////////////////////////////////////////////////////////////////////////////
// class ReportParameterVORowImpl
// ~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~
/**
 ** ---------------------------------------------------------------------
 ** --- File generated by Oracle ADF Business Components Design Time.
 ** --- Tue Mar 07 07:51:54 CET 2017
 ** --- Custom code may be added to this class.
 ** --- Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public class ReportParameterVORowImpl extends ViewRowImpl {

  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  public static final int PATH         = AttributesEnum.path.ordinal();
  public static final int NAME         = AttributesEnum.name.ordinal();
  public static final int LABEL        = AttributesEnum.label.ordinal();
  public static final int DATATYPE     = AttributesEnum.dataType.ordinal();
  public static final int DEFAULTVALUE = AttributesEnum.defaultValue.ordinal();
  public static final int VALUE        = AttributesEnum.value.ordinal();

  //////////////////////////////////////////////////////////////////////////////
  // Member classes
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // class AttributesEnum
  /**
   ** AttributesEnum: generated enum for identifying attributes and accessors.
   ** Do not modify.
   */
  @SuppressWarnings({ "oracle.jbo.attribute-enumeration-classes-rule", "oracle.jbo.attribute-order-rule" })
  private static enum AttributesEnum {
      path
    , name
    , label
    , dataType
    , defaultValue
    , value
    ;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>ReportParameterVORowImpl</code> view object that allows
   ** use as a JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public ReportParameterVORowImpl() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Accessor and Mutator methods
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getReportParameterEO
  /**
   ** Returns the Report entity object.
   **
   ** @return                    the getReportEO
   */
  public ReportParameterEOImpl getReportParameterEO() {
    return (ReportParameterEOImpl)getEntity(0);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setPath
  /**
   ** Sets the attribute value for <code>PATH</code> using the alias name
   ** <code>path</code>.
   **
   ** @param  value              the attribute value for <code>PATH</code>
   **                            using the alias name <code>path</code>.
   **                            Allowed object is {@link String}.
   */
  public void setPath(final String value) {
    setAttributeInternal(PATH, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setPath
  /**
   ** Returns the attribute value for <code>PATH</code> using the alias name
   ** <code>report</code>.
   **
   ** @return                    the attribute value for <code>PATH</code>
   **                            using the alias name <code>path</code>.
   **                            Possible object is {@link String}.
   */
  public String getreport() {
    return (String)getAttributeInternal(PATH);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setName
  /**
   ** Sets the attribute value for <code>NAME</code> using the alias name
   ** <code>name</code>.
   **
   ** @param  value              the attribute value for <code>NAME</code> using
   **                            the alias name <code>name</code>.
   **                            Allowed object is {@link Long}.
   */
  public void setName(final Long value) {
    setAttributeInternal(NAME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getName
  /**
   ** Returns the attribute value for <code>NAME</code> using the alias name
   ** <code>name</code>.
   **
   ** @return                    the attribute value for <code>NAME</code> using
   **                            the alias name <code>name</code>.
   **                            Possible object is {@link Long}.
   */
  public Long getName() {
    return (Long)getAttributeInternal(NAME);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setLabel
  /**
   ** Sets the attribute value for <code>LABEL</code> using the alias name
   ** <code>label</code>.
   **
   ** @param  value              the attribute value for <code>LABEL</code>
   **                            using the alias name <code>label</code>.
   **                            Allowed display is {@link String}.
   */
  public void setLabel(final String value) {
    setAttributeInternal(LABEL, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getLabel
  /**
   ** Returns the attribute value for <code>LABEL</code> using the alias name
   ** <code>label</code>.
   **
   ** @return                    the attribute value for <code>LABEL</code>
   **                            using the alias name <code>label</code>.
   **                            Possible display is {@link String}.
   */
  public String getLabel() {
    return (String)getAttributeInternal(LABEL);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setDataType
  /**
   ** Sets the attribute value for <code>DATATYPE</code> using the alias name
   ** <code>dataType</code>.
   **
   ** @param  value              the attribute value for <code>DATATYPE</code>
   **                            using the alias name <code>dataType</code>.
   **                            Allowed object is {@link String}.
   */
  public void setDataType(final String value) {
    setAttributeInternal(DATATYPE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getDataType
  /**
   ** Returns the attribute value for <code>DATATYPE</code> using the alias name
   ** <code>dataType</code>.
   **
   ** @return                    the attribute value for <code>DATATYPE</code>
   **                            using the alias name <code>dataType</code>.
   **                            Possible object is {@link String}.
   */
  public Long getDataType() {
    return (Long)getAttributeInternal(DATATYPE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setDefaultValue
  /**
   ** Sets the attribute value for <code>DEFAULTVALUE</code> using the alias
   ** name <code>defualtValue</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>DEFAULTVALUE</code> using the alias name
   **                            <code>defualtValue</code>.
   **                            Allowed display is {@link String}.
   */
  public void setDefaultValue(final String value) {
    setAttributeInternal(DEFAULTVALUE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getDefaultValue
  /**
   ** Returns the attribute value for <code>DEFAULTVALUE</code> using the alias
   ** name <code>defualtValue</code>.
   **
   ** @return                    the attribute value for
   **                            <code>DEFAULTVALUE</code> using the alias name
   **                            <code>defualtValue</code>.
   **                            Possible display is {@link String}.
   */
  public String getDefaultValue() {
    return (String)getAttributeInternal(DEFAULTVALUE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setValue
  /**
   ** Sets the attribute value for <code>VALUE</code> using the alias name
   ** <code>value</code>.
   **
   ** @param  value              the attribute value for <code>VALUE</code>
   **                            using the alias name <code>value</code>.
   **                            Allowed object is {@link String}.
   */
  public void setValue(final String value) {
    setAttributeInternal(VALUE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getValue
  /**
   ** Returns the attribute value for <code>VALUE</code> using the alias name
   ** <code>value</code>.
   **
   ** @return                    the attribute value for <code>VALUE</code>
   **                            using the alias name <code>value</code>.
   **                            Possible object is {@link String}.
   */
  public String getValue() {
    return (String)getAttributeInternal(VALUE);
  }
}