/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2020. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Employee Self Service Portal
    Subsystem   :   Common Backend Model Component

    File        :   PortalViewObjectImpl.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    PortalViewObjectImpl.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    1.0.0.0     2020-02-23  DSteding    First release version
*/

package bka.employee.portal.model;

import oracle.jbo.Row;
import oracle.jbo.Key;

import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.TransactionEvent;

import bka.employee.portal.model.common.PortalViewObject;

////////////////////////////////////////////////////////////////////////////////
// class PortalViewObjectImpl
// ~~~~~ ~~~~~~~~~~~~~~~~~~~~
/**
 ** The <code>View Object</code> to coordinate database queries and the view
 ** rows that result from executing queries belonging to
 ** <code>Employee Self Service Portal</code>s.
 ** <p>
 ** A <code>View Object</code> manages a view row set (ViewRowSetImpl). When the
 ** application calls a RowSet method on a <code>View Object</code>, the call is
 ** delegated to the its view row set, which performs the actual operation.
 ** <p>
 ** A <code>View Object</code>'s base definition is provided by a View
 ** Definition object, which is built from the meta-data stored in an XML file.
 ** <br>
 ** The <code>View Object</code> inherits many of its definitions from its View
 ** Definition, but applications can override them in instances.
 ** <p>
 ** A <code>View Object</code> persists until it, or the
 ** <code>Application Module</code> from which it was created, is explicitly
 ** deleted (using remove methods). You can use a given <code>View Object</code>
 ** definition more than once within an <code>Application Module</code>; the
 ** Business Component framework uses View instance names to distinguish between
 ** them.
 ** ---------------------------------------------------------------------
 ** --- File generated by Oracle ADF Business Components Design Time.
 ** --- Mon Jun 11 20:43:53 CEST 2018
 ** --- Custom code may be added to this class.
 ** --- Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 **
 ** @author  dieter.steding@oracle.com
 ** @version 1.0.0.0
 ** @since   1.0.0.0
 */
public class PortalViewObjectImpl extends    ViewObjectImpl
                                  implements PortalViewObject {

  //////////////////////////////////////////////////////////////////////////////
  // instance attributes
  //////////////////////////////////////////////////////////////////////////////

  private Key current;
  private int range;

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>PortalViewObjectImpl</code> view object that allows use
   ** as a JavaBean.
   ** <br>
   ** Zero argumment constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public PortalViewObjectImpl() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methods of implemented interfaces
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   refreshCurrentRow (PortalViewObject)
  /**
   ** Handles events raised to refresh the current row only.
   **
   ** @param  row                the {@link Row} to refresh.
   */
  @Override
  public void refreshCurrentRow(final Row row) {
    if (row != null)
      row.refresh(Row.REFRESH_UNDO_CHANGES | Row.REFRESH_WITH_DB_FORGET_CHANGES);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methods grouped by functionality
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   beforeRollback (overridden)
  /**
   ** Handles events raised before a transaction is rolled back.
   **
   ** @param  event              the transaction event.
   */
  @Override
  public void beforeRollback(final TransactionEvent event) {
    if (this.isExecuted()) {
      final ViewRowImpl cursor = (ViewRowImpl)getCurrentRow();
      if (cursor != null) {
        byte newRowState = cursor.getNewRowState();
        if (newRowState != Row.STATUS_INITIALIZED && newRowState != Row.STATUS_NEW) {
          this.current = cursor.getKey();
          this.range   = getRangeIndexOf(cursor);
        }
      }
    }
    // ensure inheritance
    super.beforeRollback(event);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   afterRollback (overridden)
  /**
   ** Handles events raised after a transaction has been rolled back.
   ** <br>
   ** All row sets that belong to this View Object are refreshed.
   **
   ** @param  event               the transaction event.
   */
  @Override
  public void afterRollback(final TransactionEvent event) {
    // ensure inheritance
    super.afterRollback(event);
    if (this.current != null) {
      this.executeQuery();
      final Key   k = new Key(this.current.getAttributeValues());
      final Row[] f = this.findByKey(k, 1);
      if (f != null && f.length == 1) {
        final Row r = this.getRow(k);
        setCurrentRow(r);
        if (this.range >= 0) {
          scrollRangeTo(r, this.range);
        }
      }
    }
    this.current = null;
  }
}