/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Provisioning Management

    File        :   ResourceObjectAM.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the interface
                    ResourceObjectAM.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysprov.module.common;

import oracle.jbo.ApplicationModule;

////////////////////////////////////////////////////////////////////////////////
// class ResourceObjectAM
// ~~~~~ ~~~~~~~~~~~~~~~~
/**
 ** The <code>Application Module</code> to coordinate the particular task
 ** belonging to <code>Resource Object</code>s.
 ** <p>
 ** ---------------------------------------------------------------------
 ** ---    File generated by Oracle ADF Business Components Design Time.
 ** ---    Mon Mar 20 14:49:55 CET 2017
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public interface ResourceObjectAM extends ApplicationModule {

  //////////////////////////////////////////////////////////////////////////////
  // Methods grouped by functionality
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchByIdentifier
  /**
   ** Finds a certain <code>Resource Object</code> by executing a query against
   ** the persistence layer which leverage the primary key of the entity object.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Resource Object</code> to fetch from the
   **                            persistence layer.
   */
  void fetchByIdentifier(final String identifier);

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchByName
  /**
   ** Finds a certain <code>Resource Object</code> by executing a query against
   ** the persistence layer which leverage the unique key of the entity object.
   **
   ** @param  name               the unique identifier of the
   **                            <code>Resource Object</code> to fetch from the
   **                            persistence layer.
   */
  void fetchByName(final String name);

  //////////////////////////////////////////////////////////////////////////////
  // Method:   createDetail
  /**
   ** Initialize the model to create a new <code>Resource Object</code>.
   */
  void createDetail();

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchDetail
  /**
   ** Initialize the model to maintain an existing <code>Resource Object</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Resource Object</code> to fetch from the
   **                            persistence layer.
   **                            Allowed object is {@link String}.
   */
  void fetchDetail(final String identifier);

  //////////////////////////////////////////////////////////////////////////////
  // Method:   refreshAttribute
  /**
   ** Refresh the attributes belonging to a certain
   ** <code>Resource Object</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Resource Object</code> to initialize.
   **                            Allowed object is {@link String}.
   */
  void refreshAttribute(final String identifier);

  //////////////////////////////////////////////////////////////////////////////
  // Method:   refreshReconciliation
  /**
   ** Refresh the reconciliation belonging to a certain
   ** <code>Resource Object</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Resource Object</code> to initialize.
   **                            Allowed object is {@link String}.
   */
  void refreshReconciliation(final String identifier);

  //////////////////////////////////////////////////////////////////////////////
  // Method:   refreshAdministrator
  /**
   ** Refresh the administrators belonging to a certain
   ** <code>Resource Object</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Resource Object</code> to initialize.
   **                            Allowed object is {@link String}.
   */
  void refreshAdministrator(final String identifier);

  //////////////////////////////////////////////////////////////////////////////
  // Method:   refreshAccount
  /**
   ** Refresh the accounts belonging to a certain <code>Resource Object</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Resource Object</code> to initialize.
   **                            Allowed object is {@link String}.
   */
  void refreshAccount(final String identifier);
}