/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Administration Management

    File        :   JobHistoryVORowImpl.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    JobHistoryVORowImpl.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysadmin.model.view;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;

////////////////////////////////////////////////////////////////////////////////
// class JobHistoryVORowImpl
// ~~~~~ ~~~~~~~~~~~~~~~~~~~
/**
 ** ---------------------------------------------------------------------
 ** --- File generated by Oracle ADF Business Components Design Time.
 ** --- Tue Mar 07 07:51:54 CET 2017
 ** --- Custom code may be added to this class.
 ** --- Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public class JobHistoryVORowImpl extends ViewRowImpl {

  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  public static final int HISTORYID    = AttributesEnum.historyId.ordinal();
  public static final int JOBNAME      = AttributesEnum.jobName.ordinal();
  public static final int NAME         = AttributesEnum.name.ordinal();
  public static final int INFOTYPE     = AttributesEnum.infoType.ordinal();
  public static final int STATUS       = AttributesEnum.status.ordinal();
  public static final int STATUSDECODE = AttributesEnum.statusDecode.ordinal();
  public static final int CUSTOMSTATUS = AttributesEnum.customStatus.ordinal();
  public static final int STARTTIME    = AttributesEnum.startTime.ordinal();
  public static final int ENDTIME      = AttributesEnum.endTime.ordinal();
  public static final int EXCEPTION    = AttributesEnum.exception.ordinal();

  //////////////////////////////////////////////////////////////////////////////
  // Member classes
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // class AttributesEnum
  /**
   ** AttributesEnum: generated enum for identifying attributes and accessors.
   ** Do not modify.
   */
  @SuppressWarnings("oracle.jbo.attribute-order-rule")
  private static enum AttributesEnum {
      historyId
    , jobName
    , name
    , infoType
    , status
    , statusDecode
    , customStatus
    , startTime
    , endTime
    , exception
    ;
  };

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>JobHistoryVORowImpl</code> view object that allows use
   ** as a JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public JobHistoryVORowImpl() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Accessor and Mutator methods
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setHistoryId
  /**
   ** Sets the attribute value for <code>HISTORYID</code> using the alias name
   ** <code>historyId</code>.
   **
   ** @param  value              the attribute value for <code>HISTORYID</code>
   **                            using the alias name <code>historyId</code>.
   **                            Allowed object is {@link Double}.
   */
  public void setHistoryId(final Double value) {
    setAttributeInternal(HISTORYID, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getHistoryId
  /**
   ** Returns the attribute value for <code>HISTORYID</code> using the alias
   ** name <code>historyId</code>.
   **
   ** @return                    the attribute value for <code>HISTORYID</code>
   **                            using the alias name <code>historyId</code>.
   **                            Possible object is {@link Double}.
   */
  public Double getHistoryId() {
    return (Double)getAttributeInternal(HISTORYID);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setJobName
  /**
   ** Sets the attribute value for <code>JOBNAME</code> using the alias name
   ** <code>jobName</code>.
   **
   ** @param  value              the attribute value for <code>JOBNAME</code>
   **                            using the alias name <code>jobName</code>.
   **                            Allowed object is {@link String}.
   */
  public void setJobName(final String value) {
    setAttributeInternal(JOBNAME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getJobName
  /**
   ** Returns the attribute value for <code>JOBNAME</code> using the alias
   ** name <code>jobName</code>.
   **
   ** @return                    the attribute value for <code>JOBNAME</code>
   **                            using the alias name <code>jobName</code>.
   **                            Possible object is {@link String}.
   */
  public String getJobName() {
    return (String)getAttributeInternal(JOBNAME);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setName
  /**
   ** Sets the attribute value for <code>NAME</code> using the alias name
   ** <code>name</code>.
   **
   ** @param  value              the attribute value for <code>NAME</code> using
                                 the alias name <code>name</code>.
   **                            Allowed object is {@link String}.
   */
  public void setName(final String value) {
    setAttributeInternal(NAME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getName
  /**
   ** Returns the attribute value for <code>NAME</code> using the alias
   ** name <code>name</code>.
   **
   ** @return                    the attribute value for <code>NAME</code> using
                                 the alias name <code>name</code>.
   **                            Possible object is {@link String}.
   */
  public String getName() {
    return (String)getAttributeInternal(NAME);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setInfoType
  /**
   ** Sets the attribute value for <code>INFOTYPE</code> using the alias name
   ** <code>infoType</code>.
   **
   ** @param  value              the attribute value for <code>INFOTYPE</code>
   **                            using the alias name <code>infoType</code>.
   **                            Allowed endpoint is {@link String}.
   */
  public void setInfoType(final String value) {
    setAttributeInternal(INFOTYPE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getInfoType
  /**
   ** Returns the attribute value for <code>INFOTYPE</code> using the alias
   ** name <code>infoType</code>.
   **
   ** @return                    the attribute value for <code>INFOTYPE</code>
   **                            using the alias name <code>infoType</code>.
   **                            Possible endpoint is {@link String}.
   */
  public String getInfoType() {
    return (String)getAttributeInternal(INFOTYPE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setStatus
  /**
   ** Sets the attribute value for <code>STATUS</code> using the alias name
   ** <code>status</code>.
   **
   ** @param  value              the attribute value for <code>STATUS</code>
   **                            using the alias name <code>status</code>.
   **                            Allowed display is {@link String}.
   */
  public void setStatus(final String value) {
    setAttributeInternal(STATUS, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getStatus
  /**
   ** Returns the attribute value for <code>STATUS</code> using the alias
   ** name <code>status</code>.
   **
   ** @return                    the attribute value for <code>STATUS</code>
   **                            using the alias name <code>status</code>.
   **                            Possible display is {@link String}.
   */
  public String getStatus() {
    return (String)getAttributeInternal(STATUS);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setStatusDecode
  /**
   ** Sets the attribute value for <code>STATUSDECODE</code> using the alias
   ** name <code>statusDecode</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>STATUSDECODE</code> using the
   **                            alias name <code>statusDecode</code>.
   **                            Allowed object is {@link String}.
   */
  public void setStatusDecode(final String value) {
    setAttributeInternal(STATUSDECODE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getStatusDecode
  /**
   ** Returns the attribute value for <code>STATUSDECODE</code> using
   ** the alias name <code>statusDecode</code>.
   **
   ** @return                    the attribute value for
   **                            <code>STATUSDECODE</code> using the
   **                            alias name <code>statusDecode</code>.
   **                            Possible object is {@link String}.
   */
  public String getStatusDecode() {
    return (String)getAttributeInternal(STATUSDECODE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setCustomStatus
  /**
   ** Sets the attribute value for <code>CUSTOMSTATUS</code> using the alias
   ** name <code>customStatus</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>CUSTOMSTATUS</code> using the alias name
   **                            <code>customStatus</code>.
   **                            Allowed object is {@link String}.
   */
  public void setCustomStatus(final String value) {
    setAttributeInternal(CUSTOMSTATUS, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getCustomStatus
  /**
   ** Returns the attribute value for <code>CUSTOMSTATUS</code> using the alias
   ** name <code>customStatus</code>.
   **
   ** @return                    the attribute value for
   **                            <code>CUSTOMSTATUS</code> using the alias name
   **                            <code>customStatus</code>.
   **                            Possible object is {@link String}.
   */
  public String getCustomStatus() {
    return (String)getAttributeInternal(CUSTOMSTATUS);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setStartTime
  /**
   ** Sets the attribute value for <code>STARTTIME</code> using the alias name
   ** <code>startTime</code>.
   **
   ** @param  value              the attribute value for <code>STARTTIME</code>
   **                            using the alias name <code>startTime</code>.
   **                            Allowed object is {@link Timestamp}.
   */
  public void setStartTime(final Timestamp value) {
    setAttributeInternal(STARTTIME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getStartTime
  /**
   ** Returns the attribute value for <code>STARTTIME</code> using the alias
   ** name <code>startTime</code>.
   **
   ** @return                    the attribute value for <code>STARTTIME</code>
   **                            using the alias name <code>startTime</code>.
   **                            Possible object is {@link Timestamp}.
   */
  public Timestamp getStartTime() {
    return (Timestamp)getAttributeInternal(STARTTIME);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setEndTime
  /**
   ** Sets the attribute value for <code>ENDTIME</code> using the alias name
   ** <code>endTime</code>.
   **
   ** @param  value              the attribute value for <code>ENDTIME</code>
   **                            using the alias name <code>endTime</code>.
   **                            Allowed object is {@link Timestamp}.
   */
  public void setEndTime(final Timestamp value) {
    setAttributeInternal(ENDTIME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEndTime
  /**
   ** Returns the attribute value for <code>ENDTIME</code> using the alias
   ** name <code>endTime</code>.
   **
   ** @return                    the attribute value for <code>ENDTIME</code>
   **                            using the alias name <code>endTime</code>.
   **                            Possible object is {@link Timestamp}.
   */
  public Timestamp getEndTime() {
    return (Timestamp)getAttributeInternal(ENDTIME);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setException
  /**
   ** Sets the attribute value for <code>EXCEPTION</code> using the alias name
   ** <code>exception</code>.
   **
   ** @param  value              the attribute value for <code>EXCEPTION</code>
   **                            using the alias name <code>exception</code>.
   **                            Allowed object is {@link Exception}.
   */
  public void setException(final Exception value) {
    setAttributeInternal(EXCEPTION, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getException
  /**
   ** Returns the attribute value for <code>EXCEPTION</code> using the alias
   ** name <code>exception</code>.
   **
   ** @return                    the attribute value for <code>EXCEPTION</code>
   **                            using the alias name <code>exception</code>.
   **                            Possible object is {@link Exception}.
   */
  public Exception getException() {
    return (Exception)getAttributeInternal(EXCEPTION);
  }
}