/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Administration Management

    File        :   JobParameterVORowImpl.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    JobParameterVORowImpl.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysadmin.model.view;

import oracle.jbo.server.ViewRowImpl;

////////////////////////////////////////////////////////////////////////////////
// class JobParameterVORowImpl
// ~~~~~ ~~~~~~~~~~~~~~~~~~~~~
/**
 ** ---------------------------------------------------------------------
 ** --- File generated by Oracle ADF Business Components Design Time.
 ** --- Tue Mar 07 07:51:54 CET 2017
 ** --- Custom code may be added to this class.
 ** --- Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public class JobParameterVORowImpl extends ViewRowImpl {

  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  public static final int PARAMETERKEY  = AttributesEnum.parameterKey.ordinal();
  public static final int JOBNAME       = AttributesEnum.jobName.ordinal();
  public static final int TASK          = AttributesEnum.task.ordinal();
  public static final int NAME          = AttributesEnum.name.ordinal();
  public static final int DATATYPE      = AttributesEnum.dataType.ordinal();
  public static final int VALUE         = AttributesEnum.value.ordinal();
  public static final int REQUIRED      = AttributesEnum.required.ordinal();
  public static final int ENCRYPTED     = AttributesEnum.encrypted.ordinal();
  public static final int HELPTEXT      = AttributesEnum.helpText.ordinal();
  public static final int PENDINGACTION = AttributesEnum.pendingAction.ordinal();
  public static final int MOD           = AttributesEnum.mod.ordinal();

  //////////////////////////////////////////////////////////////////////////////
  // Member classes
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // class AttributesEnum
  /**
   ** AttributesEnum: generated enum for identifying attributes and accessors.
   ** Do not modify.
   */
  @SuppressWarnings("oracle.jbo.attribute-order-rule")
  private static enum AttributesEnum {
      parameterKey
    , jobName
    , task
    , name
    , dataType
    , value
    , required
    , encrypted
    , helpText
    , pendingAction
    , mod
    ;
  };

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>JobParameterVORowImpl</code> view object that allows
   ** use as a JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public JobParameterVORowImpl() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Accessor and Mutator methods
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setParameterKey
  /**
   ** Sets the attribute value for <code>PARAMETERKEY</code> using the alias
   ** name <code>parameterKey</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>PARAMETERKEY</code> using the alias name
   **                            <code>parameterKey</code>.
   **                            Allowed object is {@link String}.
   */
  public void setParameterKey(final String value) {
    setAttributeInternal(PARAMETERKEY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getParameterKey
  /**
   ** Returns the attribute value for <code>PARAMETERKEY</code> using the alias
   ** name <code>parameterKey</code>.
   **
   ** @return                    the attribute value for
   **                            <code>PARAMETERKEY</code> using the alias name
   **                            <code>parameterKey</code>.
   **                            Possible object is {@link String}.
   */
  public String getParameterKey() {
    return (String)getAttributeInternal(PARAMETERKEY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setJobName
  /**
   ** Sets the attribute value for <code>JOBNAME</code> using the alias name
   ** <code>jobName</code>.
   **
   ** @param  value              the attribute value for <code>JOBNAME</code>
   **                            using the alias name <code>jobName</code>.
   **                            Allowed object is {@link String}.
   */
  public void setJobName(final String value) {
    setAttributeInternal(JOBNAME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getJobName
  /**
   ** Returns the attribute value for <code>JOBNAME</code> using the alias
   ** name <code>jobName</code>.
   **
   ** @return                    the attribute value for <code>JOBNAME</code>
   **                            using the alias name <code>jobName</code>.
   **                            Possible object is {@link String}.
   */
  public String getJobName() {
    return (String)getAttributeInternal(JOBNAME);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setTask
  /**
   ** Sets the attribute value for <code>TASK</code> using the alias name
   ** <code>task</code>.
   **
   ** @param  value              the attribute value for <code>TASK</code> using
   **                            the alias name <code>task</code>.
   **                            Allowed endpoint is {@link String}.
   */
  public void setTask(final String value) {
    setAttributeInternal(TASK, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getTask
  /**
   ** Returns the attribute value for <code>TASK</code> using the alias
   ** name <code>task</code>.
   **
   ** @return                    the attribute value for <code>TASK</code> using
   **                            the alias name <code>task</code>.
   **                            Possible endpoint is {@link String}.
   */
  public String getTask() {
    return (String)getAttributeInternal(TASK);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setName
  /**
   ** Sets the attribute value for <code>NAME</code> using the alias name
   ** <code>name</code>.
   **
   ** @param  value              the attribute value for <code>NAME</code> using
                                 the alias name <code>name</code>.
   **                            Allowed object is {@link String}.
   */
  public void setName(final String value) {
    setAttributeInternal(NAME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getName
  /**
   ** Returns the attribute value for <code>NAME</code> using the alias
   ** name <code>name</code>.
   **
   ** @return                    the attribute value for <code>NAME</code> using
                                 the alias name <code>name</code>.
   **                            Possible object is {@link String}.
   */
  public String getName() {
    return (String)getAttributeInternal(NAME);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setDataType
  /**
   ** Sets the attribute value for <code>DATATYPE</code> using the alias name
   ** <code>dataType</code>.
   **
   ** @param  value              the attribute value for <code>DATATYPE</code>
   **                            using the alias name <code>dataType</code>.
   **                            Allowed endpoint is {@link String}.
   */
  public void setDataType(final String value) {
    setAttributeInternal(DATATYPE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getDataType
  /**
   ** Returns the attribute value for <code>DATATYPE</code> using the alias
   ** name <code>dataType</code>.
   **
   ** @return                    the attribute value for <code>DATATYPE</code>
   **                            using the alias name <code>dataType</code>.
   **                            Possible endpoint is {@link String}.
   */
  public String getDataType() {
    return (String)getAttributeInternal(DATATYPE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setValue
  /**
   ** Sets the attribute value for <code>VALUE</code> using the alias name
   ** <code>value</code>.
   **
   ** @param  value              the attribute value for <code>VALUE</code>
   **                            using the alias name <code>value</code>.
   **                            Allowed display is {@link String}.
   */
  public void setValue(final String value) {
    setAttributeInternal(VALUE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getValue
  /**
   ** Returns the attribute value for <code>VALUE</code> using the alias
   ** name <code>value</code>.
   **
   ** @return                    the attribute value for <code>VALUE</code>
   **                            using the alias name <code>value</code>.
   **                            Possible display is {@link String}.
   */
  public String getValue() {
    return (String)getAttributeInternal(VALUE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setRequired
  /**
   ** Sets the attribute value for <code>REQUIRED</code> using the alias name
   ** <code>required</code>.
   **
   ** @param  value              the attribute value for <code>REQUIRED</code>
   **                            using the alias name <code>required</code>.
   **                            Allowed object is {@link Boolean}.
   */
  public void setRequired(final Boolean value) {
    setAttributeInternal(REQUIRED, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getRequired
  /**
   ** Returns the attribute value for <code>REQUIRED</code> using the alias name
   ** <code>required</code>.
   **
   ** @return                    the attribute value for <code>REQUIRED</code>
   **                            using the alias name <code>required</code>.
   **                            Possible object is {@link Boolean}.
   */
  public Boolean getRequired() {
    return (Boolean)getAttributeInternal(REQUIRED);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setEncrypted
  /**
   ** Sets the attribute value for <code>ENCRYPTED</code> using the alias name
   ** <code>encrypted</code>.
   **
   ** @param  value              the attribute value for <code>ENCRYPTED</code>
   **                            using the alias name <code>encrypted</code>.
   **                            Allowed object is {@link Boolean}.
   */
  public void setEncrypted(final Boolean value) {
    setAttributeInternal(ENCRYPTED, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEncrypted
  /**
   ** Returns the attribute value for <code>ENCRYPTED</code> using the alias
   ** name <code>encrypted</code>.
   **
   ** @return                    the attribute value for <code>ENCRYPTED</code>
   **                            using the alias name <code>encrypted</code>.
   **                            Possible object is {@link Boolean}.
   */
  public Boolean getEncrypted() {
    return (Boolean)getAttributeInternal(ENCRYPTED);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setHelpText
  /**
   ** Sets the attribute value for <code>HELPTEXT</code> using the alias name
   ** <code>helpText</code>.
   **
   ** @param  value              the attribute value for <code>HELPTEXT</code>
   **                            using the alias name <code>helpText</code>.
   **                            Allowed object is {@link String}.
   */
  public void setHelpText(final String value) {
    setAttributeInternal(HELPTEXT, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getHelpText
  /**
   ** Returns the attribute value for <code>HELPTEXT</code> using the alias
   ** name <code>helpText</code>.
   **
   ** @return                    the attribute value for <code>HELPTEXT</code>
   **                            using the alias name <code>helpText</code>.
   **                            Possible object is {@link String}.
   */
  public String getHelpText() {
    return (String)getAttributeInternal(HELPTEXT);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setPendingAction
  /**
   ** Sets the attribute value for <code>PENDINGACTION</code> using the alias
   ** name <code>pendingAction</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>PENDINGACTION</code> using the alias name
   **                            <code>pendingAction</code>.
   **                            Allowed object is {@link String}.
   */
  public void setPendingAction(final String value) {
    setAttributeInternal(PENDINGACTION, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getPendingAction
  /**
   ** Returns the attribute value for <code>PENDINGACTION</code> using the alias
   ** name <code>pendingAction</code>.
   **
   ** @return                    the attribute value for
   **                            <code>PENDINGACTION</code> using the alias name
   **                            <code>pendingAction</code>.
   **                            Possible object is {@link String}.
   */
  public String getPendingAction() {
    return (String)getAttributeInternal(PENDINGACTION);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setMod
  /**
   ** Sets the attribute value for <code>MOD</code> using the alias name
   ** <code>mod</code>.
   **
   ** @param  value              the attribute value for <code>MOD</code> using
   **                            the alias name <code>mod</code>.
   **                            Allowed object is {@link String}.
   */
  public void setMod(final String value) {
    setAttributeInternal(MOD, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getMod
  /**
   ** Returns the attribute value for <code>MOD</code> using the alias name
   ** <code>mod</code>.
   **
   ** @return                    the attribute value for <code>MOD</code> using
   **                            the alias name <code>mod</code>.
   **                            Possible object is {@link String}.
   */
  public String getMod() {
    return (String)getAttributeInternal(MOD);
  }
}