/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Administration Management

    File        :   OrchestrationProcessVORowImpl.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    OrchestrationProcessVORowImpl.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysadmin.model.view;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;

import oracle.iam.identity.sysadmin.model.entity.OrchestrationProcessEOImpl;

////////////////////////////////////////////////////////////////////////////////
// class OrchestrationProcessVORowImpl
// ~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/**
 ** ---------------------------------------------------------------------
 ** --- File generated by Oracle ADF Business Components Design Time.
 ** --- Tue Mar 07 07:51:54 CET 2017
 ** --- Custom code may be added to this class.
 ** --- Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public class OrchestrationProcessVORowImpl extends ViewRowImpl {

  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  public static final int PROCESSID       = AttributesEnum.processId.ordinal();
  public static final int PROCESSNAME     = AttributesEnum.processName.ordinal();
  public static final int BULKPARENTID    = AttributesEnum.bulkParentId.ordinal();
  public static final int STATUS          = AttributesEnum.status.ordinal();
  public static final int PARENTID        = AttributesEnum.parentId.ordinal();
  public static final int DEPENDENDID     = AttributesEnum.dependendId.ordinal();
  public static final int ENTITYID        = AttributesEnum.entityId.ordinal();
  public static final int ENTITYTYPE      = AttributesEnum.entityType.ordinal();
  public static final int OUTOFBANDEVENTS = AttributesEnum.outOfBandEvents.ordinal();
  public static final int OPERATION       = AttributesEnum.operation.ordinal();
  public static final int STAGE           = AttributesEnum.stage.ordinal();
  public static final int CHANGETYPE      = AttributesEnum.changeType.ordinal();
  public static final int RETRY           = AttributesEnum.retry.ordinal();
  public static final int CREATEDON       = AttributesEnum.createdOn.ordinal();
  public static final int MODIFIEDON      = AttributesEnum.modifiedOn.ordinal();

  //////////////////////////////////////////////////////////////////////////////
  // Member classes
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // class AttributesEnum
  public static final int ENTITY_ORCHESTRATIONPROCESSEO = 0;

  /**
   ** AttributesEnum: generated enum for identifying attributes and accessors.
   ** Do not modify.
   */
  @SuppressWarnings({ "oracle.jbo.attribute-enumeration-classes-rule", "oracle.jbo.attribute-order-rule" })
  private static enum AttributesEnum {
      processId
    , processName
    , bulkParentId
    , status
    , parentId
    , dependendId
    , entityId
    , entityType
    , outOfBandEvents
    , operation
    , stage
    , changeType
    , retry
    , createdOn
    , modifiedOn
    ;
  };

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>OrchestrationProcessVORowImpl</code> view object that
   ** allows use as a JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public OrchestrationProcessVORowImpl() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Accessor and Mutator methods
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getOrchestrationProcessEO
  /**
   ** Returns the Orchestration Process entity object.
   **
   ** @return                    the OrchestrationProcessEO
   */
  public OrchestrationProcessEOImpl getOrchestrationProcessEO() {
    return (OrchestrationProcessEOImpl)getEntity(0);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setIdentifier
  /**
   ** Sets the attribute value for <code>PROCESSID</code> using the alias name
   ** <code>processId</code>.
   **
   ** @param  value              the attribute value for <code>PROCESSID</code>
   **                            using the alias name <code>processId</code>.
   **                            Allowed object is {@link Long}.
   */
  public void setIdentifier(final Long value) {
    setAttributeInternal(PROCESSID, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getIdentifier
  /**
   ** Returns the attribute value for <code>PROCESSID</code> using the alias
   ** name <code>processId</code>.
   **
   ** @return                    the attribute value for <code>PROCESSID</code>
   **                            using the alias name <code>processId</code>.
   **                            Possible object is {@link Long}.
   */
  public Long getIdentifier() {
    return (Long)getAttributeInternal(PROCESSID);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setProcessName
  /**
   ** Sets the attribute value for <code>PROCESSNAME</code> using the alias name
   ** <code>processName</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>PROCESSNAME</code> using the alias name
   **                            <code>processName</code>.
   **                            Allowed object is {@link String}.
   */
  public void setProcessName(final String value) {
    setAttributeInternal(PROCESSNAME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getProcessName
  /**
   ** Returns the attribute value for <code>PROCESSNAME</code> using the alias
   ** name <code>processName</code>.
   **
   ** @return                    the attribute value for
   **                            <code>PROCESSNAME</code> using the alias name
   **                            <code>processName</code>.
   **                            Possible object is {@link String}.
   */
  public String getProcessName() {
    return (String)getAttributeInternal(PROCESSNAME);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setBulkParentId
  /**
   ** Sets the attribute value for <code>BULKPARENTID</code> using the alias
   ** name <code>bulkParentId</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>BULKPARENTID</code> using the alias name
   **                            <code>bulkParentId</code>.
   **                            Allowed endpoint is {@link Long}.
   */
  public void setBulkParentId(final Long value) {
    setAttributeInternal(BULKPARENTID, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getBulkParentId
  /**
   ** Returns the attribute value for <code>BULKPARENTID</code> using the alias
   ** name <code>bulkParentId</code>.
   **
   ** @return                    the attribute value for
   **                            <code>BULKPARENTID</code> using the alias name
   **                            <code>bulkParentId</code>.
   **                            Possible endpoint is {@link Long}.
   */
  public Long getBulkParentId() {
    return (Long)getAttributeInternal(BULKPARENTID);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setStatus
  /**
   ** Sets the attribute value for <code>STATUS</code> using the alias name
   ** <code>status</code>.
   **
   ** @param  value              the attribute value for <code>STATUS</code>
   **                            using the alias name <code>status</code>.
   **                            Allowed display is {@link String}.
   */
  public void setStatus(final String value) {
    setAttributeInternal(STATUS, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getStatus
  /**
   ** Returns the attribute value for <code>STATUS</code> using the alias
   ** name <code>status</code>.
   **
   ** @return                    the attribute value for <code>STATUS</code>
   **                            using the alias name <code>status</code>.
   **                            Possible display is {@link String}.
   */
  public String getStatus() {
    return (String)getAttributeInternal(STATUS);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setParentId
  /**
   ** Sets the attribute value for <code>PARENTID</code> using the alias name
   ** <code>parentId</code>.
   **
   ** @param  value              the attribute value for <code>PARENTID</code>
   **                            using the alias name <code>parentId</code>.
   **                            Allowed endpoint is {@link Long}.
   */
  public void setParentId(final Long value) {
    setAttributeInternal(PARENTID, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getParentId
  /**
   ** Returns the attribute value for <code>PARENTID</code> using the alias
   ** name <code>parentId</code>.
   **
   ** @return                    the attribute value for <code>PARENTID</code>
   **                            using the alias name <code>parentId</code>.
   **                            Possible endpoint is {@link Long}.
   */
  public Long getParentId() {
    return (Long)getAttributeInternal(PARENTID);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setDependendId
  /**
   ** Sets the attribute value for <code>DEPENDENDID</code> using the alias name
   ** <code>dependendId</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>DEPENDENDID</code>
   **                            using the alias name <code>dependendId</code>.
   **                            Allowed endpoint is {@link Long}.
   */
  public void setDependendId(final Long value) {
    setAttributeInternal(DEPENDENDID, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getDependendId
  /**
   ** Returns the attribute value for <code>DEPENDENDID</code> using the alias
   ** name <code>dependendId</code>.
   **
   ** @return                   the attribute value for
   **                            <code>DEPENDENDID</code>
   **                            using the alias name <code>dependendId</code>.
   **                            Possible endpoint is {@link Long}.
   */
  public Long getDependendId() {
    return (Long)getAttributeInternal(DEPENDENDID);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setEntityId
  /**
   ** Sets the attribute value for <code>ENTITYID</code> using the alias name
   ** <code>entityId</code>.
   **
   ** @param  value              the attribute value for <code>ENTITYID</code>
   **                            using the alias name <code>entityId</code>.
   **                            Allowed object is {@link String}.
   */
  public void setEntityId(final String value) {
    setAttributeInternal(ENTITYID, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEventId
  /**
   ** Returns the attribute value for <code>ENTITYID</code> using the alias name
   ** <code>entityId</code>.
   **
   ** @return                    the attribute value for <code>ENTITYID</code>
   **                            using the alias name <code>entityId</code>.
   **                            Possible object is {@link String}.
   */
  public String getEntityId() {
    return (String)getAttributeInternal(ENTITYID);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setEntityType
  /**
   ** Sets the attribute value for <code>ENTITYTYPE</code> using the alias name
   ** <code>entityType</code>.
   **
   ** @param  value              the attribute value for <code>ENTITYTYPE</code>
   **                            using the alias name <code>entityType</code>.
   **                            Allowed object is {@link String}.
   */
  public void setEntityType(final String value) {
    setAttributeInternal(ENTITYTYPE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getEntityType
  /**
   ** Returns the attribute value for <code>ENTITYTYPE</code> using the alias
   ** name <code>entityType</code>.
   **
   ** @return                    the attribute value for <code>ENTITYTYPE</code>
   **                            using the alias name <code>entityType</code>.
   **                            Possible object is {@link String}.
   */
  public String getEntityType() {
    return (String)getAttributeInternal(ENTITYTYPE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setOutOfBandEvents
  /**
   ** Sets the attribute value for <code>OUTOFBANDEVENTS</code> using the alias
   ** name <code>outOfBandEvents</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>OUTOFBANDEVENTS</code> using the alias
   **                            name <code>outOfBandEvents</code>.
   **                            Allowed object is {@link Boolean}.
   */
  public void setOutOfBandEvents(final Boolean value) {
    setAttributeInternal(OUTOFBANDEVENTS, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getOutOfBandEvents
  /**
   ** Returns the attribute value for <code>OUTOFBANDEVENTS</code> using the
   ** alias name <code>outOfBandEvents</code>.
   **
   ** @return                    the attribute value for
   **                            <code>OUTOFBANDEVENTS</code> using the alias
   **                            name <code>outOfBandEvents</code>.
   **                            Possible object is {@link Boolean}.
   */
  public Boolean getOutOfBandEvents() {
    return (Boolean)getAttributeInternal(OUTOFBANDEVENTS);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setOperation
  /**
   ** Sets the attribute value for <code>OPERATION</code> using the alias name
   ** <code>operation</code>.
   **
   ** @param  value              the attribute value for <code>OPERATION</code>
   **                            using the alias name <code>operation</code>.
   **                            Allowed endpoint is {@link String}.
   */
  public void setOperation(final String value) {
    setAttributeInternal(OPERATION, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getOperation
  /**
   ** Returns the attribute value for <code>OPERATION</code> using the alias
   ** name <code>operation</code>.
   **
   ** @return                    the attribute value for <code>OPERATION</code>
   **                            using the alias name <code>operation</code>.
   **                            Possible endpoint is {@link String}.
   */
  public String getOperation() {
    return (String)getAttributeInternal(OPERATION);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setStage
  /**
   ** Sets the attribute value for <code>STAGE</code> using the alias name
   ** <code>stage</code>.
   **
   ** @param  value              the attribute value for <code>STAGE</code>
   **                            using the alias name <code>stage</code>.
   **                            Allowed object is {@link String}.
   */
  public void setStage(final String value) {
    setAttributeInternal(STAGE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getStage
  /**
   ** Returns the attribute value for <code>STAGE</code> using the alias name
   ** <code>stage</code>.
   **
   ** @return                    the attribute value for <code>STAGE</code>
   **                            using the alias name <code>stage</code>.
   **                            Possible object is {@link String}.
   */
  public String getStage() {
    return (String)getAttributeInternal(STAGE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setChangeType
  /**
   ** Sets the attribute value for <code>CHANGETYPE</code> using the alias name
   ** <code>changeType</code>.
   **
   ** @param  value              the attribute value for <code>CHANGETYPE</code>
   **                            using the alias name <code>changeType</code>.
   **                            Allowed display is {@link String}.
   */
  public void setChangeType(final String value) {
    setAttributeInternal(CHANGETYPE, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getChangeType
  /**
   ** Returns the attribute value for <code>CHANGETYPE</code> using the alias
   ** name <code>changeType</code>.
   **
   ** @return                    the attribute value for <code>CHANGETYPE</code>
   **                            using the alias name <code>changeType</code>.
   **                            Possible display is {@link String}.
   */
  public String getChangeType() {
    return (String)getAttributeInternal(CHANGETYPE);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setRetry
  /**
   ** Sets the attribute value for <code>RETRY</code> using the alias name
   ** <code>retry</code>.
   **
   ** @param  value              the attribute value for <code>RETRY</code>
   **                            using the alias name <code>retry</code>.
   **                            Allowed object is {@link Long}.
   */
  public void setRetry(final Long value) {
    setAttributeInternal(RETRY, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getRetry
  /**
   ** Returns the attribute value for <code>RETRY</code> using the alias
   ** name <code>retry</code>.
   **
   ** @return                    the attribute value for <code>RETRY</code>
   **                            using the alias name <code>retry</code>.
   **                            Possible object is {@link Long}.
   */
  public Long getRetry() {
    return (Long)getAttributeInternal(RETRY);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setCeatedOn
  /**
   ** Sets the attribute value for <code>CREATEDON</code> using the alias name
   ** <code>createdOn</code>.
   **
   ** @param  value              the attribute value for <code>CREATEDON</code>
   **                            using the alias name <code>createdOn</code>.
   **                            Allowed object is {@link Timestamp}.
   */
  public void setCeatedOn(final Timestamp value) {
    setAttributeInternal(CREATEDON, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getCeatedOn
  /**
   ** Returns the attribute value for <code>CREATEDON</code> using the alias
   ** name <code>createdOn</code>.
   **
   ** @return                    the attribute value for <code>CREATEDON</code>
   **                            using the alias name <code>createdOn</code>.
   **                            Possible object is {@link Timestamp}.
   */
  public Timestamp getCeatedOn() {
    return (Timestamp)getAttributeInternal(CREATEDON);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setModifiedOn
  /**
   ** Sets the attribute value for <code>MODIFIEDON</code> using the alias name
   ** <code>modifiedOn</code>.
   **
   ** @param  value              the attribute value for <code>MODIFIEDON</code>
   **                            using the alias name <code>modifiedOn</code>.
   **                            Allowed object is {@link Timestamp}.
   */
  public void setModifiedOn(final Timestamp value) {
    setAttributeInternal(MODIFIEDON, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getModifiedOn
  /**
   ** Returns the attribute value for <code>MODIFIEDON</code> using the alias
   ** name <code>modifiedOn</code>.
   **
   ** @return                    the attribute value for <code>MODIFIEDON</code>
   **                            using the alias name <code>modifiedOn</code>.
   **                            Possible object is {@link Timestamp}.
   */
  public Timestamp getModifiedOn() {
    return (Timestamp)getAttributeInternal(MODIFIEDON);
  }
}