/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Administration Management

    File        :   TaskVORowImpl.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    TaskVORowImpl.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysadmin.model.view;

import oracle.jbo.server.ViewRowImpl;

////////////////////////////////////////////////////////////////////////////////
// class TaskVORowImpl
// ~~~~~ ~~~~~~~~~~~~~
/**
 ** ---------------------------------------------------------------------
 ** --- File generated by Oracle ADF Business Components Design Time.
 ** --- Tue Mar 07 07:51:54 CET 2017
 ** --- Custom code may be added to this class.
 ** --- Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public class TaskVORowImpl extends ViewRowImpl {

  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  public static final int NAME        = AttributesEnum.name.ordinal();
  public static final int CLASSNAME   = AttributesEnum.className.ordinal();
  public static final int DESCRIPTION = AttributesEnum.description.ordinal();
  public static final int RETRYCOUNT  = AttributesEnum.retryCount.ordinal();

  //////////////////////////////////////////////////////////////////////////////
  // Member classes
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // class AttributesEnum
  /**
   ** AttributesEnum: generated enum for identifying attributes and accessors.
   ** Do not modify.
   */
  @SuppressWarnings("oracle.jbo.attribute-order-rule")
  private static enum AttributesEnum {
      name
    , className
    , description
    , retryCount
    ;
  };

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>TaskVORowImpl</code> view object that allows use as a
   ** JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public TaskVORowImpl() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Accessor and Mutator methods
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setName
  /**
   ** Sets the attribute value for <code>NAME</code> using the alias name
   ** <code>name</code>.
   **
   ** @param  value              the attribute value for <code>NAME</code>
   **                            using the alias name <code>name</code>.
   **                            Allowed object is {@link String}.
   */
  public void setName(final String value) {
    setAttributeInternal(NAME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getName
  /**
   ** Returns the attribute value for <code>NAME</code> using the alias
   ** name <code>name</code>.
   **
   ** @return                    the attribute value for <code>NAME</code>
   **                            using the alias name <code>name</code>.
   **                            Possible object is {@link String}.
   */
  public String getName() {
    return (String)getAttributeInternal(NAME);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setClassName
  /**
   ** Sets the attribute value for <code>CLASSNAME</code> using the alias name
   ** <code>className</code>.
   **
   ** @param  value              the attribute value for <code>CLASSNAME</code>
   **                            using the alias name <code>className</code>.
   **                            Allowed object is {@link String}.
   */
  public void setClassName(final String value) {
    setAttributeInternal(CLASSNAME, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getClassName
  /**
   ** Returns the attribute value for <code>CLASSNAME</code> using the alias
   ** name <code>className</code>.
   **
   ** @return                    the attribute value for <code>CLASSNAME</code>
   **                            using the alias name <code>className</code>.
   **                            Possible object is {@link String}.
   */
  public String getClassName() {
    return (String)getAttributeInternal(CLASSNAME);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setDescription
  /**
   ** Sets the attribute value for <code>DESCRIPTION</code> using the alias name
   ** <code>description</code>.
   **
   ** @param  value              the attribute value for
   **                            <code>DESCRIPTION</code> using the alias name
   **                            <code>description</code>.
   **                            Allowed object is {@link String}.
   */
  public void setDescription(final String value) {
    setAttributeInternal(DESCRIPTION, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getDescription
  /**
   ** Returns the attribute value for <code>DESCRIPTION</code> using the alias
   ** name <code>description</code>.
   **
   ** @return                    the attribute value for
   **                            <code>DESCRIPTION</code> using the alias name
   **                            <code>description</code>.
   **                            Possible object is {@link String}.
   */
  public String getDescription() {
    return (String)getAttributeInternal(DESCRIPTION);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   setRetryCount
  /**
   ** Sets the attribute value for <code>RETRYCOUNT</code> using the alias name
   ** <code>retryCount</code>.
   **
   ** @param  value              the attribute value for <code>RETRYCOUNT</code>
   **                            using the alias name <code>retryCount</code>.
   **                            Allowed object is {@link Integer}.
   */
  public void setRetryCount(final Integer value) {
    setAttributeInternal(RETRYCOUNT, value);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methode:   getRetryCount
  /**
   ** Returns the attribute value for <code>RETRYCOUNT</code> using the alias
   ** name <code>retryCount</code>.
   **
   ** @return                    the attribute value for <code>RETRYCOUNT</code>
   **                            using the alias name <code>retryCount</code>.
   **                            Possible object is {@link Integer}.
   */
  public Integer getRetryCount() {
    return (Integer)getAttributeInternal(RETRYCOUNT);
  }
}