/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2020. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Employee Portal
    Subsystem   :   Vehicle Management

    File        :   AdministrationAM.java

    Compiler    :   Oracle JDeveloper 11g

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the interface
                    AdministrationAM.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    1.0.0.0     2020-02-23  DSteding    First release version
*/

package bka.employee.portal.vehicle.module.common;

import oracle.jbo.ApplicationModule;

////////////////////////////////////////////////////////////////////////////////
// interface AdministrationAM
// ~~~~~~~~~ ~~~~~~~~~~~~~~~~
/**
 ** The {@link ApplicationModule} to coordinate certain task belonging to
 ** <code>Administration</code> in Employee Portal Vehicle Management.
 ** <p>
 ** ---------------------------------------------------------------------
 ** --- File generated by Oracle ADF Business Components Design Time.
 ** ---    Fri Feb 23 12:08:29 CET 2020
 ** --- Custom code may be added to this class.
 ** --- Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 1.0.0.0
 ** @since   1.0.0.0
 */
public interface AdministrationAM extends ApplicationModule {

  //////////////////////////////////////////////////////////////////////////////
  // Methods grouped by functionality
  //////////////////////////////////////////////////////////////////////////////
  
  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchBrandByIdentifier (AdministrationAM)
  /**
   ** Finds a certain  <code>Vehicle Manufactor Brand</code> by executing a
   ** query against the persistence layer which leverage the primary key of the
   ** entity object.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Vehicle Manufactor Brand</code> to fetch
   **                            from the persistence layer.
   **                            Allowed object is {@link String}.
   */
  void fetchBrandByIdentifier(final String identifier);
  
  //////////////////////////////////////////////////////////////////////////////
  // Method:   refreshBrandAttribute
  /**
   ** Refresh the attributes belonging to a certain
   ** <code>Vehicle Manufactor Brand</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Vehicle Manufactor Brand</code> to
   **                            initialize.
   **                            Allowed object is {@link Long}.
   */
  void refreshBrandAttribute(final Long identifier);
  
  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchBrandByIdentifier (AdministrationAM)
  /**
   ** Finds a certain  <code>Vehicle Color</code> by executing a query against
   ** the persistence layer which leverage the primary key of the entity object.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Vehicle Color</code> to fetch from the
   **                            persistence layer.
   **                            Allowed object is {@link String}.
   */
  void fetchColorByIdentifier(final String identifier);
  
  //////////////////////////////////////////////////////////////////////////////
  // Method:   refreshColorAttribute
  /**
   ** Refresh the attributes belonging to a certain
   ** <code>Vehicle Color</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Vehicle Color</code> to
   **                            initialize.
   **                            Allowed object is {@link Long}.
   */
  void refreshColorAttribute(final Long identifier);
  
  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchTypeByIdentifier (AdministrationAM)
  /**
   ** Finds a certain  <code>Vehicle Type</code> by executing a query against
   ** the persistence layer which leverage the primary key of the entity object.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Vehicle Type</code> to fetch from the
   **                            persistence layer.
   **                            Allowed object is {@link String}.
   */
  void fetchTypeByIdentifier(final String identifier);
  
  //////////////////////////////////////////////////////////////////////////////
  // Method:   refreshTypeAttribute
  /**
   ** Refresh the attributes belonging to a certain
   ** <code>Vehicle Type</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Vehicle Type</code> to
   **                            initialize.
   **                            Allowed object is {@link Long}.
   */
  void refreshTypeAttribute(final Long identifier);
}