/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2020. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Employee Portal
    Subsystem   :   Vehicle Management

    File        :   VehicleAM.java

    Compiler    :   Oracle JDeveloper 12g

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the interface
                    VehicleAM.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    1.0.0.0     2020-02-23  DSteding    First release version
*/

package bka.employee.portal.vehicle.module.common;

import java.util.Map;

import oracle.jbo.ApplicationModule;

////////////////////////////////////////////////////////////////////////////////
// interface VehicleAM
// ~~~~~~~~~ ~~~~~~~~~
/**
 ** The {@link ApplicationModule} to coordinate certain task belonging to
 ** <code>Vehicle</code> in Employee Portal Vehicle Management.
 ** <p>
 ** ---------------------------------------------------------------------
 ** --- File generated by Oracle ADF Business Components Design Time.
 ** ---    Fri Feb 23 12:08:29 CET 2020
 ** --- Custom code may be added to this class.
 ** --- Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 1.0.0.0
 ** @since   1.0.0.0
 */
public interface VehicleAM extends ApplicationModule {

  //////////////////////////////////////////////////////////////////////////////
  // Methods grouped by functionality
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   refreshBrandAttribute
  /**
   ** Refresh the attributes belonging to a certain
   ** <code>Vehicule</code>.
   **
   */
  void refreshVehiculeAttribute();
  
  //////////////////////////////////////////////////////////////////////////////
  // Method:   createDetail (VehicleAM)
  /**
   ** Initialize the model to create a new <code>Vehicule</code>.
   */
  void createDetail();
  
  /////////////////////////////////////////////////////////////////////////////
  // Method:   fetchVehicleByIdentifier (AdministrationAM)
  /**
   ** Finds a certain  <code>Vehicle</code> by executing a
   ** query against the persistence layer which leverage the primary key of the
   ** entity object.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Vehicle</code> to fetch
   **                            from the persistence layer.
   **                            Allowed object is {@link String}.
   */
  void fetchVehicleByIdentifier(final String identifier);
  
  //////////////////////////////////////////////////////////////////////////////
  // Method:   requeryPublication (ApplicationInstanceAM)
  /**
   ** Initialize the <code>Attribute</code>s belonging to a certain
   ** <code>Vehicule</code> to take in account pending changes on
   ** attribute.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Vehicule</code> to
   **                            initialize.
   **                            Allowed object is {@link String}.
   ** @param  pending            the collection of pending changes belonging to
   **                             modified attribute.
   */
  void requeryAttribute(final String identifier, final Map<String, Object> pending);
}

