/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Configuration Management

    File        :   LookupAMClient.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    LookupAMClient.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysconfig.module.client;

import java.util.Map;
import java.util.List;

import oracle.jbo.client.remote.ApplicationModuleImpl;

import oracle.iam.identity.sysconfig.module.common.LookupAM;

import oracle.iam.identity.sysconfig.schema.LookupAdapter;
import oracle.iam.identity.sysconfig.schema.LookupValueAdapter;

////////////////////////////////////////////////////////////////////////////////
// class LookupAMClient
// ~~~~~ ~~~~~~~~~~~~~~
/**
 ** The remote {@link ApplicationModuleImpl} to coordinate certain task
 ** belonging to <code>Lookup Definition</code>s.
 ** <p>
 ** ---------------------------------------------------------------------
 ** ---    File generated by Oracle ADF Business Components Design Time.
 ** ---    Mon Mar 06 19:50:30 CET 2017
 ** ---    Custom code may be added to this class.
 ** ---    Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public class LookupAMClient extends    ApplicationModuleImpl
                            implements LookupAM {

  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  // the official serial version ID which says cryptically which version we're
  // compatible with
  @SuppressWarnings("compatibility:-7948032396315386484")
  private static final long serialVersionUID = 4371222462438301985L;

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>LookupAMClient</code> application module that
   ** allows use as a JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public LookupAMClient() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methods of implemented interfaces
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchByIdentifier (LookupAM)
  /**
   ** Finds a certain <code>Lookup Definition</code> by executing a query
   ** against the persistence layer which leverage the primary key of the entity
   ** object.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Lookup Definition</code> to fetch from
   **                            the persistence layer.
   **                            Allowed object is {@link String}.
   */
  @Override
  public void fetchByIdentifier(final String identifier) {
    riInvokeExportedMethod(this, "fetchByIdentifier", new String [] {"java.lang.String"}, new Object[] {identifier});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchByName (LookupAM)
  /**
   ** Finds a certain <code>Lookup Definition</code> by executing a query
   ** against the persistence layer which leverage the unique key of the entity
   ** object.
   **
   ** @param  name               the unique identifier of the
   **                            <code>Lookup Definition</code> to fetch from
   **                            the persistence layer.
   **                            Allowed object is {@link String}.
   */
  @Override
  public void fetchByName(final String name) {
    this.riInvokeExportedMethod(this, "fetchByName", new String [] {"java.lang.String"}, new Object[] {name});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchDetail (LookupAM)
  /**
   ** Initialize the model to maintain an existing
   ** <code>Lookup Definition</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Lookup Definition</code> to fetch from the
   **                            persistence layer.
   **                            Allowed object is {@link String}.
   */
  @Override
  public void fetchDetail(final String identifier) {
    this.riInvokeExportedMethod(this, "fetchDetail", new String [] {"java.lang.String"}, new Object[] {identifier});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   createDetail (LookupAM)
  /**
   ** Initialize the model to create a new <code>Lookup Definition</code>.
   */
  @Override
  public void createDetail() {
    this.riInvokeExportedMethod(this, "createDetail", null, null);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   createDetail (LookupAM)
  /**
   ** Creates a new <code>Lookup Definition</code>.
   **
   ** @param  mab                the {@link LookupAdapter} model adapter bean,
   **                            with fields set.
   ** @param  value              the {@link List} of {@link LookupValueAdapter}
   **                            model adapter beans, with fields set.
   */
  @Override
  public void createDetail(final LookupAdapter mab, final List<LookupValueAdapter> value) {
    this.riInvokeExportedMethod(this, "createDetail", new String [] {"oracle.iam.identity.sysconfig.schema.LookupAdapter", "java.util.List<oracle.iam.identity.sysconfig.schema.LookupValueAdapter>"}, new Object[] {mab, value});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   modifyDetail (LookupAM)
  /**
   ** Modifies an existing <code>Lookup Definition</code>.
   **
   ** @param  mab                the {@link LookupAdapter} model adapter bean,
   **                            with fields set to create.
   ** @param  added              the {@link List} of {@link LookupValueAdapter}
   **                            model adapter beans, with fields set to be
   **                            added to the <code>Lookup Definition</code>
   **                            after its modified.
   ** @param  modified           the {@link List} of {@link LookupValueAdapter}
   **                            model adapter beans, with fields set to be
   **                            modified to the <code>Lookup Definition</code>
   **                            after its modified.
   ** @param  deleted            the {@link List} of {@link LookupValueAdapter}
   **                            model adapter beans, with fields set to be
   **                            deleted to the <code>Lookup Definition</code>
   **                            after its modified.
   */
  @Override
  public void modifyDetail(final LookupAdapter mab, final List<LookupValueAdapter> added, final List<LookupValueAdapter> modified, final List<LookupValueAdapter> deleted) {
    this.riInvokeExportedMethod(this, "modifyDetail", new String [] {"oracle.iam.identity.sysconfig.schema.LookupAdapter", "java.util.List<oracle.iam.identity.sysconfig.schema.LookupValueAdapter>", "java.util.List<oracle.iam.identity.sysconfig.schema.LookupValueAdapter>", "java.util.List<oracle.iam.identity.sysconfig.schema.LookupValueAdapter>"}, new Object[] {mab, added, modified, deleted});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchPicker (LookupAM)
  /**
   ** Initialize the model to fetch values from a
   ** <code>Lookup Definition</code>.
   **
   ** @param  name               the unique identifier of the
   **                            <code>Lookup Definition</code> the values needs
   **                            to be fetched from the persistence layer.
   **                            Allowed object is {@link String}.
   */
  @Override
  public void fetchPicker(final String name) {
    this.riInvokeExportedMethod(this, "fetchPicker", new String [] {"java.lang.String"}, new Object[] {name});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   refreshAttribute (LookupAM)
  /**
   ** Refresh the <code>Lookup Value</code>s belonging to a certain
   ** <code>Lookup Definition</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Lookup Definition</code> to refresh.
   **                            Allowed object is {@link String}.
   */
  @Override
  public void refreshAttribute(final String identifier) {
    this.riInvokeExportedMethod(this, "refreshAttribute", new String [] {"java.lang.String"}, new Object[] {identifier});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   refreshValue (LookupAM)
  /**
   ** Refresh the <code>Lookup Value</code>s belonging to a certain
   ** <code>Lookup Definition</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Lookup Definition</code> to refresh.
   **                            Allowed object is {@link String}.
   */
  @Override
  public void refreshValue(final String identifier) {
    this.riInvokeExportedMethod(this, "refreshValue", new String [] {"java.lang.String"}, new Object[] {identifier});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   createValue (LookupAM)
  /**
   ** Initialize the <code>Lookup Value</code>s belonging to a certain
   ** <code>Lookup Definition</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Lookup Definition</code> to initialize.
   **                            Allowed object is {@link String}.
   ** @param  pending            the collection of pending changes belonging to
   **                            assigned, remove and modified values.
   */
  @Override
  public void createValue(final String identifier, final Map<String, Map<String, Object>> pending) {
    this.riInvokeExportedMethod(this, "createValue", new String [] {"java.lang.String", "java.util.Map<java.lang.String, java.util.Map>"}, new Object[] {identifier, pending});
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   requeryValue (LookupAM)
  /**
   ** Requery the <code>Lookup Value</code>s belonging to a certain
   ** <code>Lookup Definition</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Lookup Definition</code> to query.
   **                            Allowed object is {@link String}.
   ** @param  pending            the collection of pending changes belonging to
   **                            assigned, remove and modified values.
   */
  @Override
  public void requeryValue(final String identifier, final Map<String, Map<String, Object>> pending) {
    this.riInvokeExportedMethod(this, "requeryValue", new String [] {"java.lang.String", "java.util.Map<java.lang.String, java.util.Map>"}, new Object[] {identifier, pending});
  }
}