/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Configuration Management

    File        :   NotificationTemplateAMImpl.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    NotificationTemplateAMImpl.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysconfig.module;

import oracle.jbo.Row;

import oracle.jbo.server.ApplicationModuleImpl;

import oracle.iam.ui.platform.model.filter.Criterion;

import oracle.iam.identity.sysconfig.module.common.NotificationTemplateAM;

import oracle.iam.identity.sysconfig.model.view.NotificationTemplateVOImpl;

import oracle.iam.identity.sysconfig.schema.NotificationTemplateAdapter;
import oracle.iam.identity.sysconfig.schema.NotificationTemplateDataProvider;

////////////////////////////////////////////////////////////////////////////////
// class NotificationTemplateAMImpl
// ~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~
/**
 ** The local {@link ApplicationModuleImpl} to coordinate certain task
 ** belonging to <code>Properties</code>.
 ** <p>
 ** ---------------------------------------------------------------------
 ** --- File generated by Oracle ADF Business Components Design Time.
 ** --- Mon Mar 06 19:50:30 CET 2017
 ** --- Custom code may be added to this class.
 ** --- Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public class NotificationTemplateAMImpl extends    ApplicationModuleImpl
                                        implements NotificationTemplateAM {

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>NotificationTemplateAMImpl</code> application module
   ** that allows use as a JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public NotificationTemplateAMImpl() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Accessor methods
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   detailView
  /**
   ** Container's getter for {@link NotificationTemplateVOImpl}.
   **
   ** @return                    the implementation of view object
   **                            <code>NotificationTemplateVO</code>.
   */
  private NotificationTemplateVOImpl detailView() {
    return (NotificationTemplateVOImpl)findViewObject("NotificationTemplateDetailVO");
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methods of implemented interfaces
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchByIdentifier (NotificationTemplateAM)
  /**
   ** Finds a certain <code>NotificationTemplate Definition</code> by executing a query
   ** against the persistence layer which leverage the primary key of the entity
   ** object.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>NotificationTemplate Definition</code> to fetch from
   **                            the persistence layer.
   **                            Allowed object is {@link String}.
   */
  @Override
  public void fetchByIdentifier(final Long identifier) {
    final NotificationTemplateVOImpl view = detailView();
    view.applyFilter(new Criterion(NotificationTemplateAdapter.PK, identifier));
    view.executeQuery();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchByName (NotificationTemplateAM)
  /**
   ** Finds a certain <code>NotificationTemplate Definition</code> by executing a query
   ** against the persistence layer which leverage the unique key of the entity
   ** object.
   **
   ** @param  name               the unique identifier of the
   **                            <code>NotificationTemplate Definition</code> to fetch from
   **                            the persistence layer.
   **                            Allowed object is {@link String}.
   */
  @Override
  public void fetchByName(final String name) {
    final NotificationTemplateVOImpl view = detailView();
    view.applyFilter(new Criterion(NotificationTemplateAdapter.NAME, name));
    view.executeQuery();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   createDetail (NotificationTemplateAM)
  /**
   ** Initialize the model to create a new <code>NotificationTemplate Definition</code>.
   */
  @Override
  public void createDetail() {
    final NotificationTemplateVOImpl  detail = detailView();
    final NotificationTemplateAdapter bean   = new NotificationTemplateAdapter();
    final Row             row    = detail.createRow();
    // call toRow to initialize, row handles lookups as well.
    bean.toRow(row, true);
    // initialize the primary key of the property to create with the proper
    // value to ensure the the iterators and dependend entities find the correct
    // binding value to initialize themself
    row.setAttribute(NotificationTemplateAdapter.PK,            "-1");
    row.setAttribute(NotificationTemplateAdapter.DATALEVEL,     2);
    // setting the proper row state to avoid the row is considered as candidate
    // for pending changes in ADF, until user types value by himself.
    row.setNewRowState(Row.STATUS_INITIALIZED);
    detail.insertRow(row);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   createDetail (NotificationTemplateAM)
  /**
   ** Creates a new <code>NotificationTemplate Definition</code>.
   **
   ** @param  mab                the {@link NotificationTemplateAdapter} model adapter bean,
   **                            with fields set to create.
   */
  @Override
  public void createDetail(final NotificationTemplateAdapter mab) {
    final NotificationTemplateVOImpl       detail   = detailView();
    final NotificationTemplateDataProvider provider = (NotificationTemplateDataProvider)detail.getDataProvider();
    provider.create(mab);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   modifyDetail (NotificationTemplateAM)
  /**
   ** Modifies an existing <code>NotificationTemplate Definition</code>.
   **
   ** @param  mab                the {@link NotificationTemplateAdapter} model adapter bean,
   **                            with fields set to create.
   */
  @Override
  public void modifyDetail(final NotificationTemplateAdapter mab) {
    final NotificationTemplateVOImpl       detail   = detailView();
    final NotificationTemplateDataProvider provider = (NotificationTemplateDataProvider)detail.getDataProvider();
    provider.update(mab);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchDetail (NotificationTemplateAM)
  /**
   ** Initialize the model to maintain an existing
   ** <code>NotificationTemplate Definition</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>NotificationTemplate Definition</code> to fetch from
   **                            the persistence layer.
   **                            Allowed object is {@link Long}.
   */
  @Override
  public void fetchDetail(final Long identifier) {
    fetchByIdentifier(identifier);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   refreshAttribute (NotificationTemplateAM)
  /**
   ** Refresh the <code>NotificationTemplate Value</code>s belonging to a certain
   ** <code>NotificationTemplate Definition</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>NotificationTemplate Definition</code> to refresh.
   **                            Allowed object is {@link Long}.
   */
  @Override
  public void refreshAttribute(final Long identifier) {
    final NotificationTemplateVOImpl view = detailView();
    view.reset();
    view.executeQuery();
  }
}