/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Provisioning Management

    File        :   EndpointAMImpl.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    EndpointAMImpl.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysprov.module;

import java.util.Map;

import oracle.jbo.Row;

import oracle.jbo.server.ApplicationModuleImpl;

import oracle.iam.ui.platform.model.filter.Criterion;

import oracle.iam.ui.platform.utils.SerializationUtils;

import oracle.iam.identity.sysprov.module.common.EndpointAM;

import oracle.iam.identity.sysprov.model.view.EndpointVOImpl;
import oracle.iam.identity.sysprov.model.view.EndpointParameterVOImpl;
import oracle.iam.identity.sysprov.model.view.EndpointAdministratorVOImpl;

import oracle.iam.identity.sysprov.schema.EndpointAdapter;
import oracle.iam.identity.sysprov.schema.EndpointParameterAdapter;
import oracle.iam.identity.sysprov.schema.EndpointAdministratorAdapter;

////////////////////////////////////////////////////////////////////////////////
// class EndpointAMImpl
// ~~~~~ ~~~~~~~~~~~~~~
/**
 ** The local {@link ApplicationModuleImpl} to coordinate certain task
 ** belonging to <code>IT Resource</code>s.
 ** <p>
 ** ---------------------------------------------------------------------
 ** --- File generated by Oracle ADF Business Components Design Time.
 ** --- Mon Mar 06 19:50:30 CET 2017
 ** --- Custom code may be added to this class.
 ** --- Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 **
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public class EndpointAMImpl extends    ApplicationModuleImpl
                            implements EndpointAM {

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>EndpointAMImpl</code> application module that allows
   ** use as a JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public EndpointAMImpl() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Accessor methods
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   detailView
  /**
   ** Container's getter for <code>EndpointDetailVO</code>.
   **
   ** @return                    the implementation of view object
   **                            <code>EndpointDetail</code>.
   */
  private EndpointVOImpl detailView() {
    return (EndpointVOImpl)findViewObject("EndpointDetailVO");
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   parameterView
  /**
   ** Container's getter for <code>EndpointParameterVO</code>.
   **
   ** @return                    the implementation of view object
   **                            <code>EndpointParameter</code>.
   */
  private EndpointParameterVOImpl parameterView() {
    return (EndpointParameterVOImpl)findViewObject("EndpointParameterVO");
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   administratorView
  /**
   ** Container's getter for <code>EndpointAdministratorVO</code>.
   **
   ** @return                    the implementation of view object
   **                            <code>EndpointAdministrator</code>.
   */
  private EndpointAdministratorVOImpl administratorView() {
    return (EndpointAdministratorVOImpl)findViewObject("EndpointAdministratorVO");
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methods of implemented interfaces
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchByIdentifier (EndpointAM)
  /**
   ** Finds a certain <code>IT Resource</code> by executing a query
   ** against the persistence layer which leverage the primary key of the entity
   ** object.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>IT Resource</code> to fetch from the
   **                            persistence layer.
   **                            Allowed object is {@link Long}.
   */
  @Override
  public void fetchByIdentifier(final Long identifier) {
    final EndpointVOImpl view = detailView();
    view.applyFilter(new Criterion(EndpointAdapter.PK, identifier));
    view.executeQuery();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchByName (EndpointAM)
  /**
   ** Finds a certain <code>IT Resource</code> by executing a query against the
   ** persistence layer which leverage the unique key of the entity object.
   **
   ** @param  name               the unique identifier of the
   **                            <code>IT Resource</code> to fetch from
   **                            the persistence layer.
   **                            Allowed object is {@link String}.
   */
  @Override
  public void fetchByName(final String name) {
    final EndpointVOImpl view = detailView();
    view.applyFilter(new Criterion(EndpointAdapter.NAME, name));
    view.executeQuery();

    // position the cursor on the first row
    view.first();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   createDetail (EndpointAM)
  /**
   ** Initialize the model to create a new <code>IT Resource</code>.
   */
  @Override
  public void createDetail() {
    final EndpointVOImpl  detail = detailView();
    final Row             row    = detail.createRow();
    // call toRow to initialize, row handles lookups as well.
    EndpointAdapter.build().toRow(row, true);
    // initialize the primary key of the IT Resource to create with the proper
    // value to ensure the iterators and dependend entities find the correct
    // binding value to initialize themself
    row.setAttribute(EndpointAdapter.PK, Long.valueOf(-1L));
    // setting the proper row state to avoid the row is considered as candidate
    // for pending changes in ADF, until user types value by himself.
    row.setNewRowState(Row.STATUS_INITIALIZED);
    detail.insertRow(row);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchDetail (EndpointAM)
  /**
   ** Initialize the model to create a new <code>IT Resource</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>IT Resource</code> to fetch from the
   **                            persistence layer.
   **                            Allowed object is {@link Long}.
   */
  @Override
  public void fetchDetail(final Long identifier) {
    fetchByIdentifier(identifier);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   refreshAttribute (EndpointAM)
  /**
   ** Refresh the attributes belonging to a certain <code>IT Resource</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>IT Resource</code> to initialize.
   **                            Allowed object is {@link Long}.
   */
  @Override
  public void refreshAttribute(final Long identifier) {
    final EndpointVOImpl view = detailView();
    view.reset();
    view.executeQuery();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   requeryParameter (EndpointAM)
  /**
   ** Refresh the <code>Parameter</code>s belonging to a certain
   ** <code>IT Resource</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>IT Resource</code> to query.
   **                            Allowed object is {@link Long}.
   ** @param  pending            the collection of pending changes belonging to
   **                            added, deleted and modified values.
   */
  @Override
  public void requeryParameter(final Long identifier, final Map<String, Map<String, Object>> pending) {
    final Criterion[] filter = {
      // put the IT Resource as the primary selector in the search criteria
      new Criterion(EndpointParameterAdapter.SVR_FK, identifier)
    , new Criterion(EndpointParameterAdapter.MOD,SerializationUtils.serializeToString(pending.get(EndpointParameterAdapter.MOD)))
    };
    final EndpointParameterVOImpl view = parameterView();
    view.applyFilter(filter);
    view.executeQuery();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   requeryAdministrator (EndpointAM)
  /**
   ** Refresh the <code>Administrator</code>s belonging to a certain
   ** <code>IT Resource</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>IT Resource</code> to query.
   **                            Allowed object is {@link Long}.
   ** @param  pending            the collection of pending changes belonging to
   **                            added, deleted and modified values.
   */
  @Override
  public void requeryAdministrator(final Long identifier, final Map<String, Map<String, Object>> pending) {
    final Criterion[] filter = {
      // put the IT Resource as the primary selector in the search criteria
      new Criterion(EndpointAdministratorAdapter.SVR_FK, identifier)
    , new Criterion(EndpointAdministratorAdapter.ADD,SerializationUtils.serializeToString(pending.get(EndpointAdministratorAdapter.ADD)))
    , new Criterion(EndpointAdministratorAdapter.DEL,SerializationUtils.serializeToString(pending.get(EndpointAdministratorAdapter.DEL)))
    , new Criterion(EndpointAdministratorAdapter.MOD,SerializationUtils.serializeToString(pending.get(EndpointAdministratorAdapter.MOD)))
    };
    final EndpointAdministratorVOImpl view = administratorView();
    view.applyFilter(filter);
    view.executeQuery();
  }
}