/*
    Oracle Deutschland GmbH

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2017. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Frontend Extension
    Subsystem   :   System Provisioning Management

    File        :   ResourceObjectAMImpl.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@oracle.com

    Purpose     :   This file implements the class
                    ResourceObjectAMImpl.


    Revisions   Date        Editor      Comment
    -----------+-----------+-----------+-----------------------------------
    2.0.0.0     2017-03-06  DSteding    First release version
*/

package oracle.iam.identity.sysprov.module;

import oracle.jbo.Row;

import oracle.jbo.server.ApplicationModuleImpl;

import oracle.iam.ui.platform.model.filter.Criterion;

import oracle.iam.identity.sysprov.module.common.ResourceObjectAM;

import oracle.iam.identity.sysprov.model.view.AccountVOImpl;
import oracle.iam.identity.sysprov.model.view.ResourceObjectVOImpl;
import oracle.iam.identity.sysprov.model.view.ReconciliationProfileVOImpl;
import oracle.iam.identity.sysprov.model.view.ResourceObjectAdministratorVOImpl;

import oracle.iam.identity.foundation.naming.ResourceObject;

import oracle.iam.identity.sysprov.schema.ResourceObjectAdapter;

////////////////////////////////////////////////////////////////////////////////
// class ResourceObjectAMImpl
// ~~~~~ ~~~~~~~~~~~~~~~~~~~~
/**
 ** The local {@link ApplicationModuleImpl} to coordinate certain task
 ** belonging to <code>Resource Object</code>s.
 ** <p>
 ** ---------------------------------------------------------------------
 ** --- File generated by Oracle ADF Business Components Design Time.
 ** --- Mon Mar 06 19:50:30 CET 2017
 ** --- Custom code may be added to this class.
 ** --- Warning: Do not modify method signatures of generated methods.
 ** ---------------------------------------------------------------------
 **
 ** @author  dieter.steding@oracle.com
 ** @version 2.0.0.0
 ** @since   2.0.0.0
 */
public class ResourceObjectAMImpl extends    ApplicationModuleImpl
                                  implements ResourceObjectAM {

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs a <code>ResourceObjectAMImpl</code> application module that
   ** allows use as a JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public ResourceObjectAMImpl() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Accessor methods
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   detailView
  /**
   ** Container's getter for <code>ResourceObjectDetailVO</code>.
   **
   ** @return                    the implementation of view object
   **                            <code>ResourceObjectDetail</code>.
   */
  private ResourceObjectVOImpl detailView() {
    return (ResourceObjectVOImpl)findViewObject("ResourceObjectDetailVO");
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   reconciliationView
  /**
   ** Container's getter for <code>ReconciliationProfileVO</code>.
   **
   ** @return                    the implementation of view object
   **                            <code>ReconciliationProfile</code>.
   */
  private ReconciliationProfileVOImpl reconciliationView() {
    return (ReconciliationProfileVOImpl)findViewObject("ReconciliationProfileVO");
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   administratorView
  /**
   ** Container's getter for <code>ResourceObjectAdministratorVO</code>.
   **
   ** @return                    the implementation of view object
   **                            <code>ResourceObjectAdministrator</code>.
   */
  private ResourceObjectAdministratorVOImpl administratorView() {
    return (ResourceObjectAdministratorVOImpl)findViewObject("ResourceObjectAdministratorVO");
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   accountView
  /**
   ** Container's getter for <code>AccountVO</code>.
   **
   ** @return                    the implementation of view object
   **                            <code>Account</code>.
   */
  private AccountVOImpl accountView() {
    return (AccountVOImpl)findViewObject("AccountVO");
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methods of implemented interfaces
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchByIdentifier (ResourceObjectAM)
  /**
   ** Finds a certain <code>Resource Object</code> by executing a query against
   ** the persistence layer which leverage the primary key of the entity object.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Resource Object</code> to fetch from
   **                            the persistence layer.
   */
  @Override
  public void fetchByIdentifier(final String identifier) {
    final ResourceObjectVOImpl view = detailView();
    view.applyFilter(new Criterion(ResourceObjectAdapter.PK, identifier));
    view.executeQuery();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchByName (ResourceObjectAM)
  /**
   ** Finds a certain <code>Resource Object</code> by executing a query against
   ** the persistence layer which leverage the unique key of the entity object.
   **
   ** @param  name               the unique identifier of the
   **                            <code>Resource Object</code> to fetch from
   **                            the persistence layer.
   */
  @Override
  public void fetchByName(final String name) {
    final ResourceObjectVOImpl view = detailView();
    view.applyFilter(new Criterion("objectsName", name));
    view.executeQuery();

    // position the cursor on the first row
    view.first();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   createDetail (ResourceObjectAM)
  /**
   ** Initialize the model to create a new <code>Resource Object</code>.
   */
  @Override
  public void createDetail() {
    final ResourceObjectVOImpl  detail = detailView();
    final Row                   row    = detail.createRow();
    // call toRow to initialize, row handles lookups as well.
    ResourceObjectAdapter.build().toRow(row, true);
    // initialize the primary key of the IT Resource to create with the proper
    // value to ensure the iterators and dependend entities find the correct
    // binding value to initialize themself
    row.setAttribute(ResourceObjectAdapter.PK,            "-1");
    row.setAttribute(ResourceObjectAdapter.ORDERFOR,      ResourceObject.ORDER_FOR_USER);
    row.setAttribute(ResourceObjectAdapter.TYPE,          ResourceObject.TYPE_APPLICATION);
    row.setAttribute(ResourceObjectAdapter.ALLOWALL,      "1");
    row.setAttribute(ResourceObjectAdapter.ALLOWMULTIPLE, "1");
    // setting the proper row state to avoid the row is considered as candidate
    // for pending changes in ADF, until user types value by himself.
    row.setNewRowState(Row.STATUS_INITIALIZED);
    detail.insertRow(row);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   fetchDetail (ResourceObjectAM)
  /**
   ** Initialize the model to create a new <code>Resource Object</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Resource Object</code> to fetch from the
   **                            persistence layer.
   **                            Allowed object is {@link String}.
   */
  @Override
  public void fetchDetail(final String identifier) {
    fetchByIdentifier(identifier);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   refreshAttribute (ResourceObjectAM)
  /**
   ** Refresh the attributes belonging to a certain
   ** <code>Resource Object</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Resource Object</code> to initialize.
   **                            Allowed object is {@link String}.
   */
  @Override
  public void refreshAttribute(final String identifier) {
    final ResourceObjectVOImpl view = detailView();
    view.reset();
    view.executeQuery();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   refreshReconciliation (ResourceObjectAM)
  /**
   ** Refresh the reconciliation belonging to a certain
   ** <code>Resource Object</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Resource Object</code> to initialize.
   **                            Allowed object is {@link String}.
   */
  @Override
  public void refreshReconciliation(final String identifier) {
    final ReconciliationProfileVOImpl view = reconciliationView();
    view.reset();
    view.executeQuery();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   refreshAdministrator (ResourceObjectAM)
  /**
   ** Refresh the administrators belonging to a certain
   ** <code>Resource Object</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Resource Object</code> to initialize.
   **                            Allowed object is {@link String}.
   */
  @Override
  public void refreshAdministrator(final String identifier) {
    final ResourceObjectAdministratorVOImpl view = administratorView();
    view.reset();
    view.executeQuery();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   refreshAccount (ResourceObjectAM)
  /**
   ** Refresh the accounts belonging to a certain <code>Resource Object</code>.
   **
   ** @param  identifier         the system identifier of the
   **                            <code>Resource Object</code> to initialize.
   **                            Allowed object is {@link String}.
   */
  @Override
  public void refreshAccount(final String identifier) {
    final AccountVOImpl view = accountView();
    view.reset();
    view.executeQuery();
  }
}