/*
    Oracle Deutschland BV & Co. KG

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2024. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Manager Connector Library
    Subsystem   :   Grafana Connector

    File        :   Entity.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@icloud.com

    Purpose     :   This file implements the class
                    Entity.


    Revisions    Date        Editor      Comment
    ------------+-----------+-----------+-----------------------------------
    1.0.0.0      2024-03-22  DSteding    First release version
*/

package oracle.iam.identity.icf.connector.grafana.schema;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.annotation.JsonProperty;

import oracle.iam.identity.icf.schema.Resource;
import oracle.iam.identity.icf.schema.Returned;
import oracle.iam.identity.icf.schema.Attribute;
import oracle.iam.identity.icf.schema.Mutability;

////////////////////////////////////////////////////////////////////////////////
// abstract class Entity
// ~~~~~~~~ ~~~~~ ~~~~~~
/**
 ** The base REST entity.
 ** <p>
 ** <code>Entity</code> is used when the domain is known ahead of time. In that
 ** case a developer can derive a class from <code>Embed</code> and annotate
 ** the class. The class should be a Java bean. This will make it easier to work
 ** with the REST object since you will just have plain old getters and setters
 ** for core attributes.
 **
 ** @param  <T>                  the type of the implementation.
 **                              <br>
 **                              This parameter is used for convenience to allow
 **                              better implementations of the entities
 **                              extending this class (entities can return their
 **                              own specific type instead of type defined by
 **                              this class only).
 **
 ** @author  dieter.steding@icloud.com
 ** @version 1.0.0.0
 ** @since   1.0.0.0
 */
public abstract class Entity<T extends Entity> implements Resource<T> {

  //////////////////////////////////////////////////////////////////////////////
  // static final attributes
  //////////////////////////////////////////////////////////////////////////////

  /**
   ** The JSON of the entity internal identifier attribute for users, teams and
   ** organizations.
   */
  public static final String ID           = "id";
  /**
   ** The JSON element name of the unique name attribute for users.
   */
  public static final String LOGIN        = "login";
  /**
   ** The JSON element name of the unique name attribute for teams,
   ** organizations and roles.
   */
  public static final String NAME         = "name";
  /**
   ** The JSON element name of the user password attribute.
   */
  public static final String PASSWORD     = "password";
  /**
   ** The JSON element of the email attribute for users and teams.
   */
  public static final String EMAIL        = "email";
  /**
   ** The JSON element of the activation status attribute of a user.
   */
  public static final String DISABLED     = "isDisabled";
  /**
   ** The JSON element of the administrator status attribute of a user.
   */
  public static final String ADMIN        = "isGrafanaAdmin";
  public static final String ADMIN_ALIAS  = "isAdmin";
  /**
   ** The JSON element of the organization id attribute for users and teams.
   */
  public static final String ORGANIZATION = "orgId";
  /**
   ** The JSON element of the avatar link attribute of a user.
   */
  public static final String AVATAR       = "avatarUrl";

  //////////////////////////////////////////////////////////////////////////////
  // instance attributes
  //////////////////////////////////////////////////////////////////////////////

  /**
   ** The internal identifier of the <code>Entity</code> resource generated by
   ** the Service Provider at time of creation.
   */
  @JsonProperty(ID)
  @JsonAlias(ORGANIZATION)
  @Attribute(value=Attribute.IDENTIFIER, required=true, mutability=Mutability.IMMUTABLE, returned=Returned.ALWAYS)
  protected String id;

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs an empty <code>Entity</code> REST Resource that allows use as a
   ** JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  protected Entity() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Accessor and Mutator methods
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   id
  /**
   ** Sets the internal identifier of the <code>Entity</code> generated by the
   ** Service Provider.
   **
   ** @param  value              the internal identifier of the
   **                            <code>Entity</code> generated by the Service
   **                            Provider.
   **                            <br>
   **                            Allowed object is {@link String}.
   **
   ** @return                    the <code>Entity</code> to allow method
   **                            chaining.
   **                            <br>
   **                            Possible object is <code>Entity</code>.
   **
   ** @throws NullPointerException if the unique identifier <code>value</code>
   **                              is <code>null</code>.
   */
  @SuppressWarnings({"unchecked", "cast"})
  public final T id(final String value) {
    this.id = Objects.requireNonNull(value);
    return (T)this;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   id
  /**
   ** Returns the internal identifier of the <code>Entity</code> generated by
   ** the Service Provider.
   **
   ** @return                    the internal identifier of the
   **                            <code>Entity</code> generated by the Service
   **                            Provider.
   **                            <br>
   **                            Possible object is {@link String}.
   */
  public final String id() {
    return this.id;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methods of implemented interfaces
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   toString (Resource)
  /**
   ** Returns the string representation for this instance in its minimal form.
   **
   ** @return                    the string representation for this instance in
   **                            its minimal form.
   **                            <br>
   **                            Possible object is {@link String}.
   */
  @Override
  public final String toString() {
    return this.id == null ? "<null>" : this.id;
  }
}