/*
    Oracle Deutschland BV & Co. KG

    This software is the confidential and proprietary information of
    Oracle Corporation. ("Confidential Information").  You shall not
    disclose such Confidential Information and shall use it only in
    accordance with the terms of the license agreement you entered
    into with Oracle.

    ORACLE MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
    SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
    PURPOSE, OR NON-INFRINGEMENT. ORACLE SHALL NOT BE LIABLE FOR ANY DAMAGES
    SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
    THIS SOFTWARE OR ITS DERIVATIVES.

    Copyright © 2024. All Rights reserved

    -----------------------------------------------------------------------

    System      :   Oracle Identity Manager Connector Library
    Subsystem   :   Grafana Connector

    File        :   Team.java

    Compiler    :   Oracle JDeveloper 12c

    Author      :   dieter.steding@icloud.com

    Purpose     :   This file implements the class
                    Team.


    Revisions    Date        Editor      Comment
    ------------+-----------+-----------+-----------------------------------
    1.0.0.0      2024-03-22  DSteding    First release version
*/

package oracle.iam.identity.icf.connector.grafana.schema;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import oracle.iam.identity.icf.schema.Schema;
import oracle.iam.identity.icf.schema.Resource;
import oracle.iam.identity.icf.schema.Returned;
import oracle.iam.identity.icf.schema.Attribute;
import oracle.iam.identity.icf.schema.Mutability;

////////////////////////////////////////////////////////////////////////////////
// final class Team
// ~~~~~ ~~~~~ ~~~~
/**
 ** The base REST team entity representation.
 **
 ** @author  dieter.steding@icloud.com
 ** @version 1.0.0.0
 ** @since   1.0.0.0
 */
@Schema("__TEAM__")
@JsonIgnoreProperties({"uid", "orgId", "memberCount", "permission", "accessControl"})
public final class Team implements Resource<Team> {

  //////////////////////////////////////////////////////////////////////////////
  // instance attributes
  //////////////////////////////////////////////////////////////////////////////

  /**
   ** The internal identifier of the <code>Entity</code> resource generated by
   ** the Service Provider at time of creation.
   */
  @JsonProperty(Entity.ID)
  @Attribute(value=Attribute.IDENTIFIER, required=true, mutability=Mutability.IMMUTABLE, returned=Returned.ALWAYS)
  protected String id;
  /**
   ** The unique identifier for the <code>Team</code> typically used as a label
   ** for the <code>Team</code> by Service Provider.
   */
  @JsonProperty(Entity.NAME)
  @Attribute(value=Attribute.UNIQUE, required=true, mutability=Mutability.MUTABLE, returned=Returned.ALWAYS)
  protected String name;
  /**
   ** The E-mail addresse for the <code>Team</code>.
   */
  @Attribute
  @JsonProperty(Entity.EMAIL)
  private String email;
  /**
   ** The relative path to the avatar of the <code>Team</code>.
   */
  @Attribute
  @JsonProperty(Entity.AVATAR)
  private String avatar;

  //////////////////////////////////////////////////////////////////////////////
  // Constructors
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   Ctor
  /**
   ** Constructs an empty <code>Team</code> REST representation that allows use
   ** as a JavaBean.
   ** <br>
   ** Zero argument constructor required by the framework.
   ** <br>
   ** Default Constructor
   */
  public Team() {
    // ensure inheritance
    super();
  }

  //////////////////////////////////////////////////////////////////////////////
  // Accessor and Mutator methods
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   id
  /**
   ** Sets the internal identifier of the <code>Entity</code> generated by the
   ** Service Provider.
   **
   ** @param  value              the internal identifier of the
   **                            <code>Team</code> generated by the Service
   **                            Provider.
   **                            <br>
   **                            Allowed object is {@link String}.
   **
   ** @return                    the <code>Team</code> to allow method chaining.
   **                            <br>
   **                            Possible object is <code>Team</code>.
   **
   ** @throws NullPointerException if the unique identifier <code>value</code>
   **                              is <code>null</code>.
   */
  public final Team id(final String value) {
    this.id = Objects.requireNonNull(value);
    return this;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   id
  /**
   ** Returns the internal identifier of the <code>Entity</code> generated by
   ** the Service Provider.
   **
   ** @return                    the internal identifier of the
   **                            <code>Entity</code> generated by the Service
   **                            Provider.
   **                            <br>
   **                            Possible object is {@link String}.
   */
  public final String id() {
    return this.id;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   name
  /**
   ** Sets the unique identifier of the <code>Team</code>.
   **
   ** @param  value              the unique identifier of the <code>Team</code>.
   **                            <br>
   **                            Allowed object is {@link String}.
   **
   ** @return                    the <code>Team</code> to allow method chaining.
   **                            <br>
   **                            Possible object is <code>Team</code>.
   **
   ** @throws NullPointerException if the unique identifier <code>value</code>
   **                              is <code>null</code>.
   */
  public final Team name(final String value) {
    this.name = Objects.requireNonNull(value);
    return this;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   name
  /**
   ** Returns the unique identifier of the <code>Team</code>.
   **
   ** @return                    the unique identifier of the <code>Team</code>.
   **                            <br>
   **                            Possible object is {@link String}.
   */
  public final String name() {
    return this.name;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   email
  /**
   ** Sets the email address of the <code>Team</code>.
   **
   ** @param  value              the email address of the <code>Team</code>.
   **                            <br>
   **                            Allowed object is {@link String}.
   **
   ** @return                    the <code>Team</code> to allow method chaining.
   **                            <br>
   **                            Possible object is <code>Team</code>.
   */
  public Team email(final String value) {
    this.email = value;
    return this;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   email
  /**
   ** Returns the email address of the <code>Team</code>.
   **
   ** @return                    the email address of the <code>Team</code>.
   **                            <br>
   **                            Possible object is {@link String}.
   */
  public String email() {
    return this.email;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   avatar
  /**
   ** Sets the relative path to the avatar of the <code>Team</code>.
   **
   ** @param  value              the relative path to the avatar of the
   **                            <code>Team</code>.
   **                            <br>
   **                            Allowed object is {@link String}.
   **
   ** @return                    the <code>Team</code> to allow method chaining.
   **                            <br>
   **                            Possible object is <code>Team</code>.
   */
  public Team avatar(final String value) {
    this.avatar = value;
    return this;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   avatar
  /**
   ** Returns the relative path to the avatar of the <code>Team</code>.
   **
   ** @return                    the relative path to the avatar of the
   **                            <code>Team</code>.
   **                            <br>
   **                            Possible object is {@link String}.
   */
  public String avatar() {
    return this.avatar;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methods of implemented interfaces
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   hashCode (Resource)
  /**
   ** Returns a hash code value for the object.
   ** <br>
   ** This method is supported for the benefit of hash tables such as those
   ** provided by {@link java.util.HashMap}.
   ** <p>
   ** The general contract of <code>hashCode</code> is:
   ** <ul>
   **   <li>Whenever it is invoked on the same object more than once during an
   **       execution of a Java application, the <code>hashCode</code> method
   **       must consistently return the same integer, provided no information
   **       used in <code>equals</code> comparisons on the object is modified.
   **       This integer need not remain consistent from one execution of an
   **       application to another execution of the same application.
   **   <li>If two objects are equal according to the
   **       <code>equals(Object)</code> method, then calling the
   **       <code>hashCode</code> method on each of the two objects must
   **       produce the same integer result.
   **   <li>It is <em>not</em> required that if two objects are unequal
   **       according to the {@link java.lang.Object#equals(java.lang.Object)}
   **       method, then calling the <code>hashCode</code> method on each of the
   **       two objects must produce distinct integer results. However, the
   **       programmer should be aware that producing distinct integer results
   **       for unequal objects may improve the performance of hash tables.
   ** </ul>
   **
   ** @return                    a hash code value for this object.
   **                            <br>
   **                            Possible object is <code>int</code>.
   */
  @Override
  public final int hashCode() {
    return Objects.hash(this.id, this.name);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   toString (Resource)
  /**
   ** Returns the string representation for this instance in its minimal form.
   **
   ** @return                    the string representation for this instance in
   **                            its minimal form.
   **                            <br>
   **                            Possible object is {@link String}.
   */
  @Override
  public final String toString() {
    return this.id == null ? "<null>" : this.id;
  }

  //////////////////////////////////////////////////////////////////////////////
  // Methods grouped by functionality
  //////////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////////
  // Method:   build
  /**
   ** Factory method to create a minimal <code>Team</code> resource.
   **
   ** @param  name               the unique identifier of the
   **                            <code>Team</code> (usually the value of the
   **                            <code>NAME</code> for the organization in
   **                            Identity Manager.
   **                            <br>
   **                            Allowed object is {@link String}.
   **
   ** @return                    the <code>Team</code> populated with the given
   **                            <code>name</code>.
   **                            <br>
   **                            Possible object is <code>Team</code>.
   **
   ** @throws NullPointerException if the public identifier <code>name</code> is
   **                              <code>null</code>.
   */
  public static Team build(final String name) {
    return new Team().name(name);
  }

  //////////////////////////////////////////////////////////////////////////////
  // Method:   equals (overridden)
  /**
   ** Indicates whether some other object is "equal to" this one according to
   ** the contract specified in {@link Object#equals(Object)}.
   ** <p>
   ** Two <code>Entities</code> are considered equal if and only if they
   ** represent the same properties. As a consequence, two given
   ** <code>Entities</code> may be different even though they contain the same
   ** set of properties with the same values, but in a different order.
   **
   ** @param  other              the reference object with which to compare.
   **                            <br>
   **                            Allowed object is {@link Object}.
   **
   ** @return                    <code>true</code> if this object is the same as
   **                            the object argument; <code>false</code>
   **                            otherwise.
   **                            <br>
   **                            Possible object is <code>boolean</code>.
   */
  @Override
  public final boolean equals(final Object other) {
    if (this == other)
      return true;

    if (other == null || getClass() != other.getClass())
      return false;

    final Team that = (Team)other;
    return Objects.equals(this.id, that.id) && Objects.equals(this.name, that.name);
  }
}